// 捷克语
var i18n =  {
  "mt": "Den",
  "xs": "Hodiny",
  "fz": "minuty",
  "wxts": "Tipy",
  "zzjz": "načítání...",
  "noData": "NO DATA",
  "jchj": "Kontrola přihlašovacího prostředí",
  "ckfw": "Referenční rozsah",
  "bbgl": {
    "bbts": "Připomenutí aktualizace verze",
    "official": "Jsou uvolněny nové funkce, přejděte prosím na oficiální webovou stránku a stáhněte si a aktualizujte nejnovější verzi.",
    "apple": "Jsou uvolněny nové funkce, přejděte prosím do App Store a stáhněte si upgradovanou verzi.",
    "google": "Jsou uvolněny nové funkce, přejděte prosím na Google Play a stáhněte si upgradovanou verzi."
  },
  "uds": {
    "uds0001": "Vybrat modul",
    "uds0002": "Vyberte modul ke čtení",
    "uds0003": "Seznam obsahuje všechny podporované moduly vybrané značky, doporučuje se vybrat pouze moduly, které se již ve voze nacházejí. Lze však vybrat všechny moduly. Systém automaticky rozpozná jednotky skutečně přítomné ve voze .",
    "uds0004": "Vybrat vše",
    "uds0005": "Zrušit výběr všeho",
    "uds0006": "Spustit diagnostiku",
    "uds0007": "Vlastní prodejce"
  },
  "yjdl": {
    "yxdl": "Přihlášení k e-mailu",
    "dlts": "Nejdřív zadejte grafický captcha a poté získejte e-mailový captcha",
    "sryx": "Zadejte prosím svůj email",
    "sryzm": "Zadejte prosím captcha",
    "xyb": "Další",
    "xgyx": "Upravit poštovní schránku",
    "yxdz": "E-mailová adresa",
    "fsyzm": "odeslat přístupový kód na e-mail",
    "yzm": "Přístupový kód",
    "cxfs": "sekundy do opětovného odeslání",
    "dl": "Přihlášení",
    "srtxyzm": "Zadejte levý grafický captcha",
    "yxbzq": "E-mail je nesprávný",
    "txyzmbzq": "Grafická captcha je nesprávná",
    "fsdx": "Odesílání captcha",
    "yxyzmfscg": "E-mail Captcha byl úspěšně odeslán",
    "yxbky": "Odesílání e-mailu je neobvyklé! Zkontrolujte prosím, zda je e-mailová adresa zadána správně a zda lze e-mail normálně přijímat.",
    "zzyz": "Ověřování",
    "yzmcw": "E-mail Captcha je nesprávný",
    "clxxgl": "Správa informací o vozidle",
    "gxxx": "Aktualizovat informace",
    "dlcg": "Přihlášení proběhlo úspěšně",
    "dlsb": "Přihlášení se nezdařilo",
    "clxx": "Informace o vozidle",
    "czxx": "Informace o majiteli vozu",
    "wdl": "Nepřihlášen",
    "cl": "Vozidlo"
  },

  "OBDxncs": {
    "bt": "Porovnání adaptérů",
    "fbt": "větší znamená rychlejší",
    "zjsd": "Optimální rychlost",
    "dqsd": "Aktuální rychlost",
    "xzmc": "Rychlost, jakou jsou parametry čteny z ECU za sekundu (jednotka: parametry/sekunda)",
    "sec_dt": "Testováno s Galaxy Note 8 a Pixel 2",
    "sec_dd1": "(1) Adaptéry Wi-Fi se pro Android obecně nedoporučují, protože většina telefonů při používání ztrácí datové připojení k internetu.",
    "sec_dd2": "(2) Všechny testované adaptéry jsou standardní Bluetooth, pokud není součástí jejich názvu 'WiFi', 'USB' nebo 'BLE'",
    "text2": "Porovnání OBD"
  },

  "tsxx": {
    "qxz": "vybrat",
    "qsr": "Zadejte prosím",
    "qqr": "Potvrdit",
    "qqx": "Zrušit",
    "notConnected": "Nejdřív prosím připojte své zařízení",
    "save": "Uložit formulář úspěšně.",
    "dsyh": "Spotřeba paliva při nečinnosti se vztahuje ke spotřebě paliva v aktuálním okamžiku, kdy vozidlo stojí, se statistickou jednotkou čas.",
    "xsyh": "Spotřeba paliva při řízení se vztahuje ke spotřebě paliva v aktuálním okamžiku, kdy je vozidlo v jízdním stavu, a jako statistická jednotka se bere vzdálenost.",
    "pjyh": "Průměrná spotřeba paliva se vztahuje ke spotřebě paliva na 100 kilometrů vozidla během tohoto procesu jízdy a zobrazí se až po ujetí delším než 1 km.",
    "cqyh": "Dlouhodobou spotřebou paliva se rozumí spotřeba paliva spotřebovaná vozidlem na 100 kilometrů během provozu APP.",
    "yhsupport": "Toto auto nepodporuje zobrazení spotřeby paliva",
    "cg": "úspěch",
    "noTrouble": "Blahopřejeme, vaše auto je bez závad, pokračujte prosím.",
    "noVin": "Zadejte 17místné číslo rámce, abychom vám mohli poskytnout lepší služby.",
    "gzzsd": "MIL je zkratka pro Malfunction Indicator Lamp. Když kontrolka MIL svítí, znamená to, že systém motoru může mít poruchu. Důvodem rozsvícení kontrolky MIL může být příliš mnoho usazenin uhlíku uvnitř škrticí klapky nebo motoru, nebo je poměr směsi nevyvážený po poruše lambda sondy nebo svítí kontrolka motoru z důvodu špatné kvality paliva benzinu a nedostatečného spalování vozidla.",
    "noDevelopment": "Ve vývoji, zůstaňte naladěni.",
    "zc": "Aktuálně k dispozici pro testování",
    "noSupport": "Momentálně nedostupné pro testování",
    "noNetwork": "Vaše síť je momentálně nedostupná. Žádná síť neovlivní váš zážitek.",
    "jy": "Zakázáno",
    "ywc": "Test stavu dokončen",
    "noCompelte": "Test stavu nebyl dokončen",
    "noSupportPid": "Vaše vozidlo nemá tento test!",
    "useReminders": "Připomenutí: Po pozastavení můžete přiblížit nebo se potulovat přejetím prstem po posuvníku nebo na dotykové obrazovce.",
    "noCompelteDes": "Pokud lze otestovat stav připravenosti, ale nedokončit jej, lze provést následující opatření jednotlivě: plně jet, udržovat vozidlo, vyčistit sestavu, modernizovat ECU atd. Doufáme, že proces jízdy bude v budoucnu provozován v souladu se specifikacemi a bude prováděna pravidelná údržba.",
    "fgf": "Tato funkce je exkluzivní pro oficiální produkty, použijte ji prosím po zakoupení!",
    "b25": "Tato funkce je exkluzivní pro B25, použijte ji prosím po zakoupení!"
  },

  "pid": {
    "dsyh": "Spotřeba paliva při nečinnosti",
    "xsyh": "spotřeba paliva",
    "ssyh": "Průměrná spotřeba",
    "pjyh": "Okamžitá spotřeba",
    "cqyh": "Dlouhodobá spotřeba paliva",
    "pjsd": "Průměrná rychlost",
    "xslc": "Ujetá vzdálenost",
    "DTC_legnth": "Počet kódů DTC uložených v této ECU",
    "MIL": "Stav kontrolky poruchy",
    "mil_0": "světlo vypnuto",
    "mil_1": "světlo svítí",
    "shxt": "Monitorování vynechání zapalování",
    "ryxt": "Monitorování palivového systému",
    "zhzj": "Komplexní monitorování komponent",

    "fdjlx": "Typ motoru",
    "ysfdj": "kompresní zapalování",
    "dhfdj": "jiskrové zapálení",
    "chj": "Monitorování katalyzátoru",
    "jrchj": "Monitorování vyhřívaného katalyzátoru",
    "zfxt": "Monitorování odpařovacího systému",
    "eckqxt": "Monitorování systému sekundárního vzduchu",
    "ktxtzlj": "Monitorování chladiva systému klimatizace",
    "ycgqjrq": "Monitorování vyhřívání senzoru kyslíku",
    "ycgqjk": "Monitorování senzorem kyslíku",
    "erg": "Monitorování systému EGR/VVT",
    "NMHC": "NMHC Catalyst monitoring",
    "NOx": "monitorování NOx/SCR",
    "yl": "Rezervováno",
    "zyyl": "Monitorování plnicího tlaku",
    "fqcgq": "Monitorování snímače výfukových plynů",
    "pmglq": "PM filtr Monitorování monitoru"
  },

  "sygl": {
    "xieyi": "Protokol",
    "tips1": "Připojit zařízení",
    "tips2": "Zapněte Bluetooth! Zobrazit nápovědu",
    "tips3": "Nemůžete najít zařízení? Zobrazit nápovědu",
    "tips4": "Zapněte služby určování polohy",
    "tips5": "Univerzální",
    "tips6": "Nákladově efektivní verze",
    "sdlj": "Vybrat připojení ručně"
  },

  "djz": {
    "noData": "Momentálně neexistují žádná data zmrazení",
    "previousFrame": "Předchozí snímek",
    "nextFrame": "Další snímek"
  },

  "fwgl": {
    "ybp": "Panel",
    "UDS": "Unified Diagnostic Service (Test)",
    "UDS_des": "Poskytovat sjednocenou diagnostiku vozidla, více ECU a více funkcí",
    "DTC": "Monitorování DTC",
    "DTC_des": "Poskytovat profesionální řešení pro chybové kódy vozidel",
    "xcfx": "Analýza cesty",
    "xcfx_des": "Analyzujte data každé cesty",
    "xncs": "Testování výkonu vozidla",
    "xncs_des": "Poskytnout profesionální zprávu o analýze výkonu vozidla",
    "sssjl": "tok dat v reálném čase",
    "sssjl_des": "Požádat o aktuální diagnostická data hnacího ústrojí",
    "gzzsd": "Detekce indikátoru poruchy",
    "gzzsd_des": "Poskytuje informace o provozu vozidla po rozsvícení nebo zhasnutí kontrolky poruchy",

    "pid0141": "Diagnostický stav připravenosti",
    "pid0141_des": "Poskytuje stav monitorování vozidla od vymazání DTC a aktuální provozní stav monitorování jízdního cyklu",
    "$05": "Výsledky monitorování kyslíkovým senzorem",
    "$05_des": "Přečíst výsledky testu monitorování lambda sondy ve vozidle",
    "$06": "Konkrétní výsledky monitorování",
    "$06_des": "povolit přístup k výsledkům testů monitorování On-Board Diagnostic pro konkrétní komponenty/systémy.",
    "$09": "Informace o vozidle",
    "$09_des": "Přečíst informace o vozidle a informace o konkrétním vozidle",

    "clnj": "",
    "clnj_des": "",

    "obdTest": "Test výkonu OBD",
    "obdTest_des": "Testujte různé ukazatele výkonu OBD pomocí automatických testovacích nástrojů.",
    "djz": "Zmrazit snímek",
    "djz_des": "Když se DTC objeví ve výfukovém systému, ECU uloží data, když se DTC objeví",
    "yjjc": "Úplná detekce vozidla jedním kliknutím",
    "yjjc_des": "Komplexní detekce všech dat ze snímačů vozidla, informací o vozidle, chybových kódů, zmrazených snímků a informací o sledování vozidla."
  },

  "yjjc": {
    "cljkxx": "informace o sledování vozidla",
    "xx_09": "Zjišťování informací o vozidle",
    "xx_03": "Zjišťování informací o poruše",
    "xx_01": "Detekce informací o sledování vozidla",
    "xx_02": "Detekce informací o zmrazeném snímku",
    "xx_05": "Detekce informací ze senzoru kyslíku",
    "xx_06": "Čtení konkrétních informací o výsledcích monitorování"
  },

  "ybpgl": {
    "dcdy": "Napětí baterie",
    "xhyb": "Truisemetr",
    "yhyb": "Měřič spotřeby paliva",
    "zdyyb": "Vlastní měřič",
    "xz": "Přidat řídicí panel",
    "bj": "Upravit řídicí panel",
    "sc": "Smazat řídicí panel",
    "delete_tips": "Opravdu chcete smazat řídicí panel?"
  },


  "status": {
    "1000": "Bluetooth není zapnuto",
    "1001": "Bluetooth je vypnuto",
    "1002": "Čekání na úsporu paliva",
    "1003": "Vyhledávání OBD",
    "1004": "Připojování OBD",
    "1005": "Bluetooth je připojeno",
    "1006": "úspěšný zápis dat",
    "1007": "Nepodařilo se zapsat data",
    "1008": "Úspěšně povolit upozornění",
    "1009": "Nenalezeno žádné zařízení"
  },


  "szgl": {
    "bt": "Nastavení",
    "label1": "Jazyk",
    "value1": "Sledovat systém",
    "label2": "Zásady ochrany osobních údajů",
    "label3": "Nápověda k připojení",
    "label4": "O",
    "label5": "Oficiální nákupní centrum",
    "value5": "1688 Mall",
    "label6": "Verze",
    "cjwt": "Běžný problém",
    "unittitle": "Jednotka",
    "unitvalue1": "Metrický systém",
    "unitvalue2": "Imperiální jednotky",
    "unitinfo": "Potvrdit, zda přepnout jednotky?"
  },

  "yygl": {
    "label": "Sledovat systém",
    "des": "Po zapnutí se automaticky nastaví podle jazyka systému",
    "en": "angličtina",
    "zh": "zjednodušená čínština",
    "zwft": "Tradiční čínština",
    "es": "španělština",
    "kr": "korejština",
    "ru": "ruština",
    "ja": "japonština",
    "it": "italština",
    "hi": "hindština",
    "pt": "portugalština",
    "de": "německy",
    "fr": "francouzština",
    "nl": "holandština",
    "fi": "finština",
    "pl": "polština",
    "bn": "bengálština",
		"hu": "maďarština",
		"cs": "čeština",
		"th": "thajština",
		"tr": "turečtina",
		"ms": "malajština",
		"ro": "rumunština",
		"sv": "švédština",
		"da": "dánština"
  },


  "obdManage": {
    "bt": "Správa OBD",
    "search_tip": "Hledejte prosím znovu nebo si kupte naše produkty",
    "buy_tip": "Nakupte prosím do obchodního centra",
    "searchAgain": "Hledej znovu",
    "nearBy": "Zařízení v blízkosti",
    "ls": "Historické vybavení",
    "bz": "Zobrazit nápovědu",
    "del": "Smazat",
    "delConfirm": "Opravdu chcete smazat tento záznam?",
    "switched": "Zařízení se chystá přepnout, jsi si jistý?",
    "qrxx": "Ověřte, že je zapnutý přepínač Bluetooth a informací o poloze mobilního telefonu.",
    "searchAgain_message": "Opravdu chcete znovu vyhledat zařízení v okolí?"
  },


  "gzjc": {
    "bt": "Diagnostika",
    "btn": "Zahájit testování",
    "des": "Zahajte úplnou kontrolu vašeho vozidla",
    "FaultCodeQuery": "Dotaz na chybový kód",
    "zzjc": "Testování",
    "clearFaultCode": "Vymazat chybový kód",
    "kscz": "hledat",
    "fxgz": "Byl nalezen chybový kód",
    "notFound": "nenalezeny žádné problémy",
    "cxjc": "Znovu zkontrolovat",
    "modalTitle": "Opravdu chcete vymazat chybový kód?",
    "modalContent": "Před vyřešením závady se doporučuje nemazat chybový kód libovolně. Většina ECU neumožňuje vymazat chybový kód, když motor běží. Zda lze chybový kód vymazat nebo ne, je nakonec určuje ECU. Smazání chybových kódů ve skutečnosti není řešením problému.",
    "sdjc": "Zpráva o hloubkové kontrole",
    "num": "Počet chybových kódů",
    "gzmxx": "Podrobnosti chybového kódu",
    "label1": "kategorie",
    "label2": "Vysvětlení chybového kódu",
    "definition_03": "Diagnostické chybové kódy",
    "definition_07": "Čekající diagnostické chybové kódy",
    "definition_0A": "Trvalé diagnostické chybové kódy",
    "03_des": "Když ECU (Řídící jednotka vozidla) detekuje abnormalitu, do paměti se uloží chybový kód. Tento chybový kód odkazuje na abnormální situaci zjištěnou během nedávného procesu jízdy. Tyto chybové kódy jsou uloženy v paměti po určitou dobu, když bude chybový kód znovu nalezen, aktualizujte dobu uchování.",
    "07_des": "Toto je nepotvrzená anomálie za jízdy. Pokud se anomálie opakuje a identifikuje, dočasný poruchový kód bude klasifikován jako potvrzený poruchový kód. Pokud nebude uložen, bude smazán po vypnutí motoru.",
    "0A_des": "Protože zobrazuje historii minulých kódů DTC, nepředstavuje aktuální stav vozidla. Odpovídající kódy DTC nemusí být možné programově odstranit.",
    "sys_P": "Systém hnacího ústrojí (definováno výrobcem)",
    "sys_B": "Systém karoserie (definováno výrobcem)",
    "sys_C": "Systém odpružení podvozku (definovaný výrobcem)",
    "sys_U": "Systém síťové komunikace (definováno výrobcem)",
    "zzs": "Všichni výrobci automobilů"
  },

  "clgl": {
    "bt": "Moje auto",
    "info1": "Základní informace o voze",
    "clpp": "Značky automobilů",
    "xh": "Model auta",
    "nk": "Rok",
    "rylx": "Typ paliva",
    "info2": "Další informace o vozidle",
    "atdp": "Komunikační protokol",
    "ati": "Verze adaptéru",
    "vin": "Identifikační číslo vozidla",
    "cid": "Identifikace kalibrace",
    "cvn": "Čísla pro ověření kalibrace",
    "ecu": "Elektronická řídicí jednotka",
    "ESN": "Sériové číslo motoru",
    "EROTAN": "Číslo předpisu nebo schválení typu výfuku",
    "FEOCNTR": "Počítadlo cyklů zapalování v provozu motoru",
    "obd": "OBDSUP"
  },

  "clbj": {
    "warn1": "Vyplňte prosím značku vozidla",
    "warn2": "je vyžadován model auta",
    "warn3": "je vyžadován rok auta",
    "warn4": "vin je vyžadován",
    "warn5": "Vyplňte prosím správné identifikační číslo vozidla",
    "warn6": "je vyžadováno jméno vlastníka auta",
    "warn7": "je vyžadován telefon",
    "warn8": "Zadejte prosím správný telefon",
    "warn9": "Zadejte prosím správný email",
    "bt": "Připojení OBD je úspěšné",
    "title_sub": "Následující informace jsou velmi důležité pro přesnou diagnostiku, aby se zlepšila vaše zkušenost. Nezapomeňte je pečlivě vyplnit.",
    "ts_vin": "Umístění kódu VIN: obvykle se nachází na levé straně přístrojové desky, vlevo dole na předním skle; je zde také sloupek pantů dveří, sloupek zámku dveří nebo jeden ze sloupků připojených k sloupek zámku dveří; nebo dveře v blízkosti sedadla řidiče uvnitř.",
    "vin": "Vin",
    "czxm": "Jméno",
    "lxdh": "Telefon",
    "lxyx": "E-mail"
  },
  "ota": {
    "bt": "Aktualizace OTA",
    "jcdxbb": "Byla zjištěna nová verze firmwaru",
    "gxnr": "Aktualizovat obsah",
    "fxsm": "Pokyny k upgradu",
    "fxsm_des": "Upgrade OTA (technologie over-the-air) znamená, že mobilní terminál vzdáleně stáhne aktualizační balíček na serveru za účelem aktualizace firmwaru OBD. Upgrade neovlivní bezpečnost vašeho vozidla a jízdy, neváhejte jej použít it. Pokud se zobrazí výzva, že aktualizace selhala, neopouštějte rozhraní, znovu vložte OBD a pokračujte v upgradu.",
    "zysx": "Upozornění",
    "zysx_des": "Neupgradujte za jízdy a během upgradu nevyjímejte ani nevypínejte OBD.",
    "mssj": "Upgradovat nyní",
    "kssj": "Spustit upgrade",
    "sjcg": "Aktualizace OTA proběhla úspěšně",
    "kqqxty": "Otevřít nové prostředí",
    "xzgj": "Stáhnout firmware",
    "zzxr": "Psaní",
    "zzsj": "Upgrade",
    "zzjy": "Ověřování integrity",
    "sjsb": "Upgrade se nezdařil, zkuste to znovu"
  },

  "xcfx": {
    "ksxc": "Zahájit cestu",
    "jsxc": "Ukončit cestu",
    "lsjl": "Historický záznam",
    "zlc": "Celkový počet najetých kilometrů",
    "hs": "Časově náročné",
    "kssj": "Čas zahájení",
    "zyh": "Celkový počet litrů"
  },

  "xncs": {
    "jsxn": "Zrychleno",
    "scxn": "Brzdění",
    "jlxn": "Vzdálenost",
    "des1": "Rozsah testu rychlosti",
    "des2": "rychlost při brzdění",
    "des3": "testovací vzdálenost",
    "aqtx": "věnujte prosím pozornost bezpečnosti jízdy!",
    "kscs": "Zahájit testování",
    "cxcs": "Znovu otestovat",
    "tz": "Stop",
    "tip1": "Upravte rychlost vozidla na",
    "tip2": "Pro zrychlení sešlápněte plynový pedál",
    "tip2_end": "Nahoře",
    "tip3": "Prosím šlápněte na brzdu, abyste snížili rychlost na",
    "tip4": "Jeďte prosím",
    "tip5": "Cestováno",
    "max_sd": "Nejvyšší rychlost",
    "max_jsd": "Maximální zrychlení",
    "max_zs": "Maximální rychlost",
    "tx1": "Počáteční rychlost nemůže být vyšší než koncová rychlost",
    "tx2": "Vyplňte rychlost brzdění větší než 0",
    "tx3": "Vyplňte prosím testovací vzdálenost větší než 0"
  },

  "bzxx": {
    "title1": "Krok 1: Nastartujte vozidlo",
    "title2": "Krok 2: Připojte zařízení",
    "title3": "Krok 3: Zapněte Bluetooth a určování polohy",
    "title4": "Krok 4: Otevřete APP",
    "title5": "Krok 5: Připojte zařízení",
    "text1": "Najděte umístění rozhraní OBD vozidla. Rozhraní OBD je 16kolíkové rozhraní samice. Rozhraní je lichoběžníkové. Některé modely mají na rozhraní OBD kryt. Běžné porty OBD jsou černé, bílé nebo modré. Umístění je obecně na panelu vnitřního obložení pod volantem, poblíž kolen řidiče. Umístění rozhraní OBD se může u různých modelů a modelů lišit. Následující obrázek ukazuje možné umístění rozhraní OBD:",
    "text2": "Po nalezení rozhraní OBD zapojte zařízení do rozhraní OBD. Ujistěte se, že je zapojeno až na doraz (mnoho aut je zapojeno zhruba v polovině a napájení je zapnuté, ale signální kolíky nemusí být připojeno) a svítí červený indikátor napájení nebo obrazovka.",
    "text3": "Zapněte na svém telefonu přepínače Bluetooth a polohy. Metoda: Přejeďte prstem dolů po horní části obrazovky telefonu, otevřete místní nabídku a klikněte na Bluetooth a informace o poloze. Zapněte Bluetooth na svém iOS zařízení.",
    "text4": "Otevřete aplikaci a povolte aplikaci používat informace o poloze.",
    "text5": "Po dokončení výše uvedených kroků zadejte APP, APP automaticky naskenuje zařízení OBD a zeptá se vás, zda zařízení připojit. Zařízení iOS se zeptá, zda chcete povolit přístup k adrese, klikněte na Povolit.",
    "text6": "Vyberte zařízení, které chcete připojit, a kliknutím se připojte. Po úspěšném připojení se na domovské stránce APP zobrazí název zařízení OBD, adresa Bluetooth a na palubní desce se zobrazí údaj."
  },

  "06fw": {
    "MID": "Název monitoru",
    "TID": "Testovací název",
    "CID": "Číslo součásti",
    "O2Sensor": "Název snímače O2",
    "MIN": "Minimální limit",
    "MAX": "Maximální limit",
    "CURRENT": "Testovací hodnota"
  },

  "09fw": {
    "ipt": "Sledování výkonu při používání",
    "IPT_08_1": "Zjištěné počty podmínek monitorování OBD",
    "IPT_08_2": "Počítadlo cyklů zapalování",
    "IPT_08_3": "Počet dokončení monitoru katalyzátoru, svod 1",
    "IPT_08_4": "Zjištěné počty podmínek monitorování katalyzátoru, svod 1",
    "IPT_08_5": "Počet dokončení monitoru katalyzátoru, svod 2",
    "IPT_08_6": "Zjištěné počty podmínek monitorování katalyzátoru, svod 2",
    "IPT_08_7": "Počet dokončení monitorování senzoru O2, svod 1",
    "IPT_08_8": "Zjištěné počty podmínek monitorování senzoru O2, svod 1",
    "IPT_08_9": "Počet dokončení monitorování senzoru O2, svod 2",
    "IPT_08_10": "Zjištěné počty podmínek monitorování senzoru O2, svod 2",
    "IPT_08_11": "Počet podmínek dokončení monitorování EGR a/nebo VVT",
    "IPT_08_12": "Zjištěné počty podmínek monitorování EGR a/nebo VVT",
    "IPT_08_13": "Počet podmínek dokončení monitorování AIR (sekundární vzduch)",
    "IPT_08_14": "Zjištěné počty podmínek monitorování AIR (sekundární vzduch)",
    "IPT_08_15": "Počet podmínek dokončení monitorování EVAP",
    "IPT_08_16": "Zjištěné počty podmínek monitorování EVAP",
    "IPT_08_17": "Počet dokončení monitorování sekundárního senzoru O2, svod 1",
    "IPT_08_18": "Zjištěné počty podmínek monitorování sekundárního senzoru O2, svod 1",
    "IPT_08_19": "Počet dokončení monitorování sekundárního senzoru O2, svod 2",
    "IPT_08_20": "Zjištěné počty podmínek monitorování sekundárního senzoru O2, svod 2",

    "IPT_08_des_1": "zobrazuje, kolikrát bylo vozidlo provozováno za specifikovaných podmínek monitorování OBD (obecný jmenovatel).",
    "IPT_08_des_2": "zobrazuje počet, kolikrát byl motor nastartován.",
    "IPT_08_des_3": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci poruchy systému katalyzátoru na bloku 1 (čitatel).",
    "IPT_08_des_4": "zobrazuje, kolikrát bylo vozidlo provozováno za specifikovaných podmínek monitorování katalyzátoru (jmenovatel).",
    "IPT_08_des_5": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci poruchy 2. bloku katalyzátorového systému (čitatel).",
    "IPT_08_des_6": "zobrazuje, kolikrát bylo vozidlo provozováno za specifikovaných podmínek monitorování katalyzátoru (jmenovatel).",
    "IPT_08_des_7": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci poruchy lambda sondy 1 (čitatel).",
    "IPT_08_des_8": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování kyslíkovým senzorem (jmenovatel).",
    "IPT_08_des_9": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci selhání lambda sondy 2 (čitatel).",
    "IPT_08_des_10": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování lambda sondou (jmenovatel).",
    "IPT_08_des_11": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy systému EGR/VVT (čitatel).",
    "IPT_08_des_12": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování systému EGR/VVT (jmenovatel).",
    "IPT_08_des_13": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci selhání systému AIR (čitatel).",
    "IPT_08_des_14": "zobrazuje, kolikrát bylo vozidlo provozováno za určitých podmínek monitorování systému AIR (jmenovatel).",
    "IPT_08_des_15": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci 0,020” (nebo 0,040”) poruchy netěsnosti systému EVAP (čitatel).",
    "IPT_08_des_16": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách sledování netěsnosti systému EVAP (jmenovatel).",
    "IPT_08_des_17": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci selhání sekundárního lambda sondy 1 (čitatel).",
    "IPT_08_des_18": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování sekundární lambda sondy (jmenovatel).",
    "IPT_08_des_19": "zobrazuje, kolikrát byly zjištěny všechny podmínky nezbytné k detekci poruch sekundární lambda sondy 2 (čitatel).",
    "IPT_08_des_20": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování sekundární lambda sondy (jmenovatel).",

    "IPT_0B_1": "Zjištěné počty podmínek monitorování OBD",
    "IPT_0B_2": "Počítadlo cyklů zapalování",
    "IPT_0B_3": "Počet podmínek dokončení monitorování katalyzátoru NMHC",
    "IPT_0B_4": "Zjištěné počty podmínek monitorování katalyzátoru NMHC",
    "IPT_0B_5": "Počet podmínek dokončení monitorování katalyzátoru NOx/SCR",
    "IPT_0B_6": "Zjištěné počty podmínek monitorování katalyzátoru NOx/SCR",
    "IPT_0B_7": "Počet podmínek dokončení monitorování adsorbéru NOx",
    "IPT_0B_8": "Zjištěné počty podmínek monitorování adsorbéru NOx",
    "IPT_0B_9": "Počet podmínek dokončení monitorování filtru PM",
    "IPT_0B_10": "Zjištěné počty podmínek monitorování filtru PM",
    "IPT_0B_11": "Počet stavu dokončení monitorování snímače výfukových plynů",
    "IPT_0B_12": "Zjištěné počty podmínek monitorování snímače výfukových plynů",
    "IPT_0B_13": "Počet podmínek dokončení monitorování EGR a/nebo VVT",
    "IPT_0B_14": "Zjištěné počty podmínek monitorování EGR a/nebo VVT",
    "IPT_0B_15": "Počet podmínek dokončení monitorování plnicího tlaku",
    "IPT_0B_16": "Zjištěné počty podmínek monitorování plnicího tlaku",
    "IPT_0B_17": "Počet podmínek dokončení monitorování paliva",
    "IPT_0B_18": "Zjištěné počty podmínek monitorování paliva",

    "IPT_0B_des_1": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování OBD (obecný jmenovatel).",
    "IPT_0B_des_2": "zobrazuje počet, kolikrát byl motor nastartován.",
    "IPT_0B_des_3": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy systému katalyzátoru NMHC (čitatel).",
    "IPT_0B_des_4": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování katalyzátoru NMHC (jmenovatel).",
    "IPT_0B_des_5": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy systému katalyzátoru NOx (čitatel).",
    "IPT_0B_des_6": "zobrazuje, kolikrát bylo vozidlo provozováno za specifikovaných podmínek monitorování katalyzátoru NOx (jmenovatel).",
    "IPT_0B_des_7": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy systému adsorbéru NOx (čitatel).",
    "IPT_0B_des_8": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaném jmenovateli podmínek monitorování adsorbéru NOx).",
    "IPT_0B_des_9": "zobrazuje, kolikrát byly zjištěny všechny podmínky nutné k detekci poruchy systému filtru PM (čitatel).",
    "IPT_0B_des_10": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaném jmenovateli podmínek monitorování filtru PM).",
    "IPT_0B_des_11": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy snímače výfukových plynů (čitatel)",
    "IPT_0B_des_12": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování snímače výfukových plynů (jmenovatel).",
    "IPT_0B_des_13": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy systému EGR/VVT (čitatel).",
    "IPT_0B_des_14": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování systému EGR/VVT (jmenovatel).",
    "IPT_0B_des_15": "zobrazuje, kolikrát byly zjištěny všechny podmínky nutné k detekci poruchy systému plnicího tlaku (čitatel).",
    "IPT_0B_des_16": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování systému plnicího tlaku (jmenovatel).",
    "IPT_0B_des_17": "zobrazuje, kolikrát byly splněny všechny podmínky nezbytné k detekci poruchy palivového systému (čitatel).",
    "IPT_0B_des_18": "zobrazuje, kolikrát bylo vozidlo provozováno ve specifikovaných podmínkách monitorování palivového systému (jmenovatel)."
  }
}