// 芬兰语
var i18n = {
	"mt": "Päivä",
	"xs": "Tunnit",
	"fz": "Minuutit",
	"wxts": "Vinkkejä",
	"zzjz": "ladataan...",
	"noData": "EI DATA",
	"jchj" :"Tarkistaa kirjautumisympäristöä",
	"ckfw": "Viitealue",
	"bbgl": {
		"bbts": "Version päivityksen muistutus",
		"official": "Uusia ominaisuuksia on julkaistu. Siirry viralliselle verkkosivustolle ladataksesi ja päivittääksesi uusin versio.",
		"apple": "Uusia ominaisuuksia on julkaistu, siirry App Storeen ladataksesi päivitetty versio.",
		"google": "Uusia ominaisuuksia on julkaistu. Lataa päivitetty versio Google Playsta."
	},
	"uds": {
	"uds0001": "Valitse moduuli",
	"uds0002": "Valitse luettava moduuli",
	"uds0003": "Lista sisältää kaikki valitun merkin tuetut moduulit, on suositeltavaa valita vain autossa jo olevat moduulit. Kaikki moduulit voidaan kuitenkin valita. Järjestelmä tunnistaa automaattisesti autossa todellisuudessa olevat yksiköt .",
	"uds0004": "Valitse kaikki",
	"uds0005": "Peruuta valitse kaikki",
	"uds0006": "Aloita diagnoosi",
	"uds0007": "Muokattu toimittaja"
	},
	"yjdl": {
		"yxdl": "Sähköpostikirjautuminen",
		"dlts": "Syötä ensin grafiikka Captcha ja hanki sitten sähköposti Captcha",
		"sryx": "Anna sähköpostiosoitteesi",
		"sryzm": "Syötä Captcha",
		"xyb": "Seuraava",
		"xgyx": "Muokkaa postilaatikkoa",
		"yxdz": "Sähköpostiosoite",
		"fsyzm": "lähetä pääsykoodi sähköpostiin",
		"yzm": "Pääsykoodi",
		"cxfs": "sekuntia uudelleenlähetykseen",
		"dl": "Kirjaudu sisään",
		"srtxyzm": "Anna vasen grafiikka Captcha",
		"yxbzq": "Sähköposti on väärä",
		"txyzmbzq": "Graafinen Captcha on virheellinen",
		"fsdx": "Lähetä Captcha",
		"yxyzmfscg": "Sähköpostin Captcha lähetys onnistui",
		"yxbky": "Sähköpostin lähettäminen on epänormaalia! Tarkista, onko sähköpostiosoite syötetty oikein ja voidaanko sähköposti vastaanottaa normaalisti.",
		"zzyz": "Vahvistetaan",
		"yzmcw": "Sähköpostin Captcha on virheellinen",
		"clxxgl": "Ajoneuvon tietojen hallinta",
		"gxxx": "Päivitä tiedot",
		"dlcg": "Kirjautuminen onnistui",
		"dlsb": "Kirjautuminen epäonnistui",
		"clxx": "Ajoneuvon tiedot",
		"czxx": "Auton omistajan tiedot",
		"wdl": "Ei kirjautunut sisään",
		"cl": "Ajoneuvo"
	},
	
	"OBDxncs": {
		"bt": "Sovittimien vertailu",
		"fbt": "iso tarkoittaa nopeampaa",
		"zjsd": "Optimaalinen nopeus",
		"dqsd": "Nykyinen nopeus",
		"xzmc": "Nopeus, jolla parametrit luetaan ECU:sta sekunnissa (yksikkö: parametrit/sekunti)",
		"sec_dt": "Testattu Galaxy Note 8:lla ja Pixel 2:lla",
		"sec_dd1": "(1) Wi-Fi-sovittimia ei yleensä suositella Androidille, koska useimmat puhelimet menettävät datayhteyden Internetiin käytön aikana.",
		"sec_dd2": "(2) Kaikki testatut sovittimet ovat Bluetooth-standardeja, elleivät 'WiFi', 'USB' tai 'BLE' ole osa niiden nimeä",
		"text2": "OBD:n vertailu"
	},
	
	"tsxx": {
		"qxz": "valitse",
		"qsr": "Syötä",
		"qqr": "Vahvista",
		"qqx": "Peruuta",
		"notConnected": "Yhdistä ensin laitteesi",
		"save": "Lomakkeen tallennus onnistui.",
		"dsyh": "Tyhjäkäynnillä polttoaineenkulutuksella tarkoitetaan polttoaineen kulutusta senhetkisellä hetkellä, kun ajoneuvo on paikallaan, tilastoyksikkönä aika.",
		"xsyh": "Ajon polttoaineenkulutuksella tarkoitetaan polttoaineen kulutusta sillä hetkellä, kun ajoneuvo on ajotilassa, ja ottaa tilastoyksiköksi matkan.",
		"pjyh": "Keskimääräinen polttoaineenkulutus viittaa polttoaineenkulutukseen ajoneuvoa 100 kilometriä kohden tämän ajoprosessin aikana, ja se näkyy vasta, kun on ajettu yli 1 km.",
		"cqyh": "Pitkäaikainen polttoaineenkulutus tarkoittaa polttoaineenkulutusta, jonka ajoneuvo kuluttaa 100 kilometriä APP:n käytön aikana.",
		"yhsupport": "Tämä auto ei tue polttoaineenkulutuksen näyttöä",
		"cg": "menestys",
		"noTrouble": "Onnittelut, autosi on virheetön, jatka samaan malliin.",
		"noVin": "Syötä 17-numeroinen kehysnumero, jotta voimme tarjota sinulle parempaa palvelua.",
		"gzzsd": "MIL on lyhenne sanoista toimintahäiriön merkkivalo. Kun MIL-valo palaa, se tarkoittaa, että moottorijärjestelmässä voi olla toimintahäiriö. Syynä MIL-valon syttymiseen voi olla liian paljon hiilikerrostumaa laitteen sisällä. kaasuventtiili tai moottori tai sekoitussuhde on epätasapainossa happianturin vioittumisen jälkeen tai moottorin merkkivalo palaa bensan huonon polttoainelaadun ja ajoneuvon riittämättömän palamisen vuoksi.",
		"noDevelopment": "Kehityksessä, pysy kuulolla. ",
		"zc": "Tällä hetkellä testattavissa",
		"noSupport": "Ei tällä hetkellä testattavissa",
		"noNetwork": "Verkkosi ei ole tällä hetkellä käytettävissä. Mikään verkko ei vaikuta käyttökokemukseesi.",
		"jy": "Ei käytössä",
		"ywc": "Tilatesti suoritettu",
		"noCompelte": "Tilatestiä ei suoritettu",
		"noSupportPid": "Ajoneuvollasi ei ole tätä testiä!",
		"useReminders": "Muistutus: Keskeytyksen jälkeen voit zoomata tai vaeltaa pyyhkäisemällä sormea liukusäätimellä tai kosketusnäytöllä.",
		"noCompelteDes": "Jos valmiustila voidaan testata, mutta sitä ei ole suoritettu loppuun, voidaan tehdä seuraavat toimenpiteet kohteelta: ajaa täysillä, huoltaa ajoneuvoa, puhdistaa kokoonpano, päivittää ECU jne. Ajoprosessin toivotaan käytetään jatkossa eritelmien mukaisesti ja säännöllisiä huoltoja tehdään.",
		"fgf": "Tämä toiminto on vain virallisille tuotteille, käytä sitä ostamisen jälkeen!",
		"b25": "Tämä toiminto on vain B25:lle, käytä sitä ostamisen jälkeen!"
	},
	
	"pid": {
		"dsyh": "Tyhjäkäynnin polttoaineenkulutus",
		"xsyh": "polttoaineen kulutus",
		"ssyh": "Keskimääräinen kulutus",
		"pjyh": "Intant Consumption",
		"cqyh": "Pitkäaikainen polttoaineenkulutus",
		"pjsd": "Keskinopeus",
		"xslc": "Ajomatka",
		"DTC_legnth":"Tähän ECU:hun tallennettujen vikakoodien lukumäärä",
		"MIL": "Vian merkkivalon tila",
		"mil_0": "valo pois päältä",
		"mil_1": "valo päällä",
		"shxt": "Sytytysvikojen valvonta",
		"ryxt": "Polttoainejärjestelmän valvonta",
		"zhzj": "Kattava komponenttien valvonta",
		
		"fdjlx": "Moottorityyppi",
		"ysfdj": "puristussytytys",
		"dhfdj": "kipinäsytytys",
		"chj": "Katalyytin valvonta",
		"jrchj": "Lämmitetyn katalyytin valvonta",
		"zfxt": "Haihtuvan järjestelmän valvonta",
		"eckqxt": "Toissijaisen ilmajärjestelmän valvonta",
		"ktxtzlj": "A/C-järjestelmän kylmäaineen valvonta",
		"ycgqjrq": "Happianturin lämmittimen valvonta",
		"ycgqjk": "Happianturin valvonta",
		"erg": "EGR/VVT-järjestelmän valvonta",
		"NMHC": "NMHC-katalysaattorin valvonta",
		"NOx": "NOx/SCR-valvonta",
		"yl": "Varattu",
		"zyyl": "Boost Pressure Monitoring",
		"fqcgq": "Pakokaasuanturin valvonta",
		"pmglq": "PM-suodatin Monitorin valvonta"
	},

	"sygl": {
		"xieyi": "Protokolla",
		"tips1": "Yhdistä laite",
		"tips2": "Ota Bluetooth käyttöön! Näytä ohje",
		"tips3": "Etkö löydä laitetta? Näytä ohje",
		"tips4": "Ota sijaintipalvelut käyttöön",
		"tips5": "Universaali",
		"tips6": " Kustannustehokas versio",
		"sdlj": "Valitse yhteys manuaalisesti"
	},
	
	"djz": {
		"noData": "Tällä hetkellä ei ole pysäytyskehysdataa",
		"previousFrame": "Edellinen kehys",
		"nextFrame": "Seuraava kehys"
	},
	
	"fwgl": {
		"ybp": "Kojelauta",
		"UDS": "Unified Diagnostic Service (Test)",
		"UDS_des": "Tarjoa ajoneuvon yhtenäinen diagnoosipalvelu, enemmän ECU:ta ja enemmän toimintoja",
		"DTC": "DTC-valvonta",
		"DTC_des": "Tarjoa ammattimaisia ratkaisuja ajoneuvon vikakoodeihin",
		"xcfx": "Matkan analyysi",
		"xcfx_des": "Analysoi jokaisen matkasi tiedot",
		"xncs": "Ajoneuvon suorituskyvyn testaus",
		"xncs_des": "Anna ammattimainen ajoneuvon suorituskykyanalyysiraportti",
		"sssjl": "reaaliaikainen tietovirta",
		"sssjl_des": "Pyydä voimansiirron nykyiset diagnostiikkatiedot",
		"gzzsd": "Vikailmaisimen tunnistus",
		"gzzsd_des": "Tarjoaa ajoneuvon toimintatiedot sen jälkeen, kun vikavalo on päällä tai sammutettu",
		
		"pid0141": "Diagnostiikka valmiustila",
		"pid0141_des": "Tarjoaa ajoneuvon valvontatilan DTC:n tyhjentämisen jälkeen ja nykyisen ajosyklin valvontatilan",
		"$05": "Happianturin valvontatulokset",
		"$05_des": "Lue ajoneuvon happianturin valvonnan testitulokset",
		"$06": "Tietyt seurantatulokset",
		"$06_des": "saa pääsy tiettyjen komponenttien/järjestelmien On-Board Diagnostic -valvontatestien tuloksiin.",
		"$09": "Ajoneuvon tiedot",
		"$09_des": "Lue ajoneuvokohtaisia ajoneuvotietoja",
		
		"clnj": "",
		"clnj_des": "",
		
		"obdTest": "OBD-suorituskykytesti",
		"obdTest_des": "Testaa erilaisia OBD:n suorituskykyindikaattoreita automaattisten testaustyökalujen avulla.",
		"djz": "Freeze Frame",
		"djz_des": "Kun DTC ilmestyy pakojärjestelmään, ECU tallentaa tiedot, kun vikakoodi ilmestyy",
		"yjjc": "Täysi ajoneuvon tunnistus yhdellä napsautuksella",
		"yjjc_des": "Kaikkien ajoneuvon anturitietojen, ajoneuvotietojen, vikakoodien, pysäytyskehysten ja ajoneuvon valvontatietojen kattava tunnistus."
	},
	
	"yjjc": {
		"cljkxx": "ajoneuvon valvontatiedot",
		"xx_09": "Havaitsee ajoneuvon tietoja",
		"xx_03": "Vikatietojen havaitseminen",
		"xx_01": "Havaitsee ajoneuvon valvontatietoja",
		"xx_02": "Havaitsee pysäytyskuvan tietoja",
		"xx_05": "Happianturin tietoja tunnistetaan",
		"xx_06": "Tietyiden tarkkailutulostietojen lukeminen"
	},
	
	"ybpgl":{
		"dcdy": "Akun jännite",
		"xhyb": "Cruise Meter",
		"yhyb": "polttoaineenkulutusmittari",
		"zdyyb": "Mukautettu mittari",
		"xz": "Lisää hallintapaneeli",
		"bj": "Muokkaa hallintapaneelia",
		"sc": "Poista hallintapaneeli",
		"delete_tips": "Oletko varma, että poistat kojelaudan?"
	},
	
		
	"status": {
		"1000": "Bluetooth ei ole päällä",
		"1001": "Bluetooth on pois päältä",
		"1002": "Odotetaan polttoaineen säästöä",
		"1003": "OBD:tä etsitään",
		"1004": "Yhdistetään OBD",
		"1005": "Bluetooth on yhdistetty",
		"1006": "tietojen kirjoittaminen onnistui",
		"1007": "Tietojen kirjoittaminen epäonnistui",
		"1008": "Ota ilmoitus käyttöön onnistuneesti",
		"1009": "Laitteita ei löydy"
	},

  
	"szgl": {
		"bt": "Asetus",
		"label1": "Kieli",
		"value1": "Seuraa järjestelmää",
		"label2": "Tietosuojakäytäntö",
		"label3": "Yhteyden ohjeet",
		"label4": "Tietoja",
		"label5": "Virallinen ostoskeskus",
		"value5": "1688 Mall",
		"label6": "Versio",
		"cjwt": "Yleinen ongelma",
		"unittitle": "Yksikkö",
		"unitvalue1": "Metrijärjestelmä",
		"unitvalue2": "Imperial Units",
		"unitinfo": "Vahvista, vaihdetaanko yksikköä?"
	},

	"yygl": {
		"label": "Seuraa järjestelmää",
		"des": "Kun se on kytketty päälle, se asetetaan automaattisesti järjestelmän kielen mukaan",
		"en": "englanti",
		"zh": "yksinkertaistettu kiina",
		"zwft": "perinteinen kiina",
		"es": "espanja",
		"kr": "korea",
		"ru": "venäläinen",
		"ja": "japani",
		"it": "italialainen",
		"hi": "hindi",
		"pt": "portugali",
		"de": "saksa",
		"fr": "ranskalainen",
		"nl": "hollanti",
		"fi": "suomi",
		"pl": "puolalainen",
		"bn": "bengali",
		"hu": "Unkari",
		"cs": "tsekki",
		"th": "thai",
		"tr": "turkki",
		"ms": "malaiji",
		"ro": "romania",
		"sv": "ruotsalainen",
		"da": "tanska"
	},

	
	"obdManage": {
		"bt": "OBD-hallinta",
		"search_tip": "Hae uudelleen tai osta tuotteitamme",
		"buy_tip": "Mene ostoskeskukseen ostamaan",
		"searchAgain": "Hae uudelleen",
		"nearBy": "Lähellä olevat laitteet",
		"ls": "Historialliset laitteet",
		"bz": "Näytä ohje",
		"del": "Poista",
		"delConfirm": "Oletko varma, että poistat tämän tietueen?",
		"switched": "Laite vaihdetaan, oletko varma?",
		"qrxx": "Varmista, että matkapuhelimen Bluetooth- ja sijaintitietojen kytkin on päällä.",
		"searchAgain_message": "Haetko varmasti uudelleen lähellä olevia laitteita?"
	},

	
"gzjc": {
		"bt": "Diagnostiikka",
		"btn": "Aloita testaus",
		"des": "Aloita ajoneuvosi täydellinen skannaus",
		"FaultCodeQuery": "Vikakoodikysely",
		"zzjc": "Testaus",
		"clearFaultCode": "Tyhjennä vikakoodi",
		"kscz": "haku",
		"fxgz": "Vikakoodi löydetty",
		"notFound": "ongelmia ei löytynyt",
		"cxjc": "Tarkista uudelleen",
		"modalTitle": "Haluatko varmasti poistaa vikakoodin?",
		"modalContent": "Ennen kuin vika on ratkaistu, on suositeltavaa olla tyhjentämättä vikakoodia mielellään. Useimmat ECU:t eivät salli vikakoodin poistamista moottorin käydessä. Se, voidaanko vikakoodi tyhjentää vai ei, on viime kädessä ECU määrittää. Vikakoodien poistaminen ei todellakaan ole ratkaisu ongelmaan.",
		"sdjc": "Syvätarkastusraportti",
		"num": "Vikakoodien lukumäärä",
		"gzmxx": "Vikakoodin tiedot",
		"label1": "luokka",
		"label2": "Vikakoodin selitys",
		"definition_03": "Diagnostiset vikakoodit",
		"definition_07": "Odottaa diagnostisia vikakoodeja",
		"definition_0A": "Pysyvät diagnostiset vikakoodit",
		"03_des": "Kun ECU (Vehicle Control Unit) havaitsee poikkeavuuden, vikakoodi tallennetaan muistiin. Tämä vikakoodi viittaa epänormaaliin tilanteeseen, joka löydettiin viime ajon aikana. Nämä vikakoodit säilyvät muistissa ajan, kun vikakoodi löytyy uudelleen, päivitä säilytysaika.",
		"07_des": "Tämä on kuittaamaton poikkeama ajon aikana. Jos poikkeama toistuu ja tunnistetaan, väliaikainen vikakoodi luokitellaan vahvistetuksi vikakoodiksi. Jos sitä ei tallenneta, se poistetaan, kun moottori sammutetaan." ,
		"0A_des": "Koska se näyttää aiempien vikakoodien historian, se ei edusta ajoneuvon nykyistä tilaa. Vastaavia DTC:itä ei ehkä ole mahdollista poistaa ohjelmallisesti.",
		"sys_P": "Voimansiirtojärjestelmä (valmistajan määrittelemä)",
		"sys_B": "Runkojärjestelmä (valmistajan määrittelemä)",
		"sys_C": "Alusta jousitusjärjestelmä (valmistajan määrittelemä)",
		"sys_U": "Verkon viestintäjärjestelmä (valmistajan määrittelemä)",
		"zzs": "Kaikki autonvalmistajat"
	},

	"clgl": {
		"bt": "Oma auto",
		"info1": "Perustiedot autosta",
		"clpp": "Automerkit",
		"xh": "Automalli",
		"nk": "Vuosi",
		"rylx": "Polttoainetyyppi",
		"info2": "Muut ajoneuvotiedot",
		"atdp": "Kommunikaatioprotokolla",
		"ati": "Sovitinversio",
		"vin": "Ajoneuvon tunnistusnumero",
		"cid": "Kalibrointitunnisteet",
		"cvn": "Kalibroinnin vahvistusnumerot",
		"ecu": "Elektroninen ohjausyksikkö",
		"ESN": "Moottorin sarjanumero",
		"EROTAN": "Pakokaasusäännön tai tyyppihyväksyntänumero",
		"FEOCNTR": "Polttoainekäyttöisen moottorin sytytyssyklilaskuri",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Täytä ajoneuvon merkki",
		"warn2": "automalli vaaditaan",
		"warn3": "auton vuosi vaaditaan",
		"warn4": "vin is required",
		"warn5": "Täytä oikea ajoneuvon tunnusnumero",
		"warn6": "auton omistajan nimi vaaditaan",
		"warn7": "puhelinta tarvitaan",
		"warn8": "Anna oikea puhelin",
		"warn9": "Anna oikea sähköpostiosoite",
		"bt": "OBD-yhteys onnistui",
		"title_sub": "Seuraavat tiedot ovat erittäin tärkeitä tarkan diagnoosin kannalta ja parantavat kokemustasi. Muista täyttää huolellisesti.",
		"ts_vin": "VIN-koodin sijainti: sijaitsee yleensä kojelaudan vasemmalla puolella, etutuulilasin vasemmassa alakulmassa; siellä on myös oven saranapylväs, oven lukkopilari tai jokin pylväästä, joka on kytketty oven lukkopilari tai kuljettajan istuimen lähellä oleva ovi sisällä.",
		"vin": "Vin",
		"czxm": "Nimi",
		"lxdh": "Puhelin",
		"lxyx": "Sähköposti"
	},
	"ota": {
		"bt": "OTA-päivitys",
		"jcdxbb": "Uusi laiteohjelmistoversio havaittu",
		"gxnr": "Päivitä sisältö",
		"fxsm": "Päivitysohjeet",
		"fxsm_des": "OTA (over-the-air-tekniikka) -päivitys tarkoittaa, että mobiilipääte lataa päivityspaketin palvelimelle etäältä päivittääkseen OBD-laiteohjelmiston. Päivitys ei vaikuta ajoneuvoosi ja ajoturvallisuuteen, voit käyttää sitä vapaasti Jos se pyytää, että päivitys on epäonnistunut, älä poistu käyttöliittymästä, aseta OBD uudelleen ja jatka päivitystä.",
		"zysx": "Varoitus",
		"zysx_des": "Älä päivitä ajon aikana, äläkä irrota tai sammuta OBD:tä päivityksen aikana.",
		"mssj": "Päivitä nyt",
		"kssj": "Aloita päivitys",
		"sjcg": "OTA-päivitys onnistui",
		"kqqxty": "Avaa uusi kokemus",
		"xzgj": "Lataa laiteohjelmisto",
		"zzxr": "Kirjoittaminen",
		"zzsj": "Päivitetään",
		"zzjy": "Eheyden tarkistaminen",
		"sjsb": "Päivitys epäonnistui, yritä uudelleen"
	},

	"xcfx": {
		"ksxc": "Aloita matka",
		"jsxc": "Lopeta matka",
		"lsjl": "Historiatietue",
		"zlc": "Kokonaiskilometrimäärä",
		"hs": "Aikaa vievää",
		"kssj": "Aloitusaika",
		"zyh": "Litraa yhteensä"
	},

	"xncs": {
		"jsxn": "Nopeutettu",
		"scxn": "Jarruttaminen",
		"jlxn": "Etäisyys",
		"des1": "Nopeustestialue",
		"des2": "nopeus jarrutettaessa",
		"des3": "testietäisyys",
		"aqtx": "Kiinnitä huomiota ajoturvallisuuteen!",
		"kscs": "Aloita testaus",
		"cxcs": "Testaa uudelleen",
		"tz": "Lopeta",
		"tip1": "Säädä ajoneuvon nopeus",
		"tip2": "Kiihdytä painamalla kaasupoljinta",
		"tip2_end": "Yläpuolella",
		"tip3": "Alenna nopeutta painamalla jarruja",
		"tip4": "Aja",
		"tip5": "Matkannut",
		"max_sd": "Huippunopeus",
		"max_jsd": "Maksimikiihtyvyys",
		"max_zs": "Maksiminopeus",
		"tx1": "Aloitusnopeus ei voi olla suurempi kuin loppunopeus",
		"tx2": "Täytä jarrutusnopeus, joka on suurempi kuin 0",
		"tx3": "Täytä testietäisyys, joka on suurempi kuin 0"
	},

	"bzxx": {
		"title1": "Vaihe 1: Käynnistä ajoneuvo",
		"title2": "Vaihe 2: Kytke laite",
		"title3": "Vaihe 3: Ota Bluetooth ja Location käyttöön",
		"title4": "Vaihe 4: Avaa APP",
		"title5": "Vaihe 5: Liitä laite",
		"text1": "Etsi ajoneuvon OBD-liitännän sijainti. OBD-liitäntä on 16-nastainen naarasliitäntä. Liitäntä on puolisuunnikkaan muotoinen. Joissakin malleissa on OBD-liitännän kansi. Yleiset OBD-portit ovat mustia, valkoisia tai sinisiä. Sijainti on yleensä sisäverhoilupaneelissa ohjauspyörän alla, lähellä kuljettajan polvia. OBD-liitännän sijainti voi olla erilainen eri malleissa ja malleissa. Seuraavassa kuvassa on esitetty OBD-liitännän mahdollinen sijainti:",
		"text2": "Kun olet löytänyt OBD-liitännän, liitä laite OBD-liitäntään. Varmista, että se on kytketty kokonaan (monet autot on kytketty noin puolivälissä ja virta on päällä, mutta signaalinastat eivät ehkä ole kytketty) ja punainen virran merkkivalo tai näyttö palaa.",
		"text3": "Ota käyttöön puhelimesi Bluetooth- ja sijaintikytkimet. Menetelmä: Pyyhkäise alas puhelimen näytön yläreunasta, avaa pikavalikko ja napsauta Bluetooth ja sijaintitiedot. Ota Bluetooth käyttöön iOS-laitteessasi.",
		"text4": "Avaa sovellus ja salli sovelluksen käyttää sijaintitietoja.",
		"text5": "Kun olet suorittanut yllä olevat vaiheet, syötä APP, APP skannaa automaattisesti OBD-laitteen ja kysyy, liitetäänkö laite. iOS-laite kysyy, sallitaanko osoitteen käyttö, napsauta Salli.",
		"text6": "Valitse yhdistettävä laite ja yhdistä napsauttamalla. Kun yhteys on muodostettu, APP:n kotisivulla näkyy OBD-laitteen nimi, Bluetooth-osoite ja lukema tulee näkyviin kojelautaan."
	},
	
	"06fw": {
		"MID": "Monitorin nimi",
		"TID": "testin nimi",
		"CID": "Komponenttinumero",
		"O2Sensor": "O2-anturin nimi",
		"MIN": "Minimiraja",
		"MAX": "Maksimiraja",
		"CURRENT": "Test Value"
	},
	
	"09fw": {
		"ipt": "Käytössä olevan suorituskyvyn seuranta",
		"IPT_08_1": "OBD-valvontaolosuhteiden havaitut määrät",
		"IPT_08_2": "Sytytysjaksolaskuri",
		"IPT_08_3": "Catalyst Monitor Completion Counts Bank 1",
		"IPT_08_4": "Catalyst Monitor Conditions Encountered Counts Bank 1",
		"IPT_08_5": "Catalyst Monitor Completion Counts Bank 2",
		"IPT_08_6": "Catalyst Monitor Conditions Encountered Counts Bank 2",
		"IPT_08_7": "O2-anturin monitorin valmistumismäärät pankki 1",
		"IPT_08_8": "O2-anturin monitorin olosuhteet havaitut laskee pankki 1",
		"IPT_08_9": "O2-anturin monitorin valmistumismäärät pankki 2",
		"IPT_08_10": "O2-anturin valvontaolosuhteet havaitsevat, laskee pankki 2",
		"IPT_08_11": "EGR- ja/tai VVT-monitorin valmistumismäärät",
		"IPT_08_12": "EGR- ja/tai VVT-monitoriolosuhteiden havaitut määrät",
		"IPT_08_13": "AIR Monitor Completion Condition -counts (Toissijainen ilma)",
		"IPT_08_14": "AIR Monitor Conditions Encounted Counts (Secondary Air)",
		"IPT_08_15": "EVAP-monitorin valmistumisehtojen määrä",
		"IPT_08_16": "EVAP-monitorin olosuhteiden havaitut määrät",
		"IPT_08_17": "Toissijaisen O2-anturin monitorin valmistumismäärät, pankki 1",
		"IPT_08_18": "Toissijaisen O2-anturin valvontatilan kohdat laskee pankki 1",
		"IPT_08_19": "Toissijaisen O2-anturin monitorin valmistumismäärät pankki 2",
		"IPT_08_20": "Toissijaisen O2-anturin monitorin olosuhteet laskevat pankki 2",
		
		"IPT_08_des_1": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä OBD-valvontaolosuhteissa (yleinen nimittäjä).",
		"IPT_08_des_2": "näyttää kuinka monta kertaa moottori on käynnistetty.",
		"IPT_08_des_3": "näyttää, kuinka monta kertaa kaikki olosuhteet, jotka ovat tarpeen katalyyttijärjestelmän pankin 1 virhetoiminnan havaitsemiseksi, on kohdattu (osoittaja).",
		"IPT_08_des_4": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä katalyytin valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_5": "näyttää, kuinka monta kertaa kaikki olosuhteet, jotka ovat tarpeen katalyyttijärjestelmän pankin 2 virhetoiminnan havaitsemiseksi, on kohdattu (osoittaja).",
		"IPT_08_des_6": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä katalyytin valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_7": "näyttää, kuinka monta kertaa kaikki olosuhteet, jotka ovat tarpeen happianturin pankin 1 virhetoiminnan havaitsemiseksi, on kohdattu (osoittaja).",
		"IPT_08_des_8": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä happianturin valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_9": "näyttää, kuinka monta kertaa kaikki olosuhteet, jotka ovat tarpeen happianturin pankin 2 virhetoiminnan havaitsemiseksi, on kohdattu (osoittaja).",
		"IPT_08_des_10": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä happianturin valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_11": "näyttää kuinka monta kertaa kaikki EGR/VVT-järjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_08_des_12": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä EGR/VVT-järjestelmän valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_13": "näyttää kuinka monta kertaa kaikki AIR-järjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_08_des_14": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä AIR-järjestelmän valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_15": "näyttää kuinka monta kertaa kaikki olosuhteet, jotka tarvitaan 0,020” (tai 0,040”) EVAP-järjestelmän vuodon havaitsemiseen, on havaittu (osoittaja).",
		"IPT_08_des_16": "näyttää, kuinka monta kertaa ajoneuvoa on käytetty määritellyissä EVAP-järjestelmän vuotojen toimintahäiriöiden valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_17": "näyttää, kuinka monta kertaa kaikki olosuhteet, jotka ovat tarpeen toissijaisen happianturin pankin 1 virhetoiminnan havaitsemiseksi, on kohdattu (osoittaja).",
		"IPT_08_des_18": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä toissijaisissa happianturin valvontaolosuhteissa (nimittäjä).",
		"IPT_08_des_19": "näyttää kuinka monta kertaa kaikki olosuhteet, jotka ovat tarpeen toissijaisen happianturiryhmän 2 toimintahäiriöiden havaitsemiseksi, on kohdattu (osoittaja).",
		"IPT_08_des_20": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä toissijaisen happianturin valvontaolosuhteissa (nimittäjä).",
		
		"IPT_0B_1": "OBD-valvontaolosuhteiden havaitut määrät",
		"IPT_0B_2": "Sytytysjaksolaskuri",
		"IPT_0B_3": "NMHC Catalyst Monitor Completion Condition -määrät",
		"IPT_0B_4": "NMHC Catalyst Monitor Conditions Encounted Counts",
		"IPT_0B_5": "NOx/SCR Catalyst Monitor Completion Condition Counts",
		"IPT_0B_6": "NOx/SCR-katalysaattorin valvontaolosuhteiden havaitut määrät",
		"IPT_0B_7": "NOx-adsorber-monitorin valmistumismäärät",
		"IPT_0B_8": "NOx Adsorber Monitor Conditions Encounted Counts",
		"IPT_0B_9": "PM Filter Monitor Completion Condition -counts",
		"IPT_0B_10": "PM Filter Monitor Conditions Encounted Counts",
		"IPT_0B_11": "Pakokaasuanturin valvonnan valmistumismäärät",
		"IPT_0B_12": "Pakokaasuanturin valvontaolosuhteiden havaitut määrät",
		"IPT_0B_13": "EGR- ja/tai VVT-monitorin valmistumismäärät",
		"IPT_0B_14": "EGR- ja/tai VVT-monitoriolosuhteiden havaitut määrät",
		"IPT_0B_15": "Boost Pressure Monitorin valmistumismäärät",
		"IPT_0B_16": "Boost Pressure Monitor Conditions Conditions Encounted Counts",
		"IPT_0B_17": "Polttoainevalvonnan valmistumismäärät",
		"IPT_0B_18": "Fuel Monitor Conditions Encounted Counts",
		
		"IPT_0B_des_1": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä OBD-valvontaolosuhteissa (yleinen nimittäjä).",
		"IPT_0B_des_2": "näyttää kuinka monta kertaa moottori on käynnistetty.",
		"IPT_0B_des_3": "näyttää, kuinka monta kertaa kaikki NMHC-katalysaattorijärjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_4": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä NMHC-katalysaattorin valvontaolosuhteissa (nimittäjä).",
		"IPT_0B_des_5": "näyttää, kuinka monta kertaa kaikki NOx-katalysaattorijärjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_6": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä NOx-katalysaattorin valvontaolosuhteissa (nimittäjä).",
		"IPT_0B_des_7": "näyttää, kuinka monta kertaa kaikki NOx-adsorberijärjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_8": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyssä NOx-adsorberin valvontaolosuhteiden nimittäjässä).",
		"IPT_0B_des_9": "näyttää kuinka monta kertaa kaikki PM-suodatinjärjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_10": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyssä PM-suodattimen valvontaolosuhteiden nimittäjässä).",
		"IPT_0B_des_11": "näyttää kuinka monta kertaa kaikki pakokaasuanturin toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja)",
		"IPT_0B_des_12": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritellyissä pakokaasuanturin valvontaolosuhteissa (nimittäjä).",
		"IPT_0B_des_13": "näyttää, kuinka monta kertaa kaikki EGR/VVT-järjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_14": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä EGR/VVT-järjestelmän valvontaolosuhteissa (nimittäjä).",
		"IPT_0B_des_15": "näyttää, kuinka monta kertaa kaikki ahtopainejärjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_16": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä ahtopainejärjestelmän valvontaolosuhteissa (nimittäjä).",
		"IPT_0B_des_17": "näyttää, kuinka monta kertaa kaikki polttoainejärjestelmän toimintahäiriön havaitsemiseen tarvittavat olosuhteet on kohdattu (osoittaja).",
		"IPT_0B_des_18": "näyttää kuinka monta kertaa ajoneuvoa on käytetty määritetyissä polttoainejärjestelmän valvontaolosuhteissa (nimittäjä)."
	}
}