// 法语
var i18n = {
	"mt": "Jour",
	"xs": "Heures",
	"fz": "Minutes",
	"wxts": "Conseils",
	"zzjz": "chargement...",
	"noData": "AUCUNE DONNEE",
	"jchj" :"Vérification de l'environnement de connexion",
	"ckfw": "Plage de référence",
	"bbgl": {
		"bbts": "Rappel de mise à jour de version",
		"official": "De nouvelles fonctionnalités ont été publiées, veuillez vous rendre sur le site officiel pour télécharger et mettre à jour la dernière version.",
		"apple": "De nouvelles fonctionnalités ont été publiées, veuillez vous rendre sur l'App Store pour télécharger la version mise à jour.",
		"google": "De nouvelles fonctionnalités ont été publiées, veuillez vous rendre sur Google Play pour télécharger la version mise à jour."
	},
	"uds": {
	"uds0001": "Sélectionner un module",
	"uds0002": "Sélectionner le module à lire",
	"uds0003": "La liste contient tous les modules pris en charge de la marque sélectionnée, il est recommandé de sélectionner uniquement les modules déjà présents sur la voiture. Cependant, tous les modules peuvent être sélectionnés. Le système détectera automatiquement les unités réellement présentes sur la voiture .",
	"uds0004": "Tout sélectionner",
	"uds0005": "Annuler tout sélectionner",
	"uds0006": "Démarrer le diagnostic",
	"uds0007": "Fournisseur personnalisé"
	},
	"yjdl": {
		"yxdl": "Connexion par e-mail",
		"dlts": "Entrez d'abord le Captcha graphique, puis récupérez le Captcha par e-mail",
		"sryx": "Veuillez saisir votre email",
		"sryzm": "Veuillez saisir le Captcha",
		"xyb": "Suivant",
		"xgyx": "Modifier la boîte aux lettres",
		"yxdz": "Adresse e-mail",
		"fsyzm": "envoyer le code d'accès par e-mail",
		"yzm": "Code d'accès",
		"cxfs": "secondes pour renvoyer",
		"dl": "Connexion",
		"srtxyzm": "Entrez le Captcha graphique de gauche",
		"yxbzq": "L'e-mail est incorrect",
		"txyzmbzq": "Le Captcha graphique est incorrect",
		"fsdx": "Envoi de Captcha",
		"yxyzmfscg": "Email Captcha envoyé avec succès",
		"yxbky": "L'envoi d'e-mail est anormal ! Veuillez vérifier si l'adresse e-mail est correctement saisie et si l'e-mail peut être reçu normalement.",
		"zzyz": "Vérification",
		"yzmcw": "L'e-mail Captcha est incorrect",
		"clxxgl": "Gestion des informations du véhicule",
		"gxxx": "Mettre à jour les informations",
		"dlcg": "Connexion réussie",
		"dlsb": "La connexion a échoué",
		"clxx": "Informations sur le véhicule",
		"czxx": "Informations sur le propriétaire de la voiture",
		"wdl": "Non connecté",
		"cl": "Véhicule"
	},
	
	"OBDxncs": {
		"bt": "Comparaison des adaptateurs",
		"fbt": "plus grand signifie plus rapide",
		"zjsd": "Vitesse optimale",
		"dqsd": "Vitesse actuelle",
		"xzmc": "Le taux auquel les paramètres sont lus à partir de l'ECU par seconde (unité : paramètres/seconde)",
		"sec_dt": "Testé avec Galaxy Note 8 et Pixel 2",
		"sec_dd1": "(1) Les adaptateurs Wi-Fi ne sont généralement pas recommandés pour Android, car la plupart des téléphones perdent leur connexion de données à Internet pendant leur utilisation.",
		"sec_dd2": "(2) Tous les adaptateurs testés sont Bluetooth standard à moins que 'WiFi', 'USB' ou 'BLE' fasse partie de leur nom",
		"text2": "Comparaison des OBD"
	},
	
	"tsxx": {
		"qxz": "choisir",
		"qsr": "Veuillez entrer",
		"qqr": "Confirmer",
		"qqx": "Annuler",
		"notConnected": "Veuillez d'abord connecter votre appareil",
		"save": "Enregistrez le formulaire avec succès.",
		"dsyh": "La consommation de carburant au ralenti fait référence à la consommation de carburant au moment où le véhicule est à l'arrêt, avec le temps comme unité statistique.",
		"xsyh": "La consommation de carburant de conduite fait référence à la consommation de carburant au moment où le véhicule est en état de conduite, et prend la distance comme unité statistique.",
		"pjyh": "La consommation moyenne de carburant se réfère à la consommation de carburant pour 100 kilomètres du véhicule pendant ce processus de conduite, et elle n'est affichée qu'après avoir parcouru plus de 1 km.",
		"cqyh": "La consommation de carburant à long terme fait référence à la consommation de carburant consommée par le véhicule sur 100 kilomètres pendant le fonctionnement de l'APP.",
		"yhsupport": "Cette voiture ne prend pas en charge l'affichage de la consommation de carburant",
		"cg": "succès",
		"noTrouble": "Félicitations, votre voiture est sans défaut, continuez comme ça.",
		"noVin": "Veuillez saisir le numéro de cadre à 17 chiffres afin que nous puissions vous offrir un meilleur service.",
		"gzzsd": "Le MIL est l'abréviation de Malfunction Indicator Lamp. Lorsque le voyant MIL est allumé, cela signifie que le système du moteur peut mal fonctionner. La raison pour laquelle le voyant MIL est allumé peut être qu'il y a trop de dépôt de carbone à l'intérieur du papillon des gaz ou le moteur, ou le rapport de mélange est déséquilibré après la panne du capteur d'oxygène, ou le voyant du moteur est allumé en raison de la mauvaise qualité du carburant de l'essence et de la combustion insuffisante du véhicule.",
		"noDevelopment": "En cours de développement, restez à l'écoute. ",
		"zc": "Actuellement disponible pour test",
		"noSupport": "Actuellement non disponible pour les tests",
		"noNetwork": "Votre réseau est actuellement indisponible. Aucun réseau n'affectera votre expérience.",
		"jy": "Désactivé",
		"ywc": "Test d'état terminé",
		"noCompelte": "Test d'état non terminé",
		"noSupportPid": "Votre véhicule n'a pas ce test !",
		"useReminders": "Rappel : Après une pause, vous pouvez zoomer ou vous déplacer en faisant glisser votre doigt sur le curseur ou sur l'écran tactile.",
		"noCompelteDes": "Si l'état prêt peut être testé mais pas terminé, les mesures suivantes peuvent être prises élément par élément : conduire complètement, entretenir le véhicule, nettoyer l'ensemble, mettre à niveau l'ECU, etc. On espère que le processus de conduite seront exploités conformément aux spécifications à l'avenir, et un entretien régulier sera effectué.",
		"fgf": "Cette fonction est exclusive aux produits officiels, veuillez l'utiliser après l'achat !",
		"b25": "Cette fonction est exclusive à B25, veuillez l'utiliser après l'achat !"
	},
	
	"pid": {
		"dsyh": "Consommation de carburant au ralenti",
		"xsyh": "consommation de carburant",
		"ssyh": "Consommation moyenne",
		"pjyh": "Consommation instantanée",
		"cqyh": "Consommation de carburant à long terme",
		"pjsd": "Vitesse moyenne",
		"xslc": "Distance parcourue",
		"DTC_legnth": "# de DTC stockés dans cet ECU",
		"MIL": "État du voyant de dysfonctionnement",
		"mil_0": "lumière éteinte",
		"mil_1": "lumière allumée",
		"shxt": "Surveillance des ratés",
		"ryxt": "Surveillance du système de carburant",
		"zhzj": "Surveillance complète des composants",
		
		"fdjlx": "Type de moteur",
		"ysfdj": "allumage par compression",
		"dhfdj": "allumage par étincelle",
		"chj": "Surveillance du catalyseur",
		"jrchj": "Surveillance du catalyseur chauffé",
		"zfxt": "Surveillance du système d'évaporation",
		"eckqxt": "Surveillance du système d'air secondaire",
		"ktxtzlj": "Surveillance du réfrigérant du système de climatisation",
		"ycgqjrq": "Surveillance du chauffage du capteur d'oxygène",
		"ycgqjk": "Surveillance du capteur d'oxygène",
		"erg": "Surveillance du système EGR/VVT",
		"NMHC": "Surveillance du catalyseur NMHC",
		"NOx": "Surveillance NOx/SCR",
		"yl": "Réservé",
		"zyyl": "Surveillance de la pression de suralimentation",
		"fqcgq": "Surveillance du capteur de gaz d'échappement",
		"pmglq": "Surveillance du moniteur de filtre PM"
	},

	"sygl": {
		"xieyi": "Protocole",
		"tips1": "Connecter l'appareil",
		"tips2": "Veuillez activer le Bluetooth ! Afficher l'aide",
		"tips3": "Vous ne trouvez pas l'appareil ? Affichez l'aide",
		"tips4": "Veuillez activer les services de localisation",
		"tips5": " Universel",
		"tips6": " Version économique",
		"sdlj": "Sélectionner manuellement une connexion"
	},
	
	"djz": {
		"noData": "Il n'y a actuellement aucune donnée d'arrêt sur image",
		"previousFrame": "Cadre précédent",
		"nextFrame": "Image suivante"
	},
	
	"fwgl": {
		"ybp": "Tableau de bord",
		"UDS": "Service de diagnostic unifié (test)",
		"UDS_des": "Fournir un service de diagnostic unifié du véhicule, plus d'ECU et plus de fonctions",
		"DTC": "Surveillance DTC",
		"DTC_des": "Fournir des solutions professionnelles pour les codes d'erreur des véhicules",
		"xcfx": "Analyse du trajet",
		"xcfx_des": "Analysez toutes vos données de trajet",
		"xncs": "Test de performance du véhicule",
		"xncs_des": "Fournir un rapport d'analyse des performances du véhicule professionnel",
		"sssjl": "flux de données en temps réel",
		"sssjl_des": "Demander les données de diagnostic actuelles du groupe motopropulseur",
		"gzzsd": "Détection d'indicateur de défaut",
		"gzzsd_des": "Fournit des informations sur le fonctionnement du véhicule après l'allumage ou l'extinction du voyant de panne",
		
		"pid0141": "État de diagnostic prêt",
		"pid0141_des": "Fournit l'état de surveillance du véhicule depuis que le DTC a été effacé et l'état de fonctionnement actuel du moniteur de cycle de conduite",
		"$05": "Résultats de la surveillance du capteur d'oxygène",
		"$05_des": "Lire les résultats des tests de surveillance du capteur d'oxygène du véhicule",
		"$06": "Résultats de surveillance spécifiques",
		"$06_des": "autoriser l'accès aux résultats des tests de surveillance du diagnostic embarqué pour des composants/systèmes spécifiques.",
		"$09": "Informations sur le véhicule",
		"$09_des": "Lire les informations et informations spécifiques au véhicule",
		
		"clnj": "",
		"clnj_des": "",
		
		"obdTest": "Test de performances OBD",
		"obdTest_des": "Testez divers indicateurs de performance de l'OBD grâce à des outils de test automatisés.",
		"djz": "Image figée",
		"djz_des": "Lorsqu'un DTC apparaît dans le système d'échappement, l'ECU stocke les données lorsque le DTC apparaît",
		"yjjc": "Détection complète du véhicule en un clic",
		"yjjc_des": "Détection complète de toutes les données des capteurs du véhicule, des informations sur le véhicule, des codes de panne, des arrêts sur image et des informations de surveillance du véhicule."
	},
	
	"yjjc": {
		"cljkxx": "informations de surveillance du véhicule",
		"xx_09": "Détection des informations du véhicule",
		"xx_03": "Détection des informations de défaut",
		"xx_01": "Détection des informations de surveillance du véhicule",
		"xx_02": "Détection des informations d'arrêt sur image",
		"xx_05": "Détection des informations du capteur d'oxygène",
		"xx_06": "Lecture d'informations de résultat de surveillance spécifiques"
	},
	
	"ybpgl":{
		"dcdy": "Tension de la batterie",
		"xhyb": "Compteur de croisière",
		"yhyb": "Compteur de consommation de carburant",
		"zdyyb": "Compteur personnalisé",
		"xz": "Ajouter un tableau de bord",
		"bj": "Modifier le tableau de bord",
		"sc": "Supprimer le tableau de bord",
		"delete_tips": "Êtes-vous sûr de vouloir supprimer le tableau de bord ?"
	},
	
		
	"status": {
		"1000": "Bluetooth n'est pas activé",
		"1001": "Bluetooth est désactivé",
		"1002": "En attente d'économie de carburant",
		"1003": "Recherche OBD",
		"1004": "Connexion OBD",
		"1005": "Bluetooth est connecté",
		"1006": "écriture de données réussie",
		"1007": "Échec de l'écriture des données",
		"1008": "Activer la notification avec succès",
		"1009": "Aucun appareil trouvé"
	},

  
	"szgl": {
		"bt": "Paramètre",
		"label1": "Langue",
		"value1": "Suivre le système",
		"label2": "Politique de confidentialité",
		"label3": "Aide à la connexion",
		"label4": "À propos",
		"label5": "Centre commercial officiel",
		"value5": "Centre commercial 1688",
		"label6": "Version",
		"cjwt": "Problème courant",
		"unittitle": "Unité",
		"unitvalue1": "Système métrique",
		"unitvalue2": "Unités impériales",
		"unitinfo": "Confirmer s'il faut changer d'unité ?"
	},

	"yygl": {
		"label": "Suivre le système",
		"des": "Une fois allumé, il sera automatiquement défini en fonction de la langue du système",
		"en": "Anglais",
		"zh": "Chinois simplifié",
		"zwft": "Chinois traditionnel",
		"es": "Espagnol",
		"kr": "Coréen",
		"ru": "russe",
		"ja": "japonais",
		"it": "italien",
		"hi": "hindi",
		"pt": "portugais",
		"de": "Allemand",
		"fr": "Français",
		"nl": "Néerlandais",
		"fi": "finnois",
		"pl": "polonais",
		"bn": "bengali",
		"hu": "hongrois",
		"cs": "Tchèque",
		"th": "thaï",
		"tr": "Turc",
		"ms": "Malais",
		"ro": "roumain",
		"sv": "Suédois",
		"da": "danois"
	},

	
	"obdManage": {
		"bt": "Gestion OBD",
		"search_tip": "Veuillez effectuer une nouvelle recherche ou acheter nos produits",
		"buy_tip": "Veuillez vous rendre au centre commercial pour acheter",
		"searchAgain": "Rechercher à nouveau",
		"nearBy": "Équipement à proximité",
		"ls": "Équipement historique",
		"bz": "Afficher l'aide",
		"del": "Supprimer",
		"delConfirm": "Êtes-vous sûr de vouloir supprimer cet enregistrement ?",
		"switched": "L'appareil est sur le point d'être changé, êtes-vous sûr ?",
		"qrxx": "Veuillez confirmer que le commutateur Bluetooth et les informations de localisation du téléphone portable sont activés.",
		"searchAgain_message": "Êtes-vous sûr de re-rechercher les appareils à proximité ?"
	},

	
"gzjc": {
		"bt": "Diagnostic",
		"btn": "Démarrer les tests",
		"des": "Lancer une analyse complète de votre véhicule",
		"FaultCodeQuery": "Requête de code d'erreur",
		"zzjc": "Test",
		"clearFaultCode": "Effacer le code d'erreur",
		"kscz": "rechercher",
		"fxgz": "Code d'erreur trouvé",
		"notFound": "aucun problème trouvé",
		"cxjc": "Revérifier",
		"modalTitle": "Êtes-vous sûr de vouloir effacer le code d'erreur ?",
		"modalContent": "Avant que le défaut ne soit résolu, il est recommandé de ne pas effacer le code d'erreur à volonté. La plupart des calculateurs ne permettent pas de supprimer le code d'erreur lorsque le moteur tourne. Que le code d'erreur puisse être effacé ou non est finalement déterminé par l'ECU. La suppression des codes de panne n'est pas vraiment la solution au problème.",
		"sdjc": "Rapport d'inspection en profondeur",
		"num": "Nombre de codes défauts",
		"gzmxx": "Détails du code d'erreur",
		"label1": "catégorie",
		"label2": "Explication du code d'erreur",
		"definition_03": "Codes d'anomalie de diagnostic",
		"definition_07": "Codes d'anomalie de diagnostic en attente",
		"definition_0A": "Codes d'anomalie de diagnostic permanents",
		"03_des": "Lorsqu'une anomalie est détectée par l'ECU (unité de contrôle du véhicule), un code de panne est stocké dans la mémoire. Ce code de panne fait référence à une situation anormale trouvée au cours du processus de conduite récent. Ces codes de panne sont conservés en mémoire pendant un certain temps, lorsque le code d'erreur est retrouvé, mettez à jour la durée de conservation.",
		"07_des": "Il s'agit d'une anomalie non reconnue pendant la conduite. Si l'anomalie se répète et est identifiée, le code d'anomalie temporaire sera classé comme un code d'anomalie confirmé. S'il n'est pas enregistré, il sera supprimé lorsque le moteur sera éteint." ,
		"0A_des": "Parce qu'il affiche un historique des DTC passés, il ne représente pas l'état actuel du véhicule. Il peut ne pas être possible de supprimer par programme les DTC correspondants.",
		"sys_P": "Système de transmission (défini par le fabricant)",
		"sys_B": "Système corporel (défini par le fabricant)",
		"sys_C": "Système de suspension du châssis (défini par le fabricant)",
		"sys_U": "Système de communication réseau (défini par le fabricant)",
		"zzs": "Tous les constructeurs automobiles"
	},

	"clgl": {
		"bt": "Ma voiture",
		"info1": "Informations de base sur la voiture",
		"clpp": "Marques de voitures",
		"xh": "Modèle de voiture",
		"nk": "Année",
		"rylx": "Type de carburant",
		"info2": "Autres informations sur le véhicule",
		"atdp": "Protocole de communication",
		"ati": "Version de l'adaptateur",
		"vin": "Numéro d'identification du véhicule",
		"cid": "Identifications d'étalonnage",
		"cvn": "Numéros de vérification d'étalonnage",
		"ecu": "Unité de contrôle électronique",
		"ESN": "Numéro de série du moteur",
		"EROTAN": "Règlement d'échappement ou numéro d'homologation de type",
		"FEOCNTR": "Compteur de cycles d'allumage de fonctionnement du moteur alimenté",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Veuillez renseigner la marque du véhicule",
		"warn2": "le modèle de voiture est requis",
		"warn3": "l'année de la voiture est requise",
		"warn4": "vin est requis",
		"warn5": "Veuillez saisir le bon numéro d'identification du véhicule",
		"warn6": "le nom du propriétaire de la voiture est requis",
		"warn7": "le téléphone est requis",
		"warn8": "Veuillez entrer le bon téléphone",
		"warn9": "Veuillez saisir le bon e-mail",
		"bt": "La connexion OBD est réussie",
		"title_sub": "Les informations suivantes sont très importantes pour un diagnostic précis, afin d'améliorer votre expérience. Assurez-vous de les remplir attentivement.",
		"ts_vin": "L'emplacement du code VIN : généralement situé sur le côté gauche du tableau de bord, en bas à gauche du pare-brise avant ; il y a aussi une colonne de charnière de porte, une colonne de serrure de porte ou l'une des colonnes reliées à la colonne de serrure de porte ; ou la porte près du siège du conducteur à l'intérieur.",
		"vin": "Vin",
		"czxm": "Nom",
		"lxdh": "Téléphone",
		"lxyx": "E-mail"
	},
	"ota": {
		"bt": "Mise à niveau OTA",
		"jcdxbb": "Nouvelle version du firmware détectée",
		"gxnr": "Mettre à jour le contenu",
		"fxsm": "Instructions de mise à jour",
		"fxsm_des": "La mise à niveau OTA (technologie sans fil) signifie que le terminal mobile télécharge à distance le package de mise à niveau sur le serveur pour mettre à niveau le micrologiciel OBD. La mise à niveau n'affectera pas votre véhicule et votre sécurité de conduite, n'hésitez pas à utiliser S'il vous indique que la mise à niveau a échoué, ne quittez pas l'interface, réinsérez l'OBD et continuez la mise à niveau.",
		"zysx": "Attention",
		"zysx_des": "Ne mettez pas à niveau pendant la conduite, et ne retirez pas ou n'éteignez pas l'OBD pendant la mise à niveau.",
		"mssj": "Mettre à niveau maintenant",
		"kssj": "Démarrer la mise à jour",
		"sjcg": "Mise à jour OTA réussie",
		"kqqxty": "Ouvrir une nouvelle expérience",
		"xzgj": "Télécharger le micrologiciel",
		"zzxr": "Écriture",
		"zzsj": "Mise à jour",
		"zzjy": "Vérification de l'intégrité",
		"sjsb": "La mise à jour a échoué, réessayez"
	},

	"xcfx": {
		"ksxc": "Commencer le voyage",
		"jsxc": "Fin du voyage",
		"lsjl": "Enregistrement de l'historique",
		"zlc": "Kilométrage total",
		"hs": "Cela prend du temps",
		"kssj": "Heure de début",
		"zyh": "Litres totaux"
	},

	"xncs": {
		"jsxn": "Accéléré",
		"scxn": "Freinage",
		"jlxn": "Distance",
		"des1": "Plage de test de vitesse",
		"des2": "vitesse au freinage",
		"des3": "distance d'essai",
		"aqtx": "veuillez faire attention à la sécurité de conduite !",
		"kscs": "Démarrer le test",
		"cxcs": "Re-tester",
		"tz": "Arrêter",
		"tip1": "Veuillez ajuster la vitesse du véhicule à",
		"tip2": "Veuillez appuyer sur l'accélérateur pour accélérer",
		"tip2_end": "Au-dessus",
		"tip3": "Veuillez appuyer sur les freins pour réduire la vitesse à",
		"tip4": "Veuillez conduire",
		"tip5": "Voyage",
		"max_sd": "Vitesse maximale",
		"max_jsd": "Accélération maximale",
		"max_zs": "Vitesse maximale",
		"tx1": "La vitesse de démarrage ne peut pas être supérieure à la vitesse de fin",
		"tx2": "Veuillez renseigner la vitesse de freinage supérieure à 0",
		"tx3": "Veuillez renseigner la distance de test supérieure à 0"
	},

	"bzxx": {
		"title1": "Étape 1 : Démarrez le véhicule",
		"title2": "Étape 2 : branchez l'appareil",
		"title3": "Étape 3 : Activez le Bluetooth et la localisation",
		"title4": "Étape 4 : Ouvrez l'application",
		"title5": "Étape 5 : Connecter l'appareil",
		"text1": "Trouvez l'emplacement de l'interface OBD du véhicule. L'interface OBD est une interface femelle à 16 broches. L'interface est trapézoïdale. Certains modèles ont un couvercle sur l'interface OBD. Les ports OBD courants sont noirs, blancs ou bleus. L'emplacement se trouve généralement dans le panneau de garnissage intérieur sous le volant, près des genoux du conducteur. L'emplacement de l'interface OBD peut être différent pour différents modèles et modèles. La figure suivante montre l'emplacement possible de l'interface OBD : ",
		"text2": "Après avoir trouvé l'interface OBD, branchez l'appareil dans l'interface OBD. Assurez-vous qu'il est complètement branché (de nombreuses voitures sont branchées à mi-chemin environ et l'alimentation est allumée, mais les broches de signal peuvent ne pas être connecté), et le voyant d'alimentation rouge ou l'écran est allumé.",
		"text3": "Activez les commutateurs Bluetooth et de localisation sur votre téléphone. Méthode : balayez vers le bas en haut de l'écran du téléphone, ouvrez le menu contextuel, puis cliquez sur Bluetooth et informations de localisation. Activez Bluetooth sur votre appareil iOS.",
		"text4": "Ouvrez l'application et autorisez l'application à utiliser les informations de localisation.",
		"text5": "Après avoir terminé les étapes ci-dessus, entrez dans l'APP, l'APP analysera automatiquement l'appareil OBD et vous demandera si vous souhaitez connecter l'appareil. L'appareil iOS demande s'il faut autoriser l'accès à l'adresse, cliquez sur Autoriser.",
		"text6": "Sélectionnez l'appareil à connecter et cliquez pour vous connecter. Une fois la connexion établie, la page d'accueil de l'APP affichera le nom de l'appareil OBD, l'adresse Bluetooth et une lecture apparaîtra sur le tableau de bord."
	},
	
	"06fw": {
		"MID": "Nom du moniteur",
		"TID": "Nom du test",
		"CID": "Numéro de composant",
		"O2Sensor": "Nom du capteur O2",
		"MIN": "Limite minimale",
		"MAX": "Limite maximale",
		"CURRENT": "Valeur test"
	},
	
	"09fw": {
		"ipt": "Suivi des performances en cours d'utilisation",
		"IPT_08_1": "Nombre de conditions de surveillance OBD rencontrées",
		"IPT_08_2": "Compteur de cycles d'allumage",
		"IPT_08_3": "L'achèvement du moniteur Catalyst compte la banque 1",
		"IPT_08_4": "Les conditions de moniteur de catalyseur rencontrées comptent la banque 1",
		"IPT_08_5": "L'achèvement du moniteur Catalyst compte la banque 2",
		"IPT_08_6": "Les conditions de moniteur de catalyseur rencontrées comptent la banque 2",
		"IPT_08_7": "L'achèvement du moniteur de capteur O2 compte la banque 1",
		"IPT_08_8": "Les conditions de surveillance du capteur O2 rencontrées comptent la banque 1",
		"IPT_08_9": "L'achèvement du moniteur de capteur O2 compte la banque 2",
		"IPT_08_10": "Les conditions de surveillance du capteur O2 rencontrées comptent la banque 2",
		"IPT_08_11": "Comptage des conditions d'achèvement du moniteur EGR et/ou VVT",
		"IPT_08_12": "Nombre de conditions de surveillance EGR et/ou VVT rencontrées",
		"IPT_08_13": "La condition d'achèvement du moniteur AIR compte (air secondaire)",
		"IPT_08_14": "Nombre de conditions de surveillance d'air rencontrées (air secondaire)",
		"IPT_08_15": "Compte des conditions d'achèvement du moniteur EVAP",
		"IPT_08_16": "Nombre de conditions de surveillance EVAP rencontrées",
		"IPT_08_17": "L'achèvement du moniteur de capteur O2 secondaire compte la banque 1",
		"IPT_08_18": "Les conditions de surveillance du capteur O2 secondaire rencontrées comptent la banque 1",
		"IPT_08_19": "L'achèvement du moniteur de capteur O2 secondaire compte la banque 2",
		"IPT_08_20": "Les conditions de surveillance du capteur d'O2 secondaire rencontrées comptent la banque 2",
		
		"IPT_08_des_1": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance OBD spécifiées (dénominateur général).",
		"IPT_08_des_2": "affiche le nombre de fois que le moteur a été démarré.",
		"IPT_08_des_3": "affiche le nombre de fois que toutes les conditions nécessaires à la détection d'un dysfonctionnement de la batterie 1 du système catalytique ont été rencontrées (numérateur).",
		"IPT_08_des_4": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du catalyseur spécifiées (dénominateur).",
		"IPT_08_des_5": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement de la banque 2 du système catalytique ont été rencontrées (numérateur).",
		"IPT_08_des_6": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du catalyseur spécifiées (dénominateur).",
		"IPT_08_des_7": "affiche le nombre de fois que toutes les conditions nécessaires à la détection d'un dysfonctionnement du banc de capteurs d'oxygène 1 ont été rencontrées (numérateur).",
		"IPT_08_des_8": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du capteur d'oxygène spécifiées (dénominateur).",
		"IPT_08_des_9": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement du banc de capteurs d'oxygène 2 ont été rencontrées (numérateur).",
		"IPT_08_des_10": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du capteur d'oxygène spécifiées (dénominateur).",
		"IPT_08_des_11": "affiche le nombre de fois que toutes les conditions nécessaires pour détecter un dysfonctionnement du système EGR/VVT ont été rencontrées (numérateur).",
		"IPT_08_des_12": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du système EGR/VVT spécifiées (dénominateur).",
		"IPT_08_des_13": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement du système AIR ont été rencontrées (numérateur).",
		"IPT_08_des_14": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du système AIR spécifiées (dénominateur).",
		"IPT_08_des_15": "affiche le nombre de fois où toutes les conditions nécessaires pour détecter un dysfonctionnement du système EVAP de 0,020” (ou 0,040”) ont été rencontrées (numérateur).",
		"IPT_08_des_16": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance de dysfonctionnement du système EVAP spécifiées (dénominateur).",
		"IPT_08_des_17": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement de la banque de capteurs d'oxygène secondaire 1 ont été rencontrées (numérateur).",
		"IPT_08_des_18": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du capteur d'oxygène secondaire spécifiées (dénominateur).",
		"IPT_08_des_19": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement d'un banc de sondes à oxygène secondaire 2 ont été rencontrées (numérateur).",
		"IPT_08_des_20": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du capteur d'oxygène secondaire spécifiées (dénominateur).",
		
		"IPT_0B_1": "Nombre de conditions de surveillance OBD rencontrées",
		"IPT_0B_2": "Compteur de cycles d'allumage",
		"IPT_0B_3": "Condition d'achèvement du moniteur NMHC Catalyst Counts",
		"IPT_0B_4": "Nombre de conditions rencontrées dans le moniteur de catalyseur NMHC",
		"IPT_0B_5": "Nombre de conditions d'achèvement du moniteur de catalyseur NOx/SCR",
		"IPT_0B_6": "Nombre de conditions rencontrées dans le moniteur de catalyseur NOx/SCR",
		"IPT_0B_7": "Nombre de conditions d'achèvement du moniteur d'adsorbeur de NOx",
		"IPT_0B_8": "Nombre de conditions rencontrées dans le moniteur d'adsorbeur de NOx",
		"IPT_0B_9": "Compte des conditions d'achèvement du moniteur de filtre PM",
		"IPT_0B_10": "Nombre de conditions de surveillance du filtre PM rencontrées",
		"IPT_0B_11": "La condition d'achèvement du moniteur de capteur de gaz d'échappement compte",
		"IPT_0B_12": "Les conditions de surveillance du capteur de gaz d'échappement rencontrées comptent",
		"IPT_0B_13": "Comptage des conditions d'achèvement du moniteur EGR et/ou VVT",
		"IPT_0B_14": "Nombre de conditions de surveillance EGR et/ou VVT rencontrées",
		"IPT_0B_15": "La condition d'achèvement du moniteur de pression de suralimentation compte",
		"IPT_0B_16": "Les conditions de surveillance de la pression de suralimentation rencontrées comptent",
		"IPT_0B_17": "La condition d'achèvement du moniteur de carburant compte",
		"IPT_0B_18": "Les conditions de surveillance du carburant rencontrées comptent",
		
		"IPT_0B_des_1": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance OBD spécifiées (dénominateur général).",
		"IPT_0B_des_2": "affiche le nombre de fois que le moteur a été démarré.",
		"IPT_0B_des_3": "affiche le nombre de fois que toutes les conditions nécessaires pour détecter un dysfonctionnement du système de catalyseur NMHC ont été rencontrées (numérateur).",
		"IPT_0B_des_4": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du catalyseur NMHC spécifiées (dénominateur).",
		"IPT_0B_des_5": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement du système catalyseur NOx ont été rencontrées (numérateur).",
		"IPT_0B_des_6": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du catalyseur NOx spécifiées (dénominateur).",
		"IPT_0B_des_7": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement du système adsorbeur de NOx ont été rencontrées (numérateur).",
		"IPT_0B_des_8": "affiche le nombre de fois où le véhicule a été utilisé dans le dénominateur des conditions de surveillance de l'adsorbeur de NOx spécifié).",
		"IPT_0B_des_9": "affiche le nombre de fois que toutes les conditions nécessaires pour détecter un dysfonctionnement du système de filtre PM ont été rencontrées (numérateur).",
		"IPT_0B_des_10": "affiche le nombre de fois où le véhicule a été utilisé dans le dénominateur des conditions de surveillance du filtre PM spécifié).",
		"IPT_0B_des_11": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement du capteur de gaz d'échappement ont été rencontrées (numérateur)",
		"IPT_0B_des_12": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du capteur de gaz d'échappement spécifiées (dénominateur).",
		"IPT_0B_des_13": "affiche le nombre de fois que toutes les conditions nécessaires pour détecter un dysfonctionnement du système EGR/VVT ont été rencontrées (numérateur).",
		"IPT_0B_des_14": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du système EGR/VVT spécifiées (dénominateur).",
		"IPT_0B_des_15": "affiche le nombre de fois que toutes les conditions nécessaires pour détecter un dysfonctionnement du système de pression de suralimentation ont été rencontrées (numérateur).",
		"IPT_0B_des_16": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du système de pression de suralimentation spécifiées (dénominateur).",
		"IPT_0B_des_17": "affiche le nombre de fois où toutes les conditions nécessaires à la détection d'un dysfonctionnement du système d'alimentation ont été rencontrées (numérateur).",
		"IPT_0B_des_18": "affiche le nombre de fois où le véhicule a été utilisé dans les conditions de surveillance du système de carburant spécifiées (dénominateur)."
	}
}