// 意大利语
var i18n = {
	'mt': "Giorno",
	'xs': "Ore",
	'fz': "Minuti",
	"wxts": "Suggerimenti",
	"zzjz": "caricamento...",
	'noData': "NESSUN DATO",
	"jchj" :"Controlla l'ambiente",
	"ckfw": "scopo",
	"bbgl": {
		"bbts": "Promemoria aggiornamento versione",
		"official": "Sono state rilasciate nuove funzionalità, visitare il sito Web ufficiale per scaricare e aggiornare l'ultima versione.",
		"apple": "Sono state rilasciate nuove funzionalità, vai all'App Store per scaricare la versione aggiornata.",
		"google": "Sono state rilasciate nuove funzioni, vai su Google Play per scaricare la versione aggiornata.",
	},
	"uds": {
		"uds0001": "Seleziona modulo",
		"uds0002": "Seleziona il modulo da leggere",
		"uds0003": "L'elenco contiene tutti i moduli supportati della marca selezionata, si consiglia di selezionare solo i moduli che sono già presenti sull'auto, ma è possibile selezionare tutti i moduli. Il sistema rileverà automaticamente le unità effettivamente presenti sulla macchina.",
		"uds0004": "Seleziona tutto",
		"uds0005": "Annulla seleziona tutto",
		"uds0006": "Avvia diagnosi",
		"uds0007": "Venditore personalizzato"
	},
	"yjdl": {
		"yxdl": "Accesso e-mail",
		"dlts": "Inserisci prima il codice di verifica grafico, quindi ottieni il codice di verifica email",
		"sryx": "Inserisci email",
		"sryzm": "Inserisci il codice di verifica",
		"xyb": "Avanti",
		"xgyx": "Modifica casella di posta",
		"yxdz": "Indirizzo email",
		"fsyzm": "invia il codice di accesso all'email",
		"yzm": "Codice di accesso",
		"cxfs": "secondi per inviare nuovamente",
		"dl": "Accedi",
		"srtxyzm": "Inserisci il Captcha grafico a sinistra",
		"yxbzq": "L'email non è corretta",
		"txyzmbzq": "Il codice di verifica grafica non è corretto",
		"fsdx": "invio in corso",
		"yxyzmfscg": "Invia con successo",
		"yxbky": "L'invio di e-mail è anomalo! Si prega di verificare se l'indirizzo e-mail è stato inserito correttamente e se l'e-mail può essere ricevuta normalmente.",
		"zzyz": "Verifica",
		"yzmcw": "Il codice di verifica email non è corretto",
		"clxxgl": "Gestione informazioni veicolo",
		"gxxx": "Aggiorna informazioni",
		"dlcg": "Accesso riuscito",
		"dlsb": "Accesso non riuscito",
		"clxx": "Informazioni sul veicolo",
		"czxx": "Informazioni sul proprietario dell'auto",
		"wdl": "Accesso non effettuato",
		"cl": "Veicolo",
	},
	
	"OBDxncs": {
		"bt": "Confronto di adattatori",
		"fbt": "più grande significa più veloce",
		"zjsd": "Velocità ottimale",
		"dqsd": "Velocità attuale",
		"xzmc": "La velocità con cui i parametri vengono letti dalla ECU al secondo (unità: parametri/secondo)",
		"sec_dt": "Testato con Galaxy Note 8 e Pixel 2",
		"sec_dd1": "(1) Gli adattatori Wi-Fi non sono generalmente consigliati per Android, poiché la maggior parte dei telefoni perde la connessione dati a Internet durante l'uso.",
		"sec_dd2": "(2) Tutti gli adattatori testati sono Bluetooth standard a meno che 'WiFi', 'USB' o 'BLE' non facciano parte del loro nome",
		"text2": "Confronto di OBD",
	},

	"tsxx": {
		'qxz': "scegliere",
		'qsr': "Inserisci",
		'qqr': "Conferma",
		'qqx': "Annulla",
		'notConnected': "Per favore connetti prima il tuo dispositivo",
		'save': "Salva il modulo con successo.",
		'dsyh': 'Il consumo di carburante al minimo si riferisce al consumo di carburante nel momento in cui il veicolo è fermo, con il tempo come unità statistica.',
		'xsyh': 'Il consumo di carburante durante la guida si riferisce al consumo di carburante nel momento in cui il veicolo è in uno stato di guida e prende la distanza come unità statistica.',
		'pjyh': 'Il consumo medio di carburante si riferisce al consumo di carburante per 100 chilometri del veicolo durante questo processo di guida e viene visualizzato solo dopo aver percorso più di 1 km.',
		'cqyh': "Il consumo di carburante a lungo termine si riferisce al consumo di carburante consumato dal veicolo per 100 chilometri durante il funzionamento dell‘APP.",
		'yhsupport': 'Questa vettura non supporta la visualizzazione del consumo di carburante',
		'cg': 'successo',
		'noTrouble': 'Congratulazioni, la tua auto è perfetta, continua così.',
		'noVin': 'Inserisci il numero di frame a 17 cifre in modo che possiamo fornirti un servizio migliore.',
		'gzzsd': "MIL è l'abbreviazione di Malfunction Indicator Lamp. Quando la spia MIL è accesa, significa che il sistema motore potrebbe non funzionare correttamente. Il motivo dell'accensione della spia MIL potrebbe essere che c'è troppa deposizione di carbonio all'interno della valvola a farfalla o del motore, o il rapporto di miscela è sbilanciato dopo che il sensore di ossigeno si è guastato o la spia del motore è accesa a causa della scarsa qualità del carburante della benzina e la combustione insufficiente del veicolo.",
		'noDevelopment': 'In fase di sviluppo, restate sintonizzati. ',
		"zc": "Attualmente disponibile per il test",
		"noSupport": "Attualmente non disponibile per il test",
		"noNetwork": "La tua rete non è attualmente disponibile. Nessuna rete influenzerà la tua esperienza.",
		"jy": "disabilitato",
		"ywc": "Test di stato completato",
		"noCompelte": "Test di stato non completato",
		"noSupportPid": "Il tuo veicolo non ha questo test!",
		"useReminders": "Promemoria: dopo la pausa, puoi eseguire lo zoom o il roaming facendo scorrere il dito sul dispositivo di scorrimento o sul touch screen.",
		"noCompelteDes": "Se lo stato di pronto può essere testato ma non completato, si possono prendere le seguenti misure articolo per articolo: guidare completamente, effettuare la manutenzione del veicolo, pulire l'assieme, aggiornare la ECU, ecc. Si spera che il processo di guida in futuro verrà utilizzato in conformità con le specifiche e verrà eseguita una manutenzione regolare.",
		"fgf": "Questa funzione è esclusiva dei prodotti ufficiali, utilizzala dopo l'acquisto!",
		"b25": "Questa funzione è esclusiva di B25, utilizzala dopo l'acquisto!"
	},
	"pid": {
		"dsyh": "Consumo di carburante al minimo",
		'xsyh': "consumo di carburante",
		"ssyh": "Consumo medio",
		"pjyh": "Consumo istantaneo",
		"cqyh": "Consumo di carburante a lungo termine",
		"pjsd": "Velocità media",
		"xslc": "Distanza guidata",
		"DTC_legnth": "# di DTC memorizzati in questa ECU",
		"MIL": "Stato spia di malfunzionamento",
		"mil_0": 'luce spenta',
		"mil_1": 'luce accesa',
		"shxt": "Monitoraggio mancata accensione",
		"ryxt": "Monitoraggio del sistema di alimentazione",
		"zhzj": "Monitoraggio completo dei componenti",

		"fdjlx": "Tipo di motore",
		"ysfdj": "accensione per compressione",
		"dhfdj": "accensione a scintilla",
		'chj': "Monitoraggio catalizzatore",
		'jrchj': "Monitoraggio del catalizzatore riscaldato",
		'zfxt': "Monitoraggio del sistema evaporativo",
		"eckqxt": "Monitoraggio impianto aria secondaria",
		"ktxtzlj": "Monitoraggio refrigerante impianto A/C",
		"ycgqjrq": "Monitoraggio riscaldatore sensore ossigeno",
		"ycgqjk": "Monitoraggio sensore ossigeno",
		"erg": "Monitoraggio del sistema EGR/VVT",
		"NMHC": "Monitoraggio catalizzatore NMHC",
		"NOx": "Monitoraggio NOx/SCR",
		"yl": "Riservato",
		"zyyl": "Monitoraggio pressione boost",
		"fqcgq": "Monitoraggio sensore gas di scarico",
		"pmglq": "Monitoraggio monitoraggio filtro PM",
	},


	"sygl": {
		"xieyi": "Protocollo",
		"tips1": "Collega il dispositivo",
		"tips2": "Attiva il Bluetooth! Visualizza aiuto",
		"tips3": "Non riesci a trovare il dispositivo? Visualizza la guida",
		"tips4": "Attiva i servizi di localizzazione",
		"tips5": "Universale",
		"tips6": " Versione economica",
		'sdlj': "Seleziona manualmente una connessione"
	},

	"djz": {
		"noData": "Al momento non ci sono dati di fermo immagine",
		"previousFrame": "Precedente",
		"nextFrame": "Prossimo",
	},

	"fwgl": {
		"ybp": "Dashboard",
		"UDS": "Servizio diagnostico unificato (test)",
		"UDS_des": "Fornisci un servizio di diagnosi unificata del veicolo, più centraline e più funzioni",
		"DTC": "Monitoraggio DTC",
		"DTC_des": "Fornire soluzioni professionali per i codici di errore dei veicoli",
		"xcfx": "Analisi di viaggio",
		"xcfx_des": "Analizza i dati di ogni tuo viaggio",
		"xncs": "Test delle prestazioni del veicolo",
		"xncs_des": "Fornire un rapporto di analisi delle prestazioni del veicolo professionale",
		"sssjl": "flusso di dati in tempo reale",
		"sssjl_des": "Richiedi dati diagnostici powertrain attuali",
		"gzzsd": "Rilevamento indicatore di guasto",
		"gzzsd_des": "Fornisce informazioni sul funzionamento del veicolo dopo l'accensione o lo spegnimento della spia di guasto",

		"pid0141": "Stato diagnostico pronto",
		"pid0141_des": "Fornisce lo stato di monitoraggio del veicolo da quando il DTC è stato cancellato e lo stato operativo del monitoraggio del ciclo di guida attuale",
		"$05": "Risultati del monitoraggio del sensore di ossigeno",
		"$05_des": "Leggi i risultati del test del monitoraggio del sensore di ossigeno del veicolo",
		"$06": "Risultati di monitoraggio specifici",
		"$06_des": "consente l'accesso ai risultati dei test di monitoraggio della diagnostica di bordo per componenti/sistemi specifici.",
		"$09": "Informazioni sul veicolo",
		"$09_des": "Leggi le informazioni e le informazioni specifiche sul veicolo",
		"clnj": "",
		"clnj_des": "",
		"obdTest": "Test delle prestazioni OBD",
		"obdTest_des": "Testa vari indicatori di prestazione di OBD attraverso strumenti di test automatizzati.",
		"djz": "Blocca fotogramma",
		"djz_des": "Quando appare un DTC nel sistema di scarico, la ECU memorizza i dati quando appare il DTC",
		"yjjc": "Rilevamento completo del veicolo con un clic",
		"yjjc_des": "Rilevamento completo di tutti i dati dei sensori del veicolo, informazioni sul veicolo, codici di errore, fermo immagine e informazioni sul monitoraggio del veicolo."
	},

	"yjjc": {
		'cljkxx': "informazioni sul monitoraggio del veicolo",
		"xx_09": "Rilevamento delle informazioni sul veicolo",
		"xx_03": "Rilevamento delle informazioni sull'errore",
		"xx_01": "Rilevamento delle informazioni di monitoraggio del veicolo",
		"xx_02": "Rilevamento informazioni fermo immagine",
		"xx_05": "Rilevamento delle informazioni del sensore di ossigeno",
		"xx_06": "Lettura di informazioni specifiche sui risultati del monitoraggio"
	},

	"ybpgl": {
		"dcdy": "Tensione batteria",
		"xhyb": "Cruise Meter",
		"yhyb": "Contatore del consumo di carburante",
		"zdyyb": "Contatore personalizzato",
		"xz": "Aggiungi dashboard",
		"bj": "Modifica dashboard",
		"sc": "Elimina dashboard",
		"delete_tips": "Sei sicuro di eliminare la dashboard?",
	},


	"status": {
		"1000": 'Bluetooth non è acceso',
		"1001": 'Bluetooth spento',
		"1002": 'In attesa di risparmio di carburante',
		"1003": 'Ricerca OBD',
		"1004": 'Collegamento OBD',
		"1005": 'Bluetooth è connesso',
		"1006": 'scrittura dei dati riuscita',
		"1007": 'Impossibile scrivere i dati',
		"1008": 'Abilita notifica riuscita',
		"1009": 'Nessun dispositivo trovato',
	},


	"szgl": {
		"bt": "Impostazione",
		"label1": "Lingua",
		"value1": "Segui sistema",
		"label2": "Informativa sulla privacy",
		"label3": "Aiuto alla connessione",
		"label4": "Informazioni",
		"label5": "Centro commerciale ufficiale",
		"value5": "1688 Mall",
		"label6": "Versione",
		"cjwt": "Problema comune",
		"unittitle": "Unità",
		"unitvalue1": "Sistema metrico",
		"unitvalue2": "Unità imperiali",
		"unitinfo": "Confermare se cambiare unità?",
	},

	"yygl": {
		"label": "Segui il sistema",
		"des": "Dopo l'accensione, verrà impostato automaticamente in base alla lingua del sistema",
		"en": "English",
		"zh": "Cinese semplificato",
		"zwft": "Cinese tradizionale",
		"es": "spagnolo",
		"kr": "coreano",
		"ru": "russo",
		"ja": "giapponese",
		'it': "italiano",
		"hi": "hindi",
		"pt": "portoghese",
		"de": "tedesco",
		"fr": "francese",
		"nl": "olandese",
		"fi": "finlandese",
		"pl": "polacco",
		"bn": "bengalese",
		"hu": "ungherese",
		"cs": "ceco",
		"th": "tailandese",
		"tr": "turco",
		"ms": "malese",
		"ro": "rumeno",
		"sv": "svedese",
		"da": "danese"
	},


	"obdManage": {
		"bt": "Gestione OBD",
		"search_tip": "Ricerca o acquista i nostri prodotti",
		"buy_tip": "Per favore, vai al centro commerciale per comprare",
		"searchAgain": "Cerca ancora",
		"nearBy": "Attrezzature nelle vicinanze",
		"ls": "Attrezzature storiche",
		"bz": "Visualizza aiuto",
		"del": "Elimina",
		"delConfirm": "Sei sicuro di eliminare questo record?",
		"switched": "Il dispositivo sta per essere cambiato, sei sicuro?",
		"qrxx": "Confermare che il Bluetooth e l'interruttore delle informazioni sulla posizione del telefono cellulare sia attivato.",
		"searchAgain_message": "Sei sicuro di cercare nuovamente i dispositivi nelle vicinanze?",
	},

	"gzjc": {
		"bt": "Diagnostica",
		"btn": "Inizia il test",
		"des": "Avvia una scansione completa del tuo veicolo",
		"FaultCodeQuery": "Richiesta del codice di errore",
		"zzjc": "Testing",
		"clearFaultCode": "Cancella codice errore",
		"kscz": "Cerca",
		"fxgz": "Codice guasto trovato",
		"notFound": "nessun problema trovato",
		"cxjc": "Ricontrolla",
		"modalTitle": "Sei sicuro di voler cancellare il codice di errore?",
		"modalContent": "Prima che l'errore sia risolto, si consiglia di non cancellare il codice di errore a piacimento. La maggior parte delle centraline elettroniche non consente di eliminare il codice di errore quando il motore è in funzione. In definitiva, è possibile eliminare o meno il codice di errore determinato dalla ECU. L'eliminazione dei codici di errore non è davvero la soluzione al problema.",
		"sdjc": "Rapporto di ispezione di profondità",
		"num": "Numero di codici di errore",
		"gzmxx": "Dettagli del codice di errore",
		"label1": "categoria",
		"label2": "Spiegazione del codice di errore",
		"definition_03": "Codici di errore diagnostici",
		"definition_07": "Codici di errore diagnostici in sospeso",
		"definition_0A": "Codici di errore diagnostici permanenti",
		"03_des": "Quando viene rilevata un'anomalia dalla ECU (Unità di controllo del veicolo), viene memorizzato un codice di errore. Questo codice di errore si riferisce a una situazione anomala rilevata durante il processo di guida recente. Questi codici di errore vengono mantenuti in memoria per un periodo di tempo, quando il codice di errore viene ritrovato, aggiornare il periodo di conservazione.",
		"07_des": "Questa è un'anomalia non riconosciuta durante la guida. Se l'anomalia viene ripetuta e identificata, il codice di errore temporaneo verrà classificato come un codice di errore confermato. Se non viene salvato, verrà eliminato allo spegnimento del motore.",
		"0A_des": "Poiché mostra una cronologia dei DTC passati, non rappresenta lo stato attuale del veicolo. Potrebbe non essere possibile eliminare programmaticamente i DTC corrispondenti.",
		"sys_P": "Sistema powertrain (definito dal produttore)",
		"sys_B": "Sistema carrozzeria (definito dal produttore)",
		"sys_C": "Sistema di sospensione del telaio (definito dal produttore)",
		"sys_U": "Sistema di comunicazione di rete (definito dal produttore)",
		"zzs": "Tutte le case automobilistiche"
	},

	"clgl": {
		"bt": "La mia macchina",
		"info1": "Informazioni di base sull'auto",
		"clpp": "Marchi di automobili",
		"xh": "Modello di automobile",
		"nk": "Anno",
		"rylx": "Tipo di carburante",
		"info2": "Altre informazioni sul veicolo",
		"atdp": "Protocollo di comunicazione",
		"ati": "Versione adattatore",
		"vin": "Numero di identificazione del veicolo",
		"cid": "Identificazioni di calibrazione",
		"cvn": "Numeri di verifica della calibrazione",
		"ecu": "Centralina Elettronica",
		"ESN": "Numero di serie del motore",
		"EROTAN": "Regolamento di scarico o numero di omologazione",
		"FEOCNTR": "Contacicli di accensione del motore alimentato",
		"obd": "OBDSUP",
	},

	"clbj": {
		'warn1': "Si prega di inserire la marca del veicolo",
		'warn2': "è richiesto il modello dell'auto",
		'warn3': "è richiesto l'anno dell'auto",
		'warn4': "vin is require",
		'warn5': "Si prega di inserire il numero di identificazione del veicolo corretto",
		'warn6': "è richiesto il nome del proprietario dell'auto",
		'warn7': "è richiesto il telefono",
		'warn8': "Inserisci il telefono corretto",
		'warn9': "Inserisci l'e-mail corretta",
		"bt": "Connessione OBD riuscita",
		"title_sub": "Le seguenti informazioni sono molto importanti per una diagnosi accurata. Si prega di compilarle attentamente.",
		"ts_vin": "La posizione del codice VIN: generalmente sul lato sinistro del cruscotto, sul lato inferiore sinistro del parabrezza anteriore; anche sul montante della cerniera della portiera, sul montante della serratura della portiera o su uno dei montanti laterali della porta collegata al montante della serratura della porta; o l'interno della porta vicino al sedile del conducente.",
		"vin": "vin",
		"czxm": "Nome",
		"lxdh": "Telefono",
		"lxyx": "E-mail"
	},
	"ota": {
		"bt": "Aggiornamento OTA",
		"jcdxbb": "Rilevata nuova versione firmware",
		"gxnr": "Aggiorna contenuto",
		"fxsm": "Istruzioni per l'aggiornamento",
		"fxsm_des": "L'aggiornamento OTA (tecnologia over-the-air) significa che il terminale mobile scarica in remoto il pacchetto di aggiornamento sul server per aggiornare il firmware OBD. L'aggiornamento non influirà sul tuo veicolo e sulla sicurezza di guida, non esitare a utilizzarlo Se indica che l'aggiornamento non è riuscito, non uscire dall'interfaccia, reinserire l'OBD e continuare l'aggiornamento.",
		"zysx": "Attenzione",
		"zysx_des": "Non aggiornare durante la guida e non rimuovere o spegnere l'OBD durante l'aggiornamento.",
		"mssj": "Aggiorna ora",
		"kssj": "Avvia l'aggiornamento",
		"sjcg": "Aggiornamento OTA riuscito",
		"kqqxty": "Apri una nuova esperienza",
		"xzgj": "Scarica firmware",
		"zzxr": "Scrivere",
		"zzsj": "Aggiornamento",
		"zzjy": "Verifica integrità",
		"sjsb": "Aggiornamento fallito, riprova",
	},

	"xcfx": {
		"ksxc": "Inizia il viaggio",
		"jsxc": "Termina il viaggio",
		"lsjl": "Registro storico",
		'zlc': "Chilometraggio totale",
		'hs': 'Dispendioso in termini di tempo',
		'kssj': 'Ora di inizio',
		'zyh': 'Litri totali',
	},

	"xncs": {
		'jsxn': 'Accelerato',
		'scxn': 'Frenata',
		'jlxn': 'Distanza',
		'des1': 'Gamma di test di velocità',
		'des2': 'velocità in frenata',
		'des3': 'distanza di prova',
		'aqtx': 'prestare attenzione alla sicurezza di guida!',
		'kscs': 'Inizia il test',
		'cxcs': 'Re-test',
		"tz": 'basta',
		"tip1": "Regola la velocità del veicolo a",
		"tip2": "Premere l'acceleratore per accelerare fino a",
		"tip2_end": "Sopra",
		"tip3": "Premere i freni per ridurre la velocità a ",
		'tip4': 'Per favore guida',
		'tip5': 'viaggiato',
		'max_sd': 'Velocità massima',
		'max_jsd': 'Accelerazione massima',
		'max_zs': 'Velocità massima',
		"tx1": "La velocità iniziale non può essere maggiore della velocità finale",
		"tx2": "Inserisci la velocità di frenata maggiore di 0",
		"tx3": "Compila la distanza di prova maggiore di 0"
	},

	"bzxx": {
		'title1': "Fase 1: avvia il veicolo",
		'title2': "Fase 2: Collega il dispositivo",
		'title3': "Fase 3: attiva Bluetooth e posizione",
		'title4': "Fase 4: apri l'APP",
		'title5': "Fase 5: Collega il dispositivo",
		'text1': "Trova la posizione dell'interfaccia OBD del veicolo. L'interfaccia OBD è un'interfaccia femmina a 16 pin. L'interfaccia è trapezoidale. Alcuni modelli hanno una copertura sull'interfaccia OBD. Le porte OBD comuni sono nere, bianche o blu. La posizione è generalmente nel pannello di rivestimento interno sotto il volante, vicino alle ginocchia del conducente. La posizione dell'interfaccia OBD può essere diversa per i diversi modelli e modelli. La figura seguente mostra la possibile posizione dell'interfaccia OBD:",
		'text2': "Dopo aver trovato l'interfaccia OBD, collega il dispositivo all'interfaccia OBD. Assicurati che sia collegato completamente (molte auto sono collegate a circa metà e l'alimentazione è accesa, ma i pin del segnale potrebbero non essere collegato) e l'indicatore di alimentazione rosso o lo schermo è acceso.",
		'text3': "Attiva il Bluetooth e gli interruttori di posizione sul telefono. Metodo: scorri verso il basso nella parte superiore dello schermo del telefono, apri il menu di scelta rapida e fai clic su Bluetooth e informazioni sulla posizione. Attiva il Bluetooth sul tuo dispositivo iOS.",
		'text4': "Apri l'app e consenti all'app di utilizzare le informazioni sulla posizione.",
		'text5': "Dopo aver completato i passaggi precedenti, accedi all'APP, l'APP eseguirà automaticamente la scansione del dispositivo OBD e ti chiederà se collegare il dispositivo. Il dispositivo iOS chiede se consentire l'accesso all'indirizzo, fai clic su Consenti.",
		'text6': "Seleziona il dispositivo da collegare e fai clic per connetterti. Dopo che la connessione è riuscita, la home page dell'APP visualizzerà il nome del dispositivo OBD, l'indirizzo Bluetooth e una lettura apparirà sul dashboard.",
	},

	'06fw': {
		"MID": "Nome monitor",
		"TID": "Nome test",
		"CID": "Numero componente",
		"O2Sensor": "Nome sensore O2",
		"MIN": "Limite minimo",
		"MAX": "Limite massimo",
		"CURRENT": "Valore di prova"
	},

	"09fw": {
		"ipt": "Tracciamento delle prestazioni in uso",
		"IPT_08_1": "Conteggi rilevati dalle condizioni di monitoraggio OBD",
		"IPT_08_2": "Contacicli di accensione",
		"IPT_08_3": "Il completamento del monitoraggio del catalizzatore conta il banco 1",
		"IPT_08_4": "Le condizioni di monitoraggio del catalizzatore rilevate contano il banco 1",
		"IPT_08_5": "Il completamento del monitoraggio del catalizzatore conta il banco 2",
		"IPT_08_6": "Le condizioni di monitoraggio del catalizzatore rilevate contano la banca 2",
		"IPT_08_7": "Il completamento del monitoraggio del sensore O2 conta il banco 1",
		"IPT_08_8": "Le condizioni di monitoraggio del sensore O2 rilevate contano il banco 1",
		"IPT_08_9": "Il completamento del monitoraggio del sensore O2 conta il banco 2",
		"IPT_08_10": "Le condizioni di monitoraggio del sensore O2 rilevate contano il banco 2",
		"IPT_08_11": "Conteggi delle condizioni di completamento del monitoraggio EGR e/o VVT",
		"IPT_08_12": "Conteggi delle condizioni di monitoraggio EGR e/o VVT incontrate",
		"IPT_08_13": "Conteggi delle condizioni di completamento del monitoraggio AIR (aria secondaria)",
		"IPT_08_14": "Conteggi delle condizioni di monitoraggio AIR incontrate (aria secondaria)",
		"IPT_08_15": "Conteggi delle condizioni di completamento del monitoraggio EVAP",
		"IPT_08_16": "Conteggi rilevati dalle condizioni di monitoraggio EVAP",
		"IPT_08_17": "Il completamento del monitoraggio del sensore O2 secondario conta il banco 1",
		"IPT_08_18": "Le condizioni di monitoraggio del sensore O2 secondario rilevate contano il banco 1",
		"IPT_08_19": "Il completamento del monitoraggio del sensore O2 secondario conta il banco 2",
		"IPT_08_20": "Le condizioni di monitoraggio del sensore O2 secondario rilevate contano il banco 2",

		"IPT_08_des_1": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio OBD specificate (denominatore generale).",
		"IPT_08_des_2": "mostra il conteggio del numero di volte in cui il motore è stato avviato.",
		"IPT_08_des_3": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del banco 1 del sistema catalizzatore (numeratore).",
		"IPT_08_des_4": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del catalizzatore specificate (denominatore).",
		"IPT_08_des_5": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del banco 2 del sistema catalizzatore (numeratore).",
		"IPT_08_des_6": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del catalizzatore specificate (denominatore).",
		"IPT_08_des_7": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del banco di sensori di ossigeno 1 (numeratore).",
		"IPT_08_des_8": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sensore di ossigeno specificate (denominatore).",
		"IPT_08_des_9": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del banco di sensori di ossigeno 2 (numeratore).",
		"IPT_08_des_10": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sensore di ossigeno specificate (denominatore).",
		"IPT_08_des_11": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema EGR/VVT (numeratore).",
		"IPT_08_des_12": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sistema EGR/VVT specificate (denominatore).",
		"IPT_08_des_13": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema AIR (numeratore).",
		"IPT_08_des_14": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sistema AIR specificate (denominatore).",
		"IPT_08_des_15": "visualizza il numero di volte in cui si sono verificate (numeratore) tutte le condizioni necessarie per rilevare un malfunzionamento della perdita del sistema EVAP di 0,020” (o 0,040” ).",
		"IPT_08_des_16": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del malfunzionamento delle perdite del sistema EVAP specificate (denominatore).",
		"IPT_08_des_17": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento della banca 1 del sensore di ossigeno secondario (numeratore).",
		"IPT_08_des_18": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sensore di ossigeno secondario specificate (denominatore).",
		"IPT_08_des_19": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del banco di sensori di ossigeno secondario 2 (numeratore).",
		"IPT_08_des_20": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sensore di ossigeno secondario specificate (denominatore).",

		"IPT_0B_1": "Conteggi rilevati dalle condizioni di monitoraggio OBD",
		"IPT_0B_2": "Contacicli di accensione",
		"IPT_0B_3": "Conteggi delle condizioni di completamento del monitoraggio del catalizzatore NMHC",
		"IPT_0B_4": "Conteggi riscontrati sulle condizioni di monitoraggio del catalizzatore NMHC",
		"IPT_0B_5": "Conteggi delle condizioni di completamento del monitoraggio del catalizzatore NOx/SCR",
		"IPT_0B_6": "Conteggi rilevati sulle condizioni del monitoraggio del catalizzatore NOx/SCR",
		"IPT_0B_7": "Conteggi delle condizioni di completamento del monitoraggio dell'adsorbitore di NOx",
		"IPT_0B_8": "Conteggi delle condizioni di monitoraggio dell'adsorbitore di NOx",
		"IPT_0B_9": "Conteggi delle condizioni di completamento del monitoraggio del filtro PM",
		"IPT_0B_10": "Conteggi rilevati dalle condizioni di monitoraggio del filtro PM",
		"IPT_0B_11": "Conteggi delle condizioni di completamento del monitoraggio del sensore di gas di scarico",
		"IPT_0B_12": "Conteggi di monitoraggio delle condizioni del sensore di gas di scarico",
		"IPT_0B_13": "Conteggi delle condizioni di completamento del monitoraggio EGR e/o VVT",
		"IPT_0B_14": "Conteggi delle condizioni di monitoraggio EGR e/o VVT incontrate",
		"IPT_0B_15": "Conteggi delle condizioni di completamento del monitoraggio della pressione di sovralimentazione",
		"IPT_0B_16": "Conteggi delle condizioni di monitoraggio della pressione di aumento",
		"IPT_0B_17": "Conteggi delle condizioni di completamento del monitoraggio del carburante",
		"IPT_0B_18": "Conteggi rilevati dalle condizioni di monitoraggio del carburante",

		"IPT_0B_des_1": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio OBD specificate (denominatore generale).",
		"IPT_0B_des_2": "mostra il conteggio del numero di volte in cui il motore è stato avviato.",
		"IPT_0B_des_3": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema catalizzatore NMHC (numeratore).",
		"IPT_0B_des_4": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del catalizzatore NMHC specificate (denominatore).",
		"IPT_0B_des_5": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema catalizzatore NOx (numeratore).",
		"IPT_0B_des_6": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del catalizzatore NOx specificate (denominatore).",
		"IPT_0B_des_7": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema adsorbitore di NOx (numeratore).",
		"IPT_0B_des_8": "visualizza il numero di volte in cui il veicolo è stato utilizzato nel denominatore delle condizioni di monitoraggio dell'adsorbitore di NOx specificato).",
		"IPT_0B_des_9": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema di filtri PM (numeratore).",
		"IPT_0B_des_10": "visualizza il numero di volte in cui il veicolo è stato utilizzato nel denominatore delle condizioni di monitoraggio del filtro PM specificato).",
		"IPT_0B_des_11": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sensore gas di scarico (numeratore)",
		"IPT_0B_des_12": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sensore dei gas di scarico specificate (denominatore).",
		"IPT_0B_des_13": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema EGR/VVT (numeratore).",
		"IPT_0B_des_14": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sistema EGR/VVT specificate (denominatore).",
		"IPT_0B_des_15": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema di pressione di sovralimentazione (numeratore).",
		"IPT_0B_des_16": "visualizza il numero di volte in cui il veicolo è stato azionato nelle condizioni di monitoraggio del sistema di pressione di sovralimentazione specificate (denominatore).",
		"IPT_0B_des_17": "visualizza il numero di volte in cui si sono verificate tutte le condizioni necessarie per rilevare un malfunzionamento del sistema di alimentazione (numeratore).",
		"IPT_0B_des_18": "visualizza il numero di volte in cui il veicolo è stato utilizzato nelle condizioni di monitoraggio del sistema di alimentazione specificate (denominatore).",
	}
}
