const i18n = {
	"mt": "Dzień",
	"xs": "Godziny",
	"fz": "Minuty",
	"wxts": "Porady",
	"zzjz": "ładowanie...",
	"noData": "BRAK DANYCH",
	"jchj" :"Sprawdzanie środowiska logowania",
	"ckfw": "Zakres odniesienia",
	"bbgl": {
		"bbts": "Przypomnienie o aktualizacji wersji",
		"official": "Wydano nowe funkcje, przejdź do oficjalnej strony internetowej, aby pobrać i zaktualizować najnowszą wersję.",
		"apple": "Wydano nowe funkcje, przejdź do App Store, aby pobrać uaktualnioną wersję.",
		"google": "Wydano nowe funkcje, przejdź do Google Play, aby pobrać uaktualnioną wersję."
	},
	"uds": {
	"uds0001": "Wybierz moduł",
	"uds0002": "Wybierz moduł do odczytu",
	"uds0003": "Lista zawiera wszystkie obsługiwane moduły wybranej marki, zaleca się wybranie tylko modułów już obecnych w samochodzie. Można jednak wybrać wszystkie moduły. System automatycznie wykryje moduły faktycznie obecne w samochodzie ",
	"uds0004": "Wybierz wszystko",
	"uds0005": "Anuluj zaznacz wszystko",
	"uds0006": "Rozpocznij diagnostykę",
	"uds0007": "Niestandardowy dostawca"
	},
	"yjdl": {
		"yxdl": "Logowanie przez e-mail",
		"dlts": "Najpierw wprowadź graficzną Captcha, a następnie odbierz Captcha e-mail",
		"sryx": "Podaj swój adres e-mail",
		"sryzm": "Proszę wpisać captcha",
		"xyb": "Dalej",
		"xgyx": "Zmodyfikuj skrzynkę pocztową",
		"yxdz": "Adres e-mail",
		"fsyzm": "wyślij kod dostępu na email",
		"yzm": "Kod dostępu",
		"cxfs": "sekundy do ponownego wysłania",
		"dl": "Zaloguj się",
		"srtxyzm": "Wpisz lewą graficzną Captcha",
		"yxbzq": "E-mail jest nieprawidłowy",
		"txyzmbzq": "Grafika Captcha jest nieprawidłowa",
		"fsdx": "Wysyłanie captcha",
		"yxyzmfscg": "E-mail Captcha został pomyślnie wysłany",
		"yxbky": "Wysyłanie wiadomości e-mail jest nieprawidłowe! Sprawdź, czy adres e-mail został wprowadzony poprawnie i czy wiadomość e-mail może zostać odebrana normalnie.",
		"zzyz": "Weryfikacja",
		"yzmcw": "E-mail Captcha jest nieprawidłowy",
		"clxxgl": "Zarządzanie informacjami o pojeździe",
		"gxxx": "Informacje o aktualizacji",
		"dlcg": "Logowanie powiodło się",
		"dlsb": "Logowanie nie powiodło się",
		"clxx": "Informacje o pojeździe",
		"czxx": "Informacje o właścicielu samochodu",
		"wdl": "Nie zalogowany",
		"cl": "Pojazd"
	},
	
	"OBDxncs": {
		"bt": "Porównanie adapterów",
		"fbt": "większy oznacza szybszy",
		"zjsd": "Optymalna prędkość",
		"dqsd": "Obecna prędkość",
		"xzmc": "Szybkość, z jaką parametry są odczytywane z ECU na sekundę (jednostka: parametry/sekundę)",
		"sec_dt": "Testowano z Galaxy Note 8 i Pixel 2",
		"sec_dd1": "(1) Adaptery Wi-Fi generalnie nie są zalecane dla Androida, ponieważ większość telefonów traci połączenie transmisji danych z Internetem podczas użytkowania.",
		"sec_dd2": "(2) Wszystkie testowane adaptery to standard Bluetooth, chyba że częścią ich nazwy jest 'WiFi', 'USB' lub 'BLE'",
		"text2": "Porównanie OBD"
	},
	
	"tsxx": {
		"qxz": "wybierz",
		"qsr": "Proszę wprowadzić",
		"qqr": "Potwierdź",
		"qqx": "Anuluj",
		"notConnected": "Najpierw podłącz swoje urządzenie",
		"save": "Zapisz formularz pomyślnie.",
		"dsyh": "Zużycie paliwa na biegu jałowym odnosi się do zużycia paliwa w bieżącej chwili, gdy pojazd jest nieruchomy, z czasem jako jednostką statystyczną.",
		"xsyh": "Zużycie paliwa podczas jazdy odnosi się do zużycia paliwa w bieżącym momencie, gdy pojazd jest w stanie jazdy, a odległość jest jednostką statystyczną.",
		"pjyh": "Średnie zużycie paliwa odnosi się do zużycia paliwa na 100 kilometrów pojazdu podczas tego procesu jazdy i jest wyświetlane dopiero po przejechaniu więcej niż 1 km.",
		"cqyh": "Długoterminowe zużycie paliwa odnosi się do zużycia paliwa przez pojazd na 100 kilometrów podczas działania aplikacji.",
		"yhsupport": "Ten samochód nie obsługuje wskaźnika zużycia paliwa",
		"cg": "sukces",
		"noTrouble": "Gratulacje, Twój samochód jest bezawaryjny, tak trzymaj.",
		"noVin": "Wprowadź 17-cyfrowy numer ramy, abyśmy mogli zapewnić Ci lepszą obsługę.",
		"gzzsd": "MIL to skrót od Lampka wskaźnika awarii. Gdy lampka MIL się świeci, oznacza to, że układ silnika może działać nieprawidłowo. Przyczyną świecenia się kontrolki MIL może być zbyt duże osadzanie się węgla wewnątrz zawór dławiący lub silnik lub stosunek mieszanki jest niezrównoważony po awarii czujnika tlenu lub świeci się kontrolka silnika z powodu złej jakości benzyny i niewystarczającego spalania pojazdu.",
		"noDevelopment": "W trakcie opracowywania, bądź na bieżąco.",
		"zc": "Obecnie dostępne do testowania",
		"noSupport": "Obecnie niedostępne do testowania",
		"noNetwork": "Twoja sieć jest obecnie niedostępna. Żadna sieć nie wpłynie na Twoje wrażenia.",
		"jy": "Wyłączone",
		"ywc": "Test stanu zakończony",
		"noCompelte": "Test statusu nie został zakończony",
		"noSupportPid": "Twój pojazd nie ma tego testu!",
		"useReminders": "Przypomnienie: Po wstrzymaniu możesz powiększać lub wędrować, przesuwając palcem po suwaku lub ekranie dotykowym.",
		"noCompelteDes": "Jeśli stan gotowości można przetestować, ale nie można go ukończyć, można podjąć następujące działania pozycja po pozycji: pełna jazda, konserwacja pojazdu, czyszczenie zespołu, aktualizacja ECU itp. Mamy nadzieję, że proces jazdy będzie w przyszłości eksploatowany zgodnie ze specyfikacjami i prowadzona będzie regularna konserwacja.",
		"fgf": "Ta funkcja jest dostępna wyłącznie w oficjalnych produktach, użyj jej po zakupie!",
		"b25": "Ta funkcja jest dostępna wyłącznie dla B25, użyj jej po zakupie!"
	},
	
	"pid": {
		"dsyh": "Zużycie paliwa na biegu jałowym",
		"xsyh": "Zużycie paliwa",
		"ssyh": "Średnie zużycie",
		"pjyh": "Natychmiastowa konsumpcja",
		"cqyh": "Długoterminowe zużycie paliwa",
		"pjsd": "Średnia prędkość",
		"xslc": "Przebyta odległość",
		"DTC_legnth":"Liczba kodów DTC zapisanych w tym ECU",
		"MIL": "Stan lampki kontrolnej usterki",
		"mil_0": "światło wyłączone",
		"mil_1": "światło włączone",
		"shxt": "Monitorowanie przerw w zapłonie",
		"ryxt": "Monitorowanie układu paliwowego",
		"zhzj": "Kompleksowe monitorowanie komponentów",
		
		"fdjlx": "Typ silnika",
		"ysfdj": "zapłon samoczynny",
		"dhfdj": "zapłon iskrowy",
		"chj": "Monitorowanie katalizatora",
		"jrchj": "Monitorowanie podgrzewanego katalizatora",
		"zfxt": "Monitorowanie układu wyparnego",
		"eckqxt": "Monitorowanie układu powietrza wtórnego",
		"ktxtzlj": "Monitorowanie czynnika chłodniczego układu klimatyzacji",
		"ycgqjrq": "Monitorowanie grzałki czujnika tlenu",
		"ycgqjk": "Monitorowanie czujnika tlenu",
		"erg": "Monitorowanie systemu EGR/VVT",
		"NMHC": "Monitorowanie katalizatora NMHC",
		"NOx": "Monitorowanie NOx/SCR",
		"yl": "Zarezerwowany",
		"zyyl": "Monitorowanie ciśnienia doładowania",
		"fqcgq": "Monitorowanie czujnika spalin",
		"pmglq": "Monitorowanie monitora filtra PM"
	},

	"sygl": {
		"xieyi": "Protokół",
		"tips1": "Podłącz urządzenie",
		"tips2": "Proszę włączyć Bluetooth! Zobacz pomoc",
		"tips3": "Nie możesz znaleźć urządzenia? Wyświetl pomoc",
		"tips4": "Proszę włączyć usługi lokalizacyjne",
		"tips5": " Uniwersalne",
		"tips6": " Wersja ekonomiczna",
		"sdlj": "Ręcznie wybierz połączenie"
	},
	
	"djz": {
		"noData": "Obecnie nie ma zamrożonych danych",
		"previousFrame": "Poprzednia klatka",
		"nextFrame": "Następna klatka"
	},
	
	"fwgl": {
		"ybp": "Pulpit nawigacyjny",
		"UDS": "Ujednolicona usługa diagnostyczna (test)",
		"UDS_des": "Zapewnij zunifikowaną usługę diagnostyczną pojazdu, więcej ECU i więcej funkcji",
		"DTC": "Monitorowanie DTC",
		"DTC_des": "Zapewnij profesjonalne rozwiązania dla kodów usterek pojazdów",
		"xcfx": "Analiza podróży",
		"xcfx_des": "Analizuj dane każdej podróży",
		"xncs": "Badanie wydajności pojazdu",
		"xncs_des": "Dostarcz profesjonalny raport z analizy wydajności pojazdu",
		"sssjl": "strumień danych w czasie rzeczywistym",
		"sssjl_des": "Poproś o aktualne dane diagnostyczne układu napędowego",
		"gzzsd": "Wykrywanie wskaźnika błędu",
		"gzzsd_des": "Dostarcza informacje o działaniu pojazdu po włączeniu lub wyłączeniu kontrolki usterki",
		
		"pid0141": "Stan gotowości diagnostycznej",
		"pid0141_des": "Zapewnia stan monitorowania pojazdu od czasu wykasowania DTC oraz aktualny status działania monitora cyklu jazdy",
		"$05": "Wyniki monitorowania czujnika tlenu",
		"$05_des": "Odczytaj wyniki testu monitorowania czujnika tlenu w pojeździe",
		"$06": "Konkretne wyniki monitorowania",
		"$06_des": "zezwalaj na dostęp do wyników testów monitorowania diagnostyki pokładowej dla określonych komponentów/systemów.",
		"$09": "Informacje o pojeździe",
		"$09_des": "Przeczytaj informacje o pojeździe i informacje o pojeździe",
		
		"clnj": "",
		"clnj_des": "",
		
		"obdTest": "Test wydajności OBD",
		"obdTest_des": "Przetestuj różne wskaźniki wydajności OBD za pomocą zautomatyzowanych narzędzi testujących.",
		"djz": "Zatrzymaj klatkę",
		"djz_des": "Kiedy DTC pojawia się w układzie wydechowym, ECU zapisuje dane, gdy pojawia się DTC",
		"yjjc": "Wykrywanie pełnego pojazdu jednym kliknięciem",
		"yjjc_des": "Kompleksowe wykrywanie wszystkich danych z czujników pojazdu, informacji o pojeździe, kodów usterek, stopklatek i informacji o monitorowaniu pojazdu."
	},
	
	"yjjc": {
		"cljkxx": "informacje o monitorowaniu pojazdu",
		"xx_09": "Wykrywanie informacji o pojeździe",
		"xx_03": "Wykrywanie informacji o usterce",
		"xx_01": "Wykrywanie informacji o monitorowaniu pojazdu",
		"xx_02": "Wykrywanie informacji o stopklatce",
		"xx_05": "Wykrywanie informacji z czujnika tlenu",
		"xx_06": "Odczyt konkretnych informacji o wynikach monitorowania"
	},
	
	"ybpgl":{
		"dcdy": "Napięcie baterii",
		"xhyb": "Licznik rejsu",
		"yhyb": "Licznik zużycia paliwa",
		"zdyyb": "Licznik niestandardowy",
		"xz": "Dodaj pulpit nawigacyjny",
		"bj": "Edytuj pulpit nawigacyjny",
		"sc": "Usuń pulpit nawigacyjny",
		"delete_tips": "Czy na pewno chcesz usunąć pulpit nawigacyjny?"
	},
	
		
	"status": {
		"1000": "Bluetooth nie jest włączony",
		"1001": "Bluetooth jest wyłączony",
		"1002": "Oczekiwanie na oszczędność paliwa",
		"1003": "Wyszukiwanie OBD",
		"1004": "Podłączanie OBD",
		"1005": "Bluetooth jest podłączony",
		"1006": "udało się zapisać dane",
		"1007": "Zapis danych nie powiódł się",
		"1008": "Włącz powiadomienie pomyślnie",
		"1009": "Nie znaleziono urządzenia"
	},

  
	"szgl": {
		"bt": "Ustawienia",
		"label1": "Język",
		"value1": "Podążaj za systemem",
		"label2": "Polityka prywatności",
		"label3": "Pomoc dotycząca połączenia",
		"label4": "O",
		"label5": "Oficjalne centrum handlowe",
		"value5": "Centrum handlowe 1688",
		"label6": "Wersja",
		"cjwt": "Powszechny problem",
		"unittitle": "Jednostka",
		"unitvalue1": "System metryczny",
		"unitvalue2": "Jednostki imperialne",
		"unitinfo": "Potwierdź, czy zmienić jednostki?"
	},

	"yygl": {
		"label": "Podążaj za systemem",
		"des": "Po włączeniu zostanie automatycznie ustawiony zgodnie z językiem systemu",
		"en": "angielski",
		"zh": "Chiński uproszczony",
		"zwft": "Chiński tradycyjny",
		"es": "hiszpański",
		"kr": "koreański",
		"ru": "rosyjski",
		"ja": "japoński",
		"it": "włoski",
		"hi": "hindi",
		"pt": "portugalski",
		"de": "niemiecki",
		"fr": "francuski",
		"nl": "holenderski",
		"fi": "fiński",
		"pl": "polski",
		"bn": "bengalski"
	},

	
	"obdManage": {
		"bt": "Zarządzanie OBD",
		"search_tip": "Wyszukaj ponownie lub kup nasze produkty",
		"buy_tip": "Idź do centrum handlowego, aby kupić",
		"searchAgain": "Wyszukaj ponownie",
		"nearBy": "Sprzęt w pobliżu",
		"ls": "Wyposażenie historyczne",
		"bz": "Wyświetl pomoc",
		"del": "Usuń",
		"delConfirm": "Czy na pewno chcesz usunąć ten rekord?",
		"switched": "Urządzenie ma zostać przełączone, czy na pewno?",
		"qrxx": "Potwierdź, że przełącznik Bluetooth i informacji o lokalizacji w telefonie komórkowym jest włączony.",
		"searchAgain_message": "Czy na pewno chcesz ponownie wyszukać pobliskie urządzenia?"
	},

	
"gzjc": {
		"bt": "Diagnostyka",
		"btn": "Rozpocznij testowanie",
		"des": "Rozpocznij pełne skanowanie pojazdu",
		"FaultCodeQuery": "Zapytanie o kod błędu",
		"zzjc": "Testowanie",
		"clearFaultCode": "Wyczyść kod błędu",
		"kscz": "szukaj",
		"fxgz": "Znaleziono kod błędu",
		"notFound": "nie znaleziono problemów",
		"cxjc": "Sprawdź ponownie",
		"modalTitle": "Czy na pewno chcesz usunąć kod błędu?",
		"modalContent": "Zanim usunie się usterkę, zaleca się, aby nie kasować kodu usterki do woli. Większość ECU nie pozwala na skasowanie kodu usterki podczas pracy silnika. To, czy kod usterki można skasować, czy nie, jest ostatecznie określony przez ECU. Usuwanie kodów usterek nie jest tak naprawdę rozwiązaniem problemu.",
		"sdjc": "Raport z inspekcji głębokości",
		"num": "Liczba kodów usterek",
		"gzmxx": "Szczegóły kodu błędu",
		"label1": "kategoria",
		"label2": "Wyjaśnienie kodu błędu",
		"definition_03": "Diagnostyczne kody usterek",
		"definition_07": "Oczekujące diagnostyczne kody usterek",
		"definition_0A": "Stałe diagnostyczne kody usterek",
		"03_des": "Gdy ECU (jednostka sterująca pojazdu) wykryje nieprawidłowość, w pamięci zapisywany jest kod usterki. Ten kod usterki odnosi się do nienormalnej sytuacji wykrytej podczas ostatniego procesu jazdy. Te kody usterek są przechowywane w pamięci przez okres czasu, gdy kod błędu zostanie ponownie znaleziony, zaktualizuj okres przechowywania.",
		"07_des": "Jest to niepotwierdzona anomalia podczas jazdy. Jeśli anomalia powtórzy się i zostanie zidentyfikowana, tymczasowy kod usterki zostanie sklasyfikowany jako kod potwierdzonej usterki. Jeśli nie zostanie zapisany, zostanie usunięty po wyłączeniu silnika." ,
		"0A_des": "Ponieważ pokazuje historię poprzednich kodów DTC, nie przedstawia aktualnego stanu pojazdu. Może nie być możliwe programowe usunięcie odpowiednich kodów DTC.",
		"sys_P": "Układ napędowy (zdefiniowany przez producenta)",
		"sys_B": "System nadwozia (zdefiniowany przez producenta)",
		"sys_C": "System zawieszenia podwozia (zdefiniowany przez producenta)",
		"sys_U": "System komunikacji sieciowej (zdefiniowany przez producenta)",
		"zzs": "Wszyscy producenci samochodów"
	},

	"clgl": {
		"bt": "Mój samochód",
		"info1": "Podstawowe informacje o samochodzie",
		"clpp": "Marki samochodów",
		"xh": "Model samochodu",
		"nk": "Rok",
		"rylx": "Rodzaj paliwa",
		"info2": "Inne informacje o pojeździe",
		"atdp": "Protokół komunikacyjny",
		"ati": "Wersja adaptera",
		"vin": "Numer identyfikacyjny pojazdu",
		"cid": "Identyfikatory kalibracji",
		"cvn": "Numery weryfikacyjne kalibracji",
		"ecu": "Elektroniczna Jednostka Sterująca",
		"ESN": "Numer seryjny silnika",
		"EROTAN": "Regulamin wydechowy lub numer homologacji typu",
		"FEOCNTR": "Licznik cykli zapłonu pracy silnika zasilanego paliwem",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Proszę wpisać markę pojazdu",
		"warn2": "wymagany jest model samochodu",
		"warn3": "wymagany jest rok samochodu",
		"warn4": "vin jest wymagany",
		"warn5": "Proszę podać poprawny numer identyfikacyjny pojazdu",
		"warn6": "wymagana jest nazwa właściciela samochodu",
		"warn7": "telefon jest wymagany",
		"warn8": "Proszę wprowadzić poprawny telefon",
		"warn9": "Wprowadź poprawny adres e-mail",
		"bt": "Połączenie OBD powiodło się",
		"title_sub": "Poniższe informacje są bardzo ważne dla dokładnej diagnozy, aby poprawić Twoje wrażenia. Pamiętaj, aby dokładnie wypełnić.",
		"ts_vin": "Lokalizacja kodu VIN: zazwyczaj znajduje się po lewej stronie tablicy rozdzielczej, w lewym dolnym rogu przedniej szyby; znajduje się tam również kolumna zawiasu drzwi, kolumna zamka drzwi lub jedna z kolumn połączonych z kolumna zamka drzwi lub drzwi w pobliżu siedzenia kierowcy wewnątrz.",
		"vin": "Vin",
		"czxm": "Nazwa",
		"lxdh": "Telefon",
		"lxyx": "E-mail"
	},
	"ota": {
		"bt": "Aktualizacja OTA",
		"jcdxbb": "Wykryto nową wersję oprogramowania układowego",
		"gxnr": "Zaktualizuj zawartość",
		"fxsm": "Instrukcje aktualizacji",
		"fxsm_des": "Aktualizacja OTA (technologia bezprzewodowa) oznacza, że terminal mobilny zdalnie pobiera pakiet aktualizacji na serwer w celu aktualizacji oprogramowania układowego OBD. Aktualizacja nie wpłynie na Twój pojazd i bezpieczeństwo jazdy, zachęcamy do korzystania Jeśli pojawi się monit, że aktualizacja się nie powiodła, nie wychodź z interfejsu, ponownie włóż OBD i kontynuuj aktualizację.",
		"zysx": "Ostrzeżenie",
		"zysx_des": "Nie aktualizuj podczas jazdy i nie usuwaj ani nie wyłączaj OBD podczas aktualizacji.",
		"mssj": "Uaktualnij teraz",
		"kssj": "Rozpocznij aktualizację",
		"sjcg": "Aktualizacja OTA powiodła się",
		"kqqxty": "Otwórz nowe doświadczenie",
		"xzgj": "Pobierz oprogramowanie układowe",
		"zzxr": "Pisanie",
		"zzsj": "Aktualizacja",
		"zzjy": "Weryfikacja integralności",
		"sjsb": "Aktualizacja nie powiodła się, spróbuj ponownie"
	},

	"xcfx": {
		"ksxc": "Rozpocznij podróż",
		"jsxc": "Zakończ podróż",
		"lsjl": "Rekord historii",
		"zlc": "Całkowity przebieg",
		"hs": "Czasochłonny",
		"kssj": "Czas rozpoczęcia",
		"zyh": "Całkowita liczba litrów"
	},

	"xncs": {
		"jsxn": "Przyspieszony",
		"scxn": "Hamowanie",
		"jlxn": "Odległość",
		"des1": "Zakres testu prędkości",
		"des2": "prędkość podczas hamowania",
		"des3": "odległość testowa",
		"aqtx": "proszę zwrócić uwagę na bezpieczeństwo jazdy!",
		"kscs": "Rozpocznij testowanie",
		"cxcs": "Przetestuj ponownie",
		"tz": "Zatrzymaj się",
		"tip1": "Dostosuj prędkość pojazdu do",
		"tip2": "Naciśnij pedał przyspieszenia, aby przyspieszyć",
		"tip2_end": "Powyżej",
		"tip3": "Naciśnij hamulec, aby zmniejszyć prędkość do",
		"tip4": "Proszę jechać",
		"tip5": "Podróżował",
		"max_sd": "Prędkość maksymalna",
		"max_jsd": "Maksymalne przyspieszenie",
		"max_zs": "Maksymalna prędkość",
		"tx1": "Prędkość początkowa nie może być większa niż prędkość końcowa",
		"tx2": "Proszę wpisać prędkość hamowania większą niż 0",
		"tx3": "Proszę wpisać odległość testową większą niż 0"
	},

	"bzxx": {
		"title1": "Krok 1: Uruchom pojazd",
		"title2": "Krok 2: Podłącz urządzenie",
		"title3": "Krok 3: Włącz Bluetooth i lokalizację",
		"title4": "Krok 4: Otwórz aplikację",
		"title5": "Krok 5: Podłącz urządzenie",
		"text1": "Znajdź lokalizację interfejsu OBD pojazdu. Interfejs OBD to 16-pinowy żeński interfejs. Interfejs ma kształt trapezu. Niektóre modele mają osłonę interfejsu OBD. Typowe porty OBD są czarne, białe lub niebieskie. Umiejscowienie to zazwyczaj w tapicerce wnętrza pod kierownicą, w pobliżu kolan kierowcy. Umiejscowienie interfejsu OBD może być różne dla różnych modeli i modeli. Poniższy rysunek przedstawia możliwe umiejscowienie interfejsu OBD:",
		"text2": "Po znalezieniu interfejsu OBD, podłącz urządzenie do interfejsu OBD. Upewnij się, że jest podłączone do końca (wiele samochodów jest podłączonych mniej więcej w połowie i zasilanie jest włączone, ale piny sygnałowe mogą nie być podłączony), a czerwony wskaźnik zasilania lub ekran jest włączony.",
		"text3": "Włącz Bluetooth i przełączniki lokalizacji w telefonie. Metoda: Przesuń palcem w dół na górze ekranu telefonu, otwórz menu skrótów i kliknij Bluetooth i informacje o lokalizacji. Włącz Bluetooth na swoim urządzeniu iOS.",
		"text4": "Otwórz aplikację i zezwól aplikacji na korzystanie z informacji o lokalizacji.",
		"text5": "Po wykonaniu powyższych kroków, wejdź do APP, APP automatycznie przeskanuje urządzenie OBD i zapyta, czy podłączyć urządzenie. Urządzenie iOS zapyta, czy zezwolić na dostęp do adresu, kliknij Zezwól.",
		"text6": "Wybierz urządzenie do podłączenia i kliknij, aby się połączyć. Po pomyślnym nawiązaniu połączenia strona główna aplikacji wyświetli nazwę urządzenia OBD, adres Bluetooth, a na desce rozdzielczej pojawi się odczyt."
	},
	
	"06fw": {
		"MID": "Nazwa monitora",
		"TID": "Nazwa testu",
		"CID": "Numer komponentu",
		"O2Sensor": "Nazwa czujnika O2",
		"MIN": "Minimalny limit",
		"MAX": "Maksymalny limit",
		"CURRENT": "Wartość testowa"
	},
	
	"09fw": {
		"ipt": "Śledzenie wydajności w użyciu",
		"IPT_08_1": "Liczba napotkanych warunków monitorowania OBD",
		"IPT_08_2": "Licznik cykli zapłonu",
		"IPT_08_3": "Bank 1 zlicza ukończenie monitora Catalyst",
		"IPT_08_4": "Napotkane warunki monitora katalizatora liczą się w banku 1",
		"IPT_08_5": "Bank 2 zlicza ukończenie monitora Catalyst",
		"IPT_08_6": "Napotkane warunki monitora katalizatora liczą się w banku 2",
		"IPT_08_7": "Bank 1 liczników ukończenia monitora czujnika O2",
		"IPT_08_8": "Napotkane zliczenia warunków monitora czujnika O2, bank 1",
		"IPT_08_9": "Bank 2 liczników ukończenia monitora czujnika O2",
		"IPT_08_10": "Warunki monitorowania czujnika O2 Napotkane zliczenia Bank 2",
		"IPT_08_11": "Zliczanie warunków ukończenia monitora EGR i/lub VVT",
		"IPT_08_12": "Liczba napotkanych warunków monitora EGR i/lub VVT",
		"IPT_08_13": "Liczy się warunek ukończenia monitora AIR (powietrze wtórne)",
		"IPT_08_14": "Liczba napotkanych warunków monitorowania powietrza (powietrze wtórne)",
		"IPT_08_15": "Liczba warunków ukończenia monitora EVAP",
		"IPT_08_16": "Liczba napotkanych warunków monitora EVAP",
		"IPT_08_17": "Bank 1 liczników ukończenia monitora wtórnego czujnika O2",
		"IPT_08_18": "Napotkane stany monitora dodatkowego czujnika O2 Bank 1",
		"IPT_08_19": "Bank 2 liczników ukończenia monitora wtórnego czujnika O2",
		"IPT_08_20": "Napotkane warunki monitora dodatkowego czujnika O2 Bank 2",
		
		"IPT_08_des_1": "wyświetla liczbę przypadków eksploatacji pojazdu w określonych warunkach monitorowania OBD (ogólny mianownik).",
		"IPT_08_des_2": "wyświetla liczbę uruchomień silnika.",
		"IPT_08_des_3": "wyświetla liczbę przypadków napotkania wszystkich warunków niezbędnych do wykrycia nieprawidłowego działania banku 1 układu katalizatora (licznik).",
		"IPT_08_des_4": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania katalizatora (mianownik).",
		"IPT_08_des_5": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia nieprawidłowego działania banku 2 układu katalizatora (licznik).",
		"IPT_08_des_6": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania katalizatora (mianownik).",
		"IPT_08_des_7": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia nieprawidłowego działania banku 1 sondy lambda (licznik).",
		"IPT_08_des_8": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania sondy lambda (mianownik).",
		"IPT_08_des_9": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia nieprawidłowego działania banku 2 sondy lambda (licznik).",
		"IPT_08_des_10": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania sondy lambda (mianownik).",
		"IPT_08_des_11": "wyświetla liczbę wystąpień wszystkich warunków niezbędnych do wykrycia usterki układu EGR/VVT (licznik).",
		"IPT_08_des_12": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania układu EGR/VVT (mianownik).",
		"IPT_08_des_13": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia awarii systemu AIR (licznik).",
		"IPT_08_des_14": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania systemu AIR (mianownik).",
		"IPT_08_des_15": "wyświetla, ile razy wystąpiły wszystkie warunki niezbędne do wykrycia usterki nieszczelności układu EVAP 0,020” (lub 0,040”) (licznik).",
		"IPT_08_des_16": "wyświetla liczbę przypadków eksploatacji pojazdu w określonych warunkach monitorowania nieprawidłowego działania układu EVAP (w mianowniku).",
		"IPT_08_des_17": "wyświetla liczbę przypadków, w których wszystkie warunki niezbędne do wykrycia nieprawidłowego działania banku 1 wtórnego czujnika tlenu zostały napotkane (licznik).",
		"IPT_08_des_18": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania wtórnej sondy lambda (mianownik).",
		"IPT_08_des_19": "wyświetla liczbę przypadków napotkania wszystkich warunków niezbędnych do wykrycia nieprawidłowego działania banku 2 wtórnego czujnika tlenu (licznik).",
		"IPT_08_des_20": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania wtórnej sondy lambda (mianownik).",
		
		"IPT_0B_1": "Liczba napotkanych warunków monitorowania OBD",
		"IPT_0B_2": "Licznik cykli zapłonu",
		"IPT_0B_3": "Liczy się warunek ukończenia monitorowania katalizatora NMHC",
		"IPT_0B_4": "Liczba napotkanych warunków monitora katalizatora NMHC",
		"IPT_0B_5": "Zliczanie warunków ukończenia monitorowania katalizatora NOx/SCR",
		"IPT_0B_6": "Liczba napotkanych warunków monitorowania katalizatora NOx/SCR",
		"IPT_0B_7": "Zliczanie warunków ukończenia monitora adsorbera NOx",
		"IPT_0B_8": "Liczba napotkanych warunków monitorowania adsorbera NOx",
		"IPT_0B_9": "Liczba warunków ukończenia monitorowania filtra PM",
		"IPT_0B_10": "Liczba napotkanych warunków monitorowania filtra PM",
		"IPT_0B_11": "Liczy się warunek ukończenia monitora czujnika spalin",
		"IPT_0B_12": "Liczba napotkanych warunków monitora czujnika spalin",
		"IPT_0B_13": "Zliczanie warunków ukończenia monitora EGR i/lub VVT",
		"IPT_0B_14": "Liczba napotkanych warunków monitora EGR i/lub VVT",
		"IPT_0B_15": "Liczy się warunek ukończenia monitora ciśnienia doładowania",
		"IPT_0B_16": "Liczba napotkanych warunków monitora ciśnienia doładowania",
		"IPT_0B_17": "Liczy się warunek ukończenia monitorowania paliwa",
		"IPT_0B_18": "Liczba napotkanych warunków monitorowania paliwa",
		
		"IPT_0B_des_1": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania OBD (ogólny mianownik).",
		"IPT_0B_des_2": "wyświetla liczbę uruchomień silnika.",
		"IPT_0B_des_3": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia nieprawidłowego działania układu katalizatora NMHC (licznik).",
		"IPT_0B_des_4": "wyświetla liczbę przypadków eksploatacji pojazdu w określonych warunkach monitorowania katalizatora NMHC (mianownik).",
		"IPT_0B_des_5": "wyświetla, ile razy wystąpiły wszystkie warunki niezbędne do wykrycia nieprawidłowego działania układu katalizatora NOx (licznik).",
		"IPT_0B_des_6": "wyświetla liczbę przypadków eksploatacji pojazdu w określonych warunkach monitorowania katalizatora NOx (mianownik).",
		"IPT_0B_des_7": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia nieprawidłowego działania układu adsorbera NOx (licznik).",
		"IPT_0B_des_8": "wyświetla, ile razy pojazd był eksploatowany w określonych mianowniku warunków monitorowania adsorbera NOx).",
		"IPT_0B_des_9": "wyświetla, ile razy zostały napotkane wszystkie warunki niezbędne do wykrycia awarii systemu filtra cząstek stałych (licznik).",
		"IPT_0B_des_10": "wyświetla, ile razy pojazd był eksploatowany w określonym mianowniku warunków monitorowania filtra cząstek stałych).",
		"IPT_0B_des_11": "wyświetla ile razy wystąpiły wszystkie warunki niezbędne do wykrycia usterki czujnika spalin (licznik)",
		"IPT_0B_des_12": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania czujnika spalin (mianownik).",
		"IPT_0B_des_13": "wyświetla, ile razy wystąpiły wszystkie warunki niezbędne do wykrycia usterki układu EGR/VVT (licznik).",
		"IPT_0B_des_14": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania układu EGR/VVT (mianownik).",
		"IPT_0B_des_15": "wyświetla, ile razy wystąpiły wszystkie warunki niezbędne do wykrycia nieprawidłowego działania układu ciśnienia doładowania (licznik).",
		"IPT_0B_des_16": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania układu ciśnienia doładowania (mianownik).",
		"IPT_0B_des_17": "wyświetla liczbę wystąpień wszystkich warunków niezbędnych do wykrycia awarii układu paliwowego (licznik).",
		"IPT_0B_des_18": "wyświetla, ile razy pojazd był eksploatowany w określonych warunkach monitorowania układu paliwowego (mianownik)."
	}
}