// 瑞典语
var i18n = {
	"mt": "Dag",
	"xs": "Timmar",
	"fz": "Minuter",
	"wxts": "Tips",
	"zzjz": "laddar in...",
	"noData": "INGEN DATA",
	"jchj": "Kontrollerar inloggningsmiljön",
	"ckfw": "Referensintervall",
	"bbgl": {
		"bbts": "Påminnelse om versionsuppdatering",
		"official": "Det har släppts nya funktioner, gå till den officiella webbplatsen för att ladda ner och uppgradera den senaste versionen.",
		"apple": "Det finns nya funktioner släppta, gå till App Store för att ladda ner den uppgraderade versionen.",
		"google": "Det finns nya funktioner släppta, vänligen gå till Google Play för att ladda ner den uppgraderade versionen."
	},
	"uds": {
		"uds0001": "Välj modul",
		"uds0002": "Välj modul att läsa",
		"uds0003": "Listan innehåller alla moduler som stöds av det valda märket, det rekommenderas att endast välja de moduler som redan finns på bilen. Alla moduler kan dock väljas. Systemet kommer automatiskt att upptäcka de enheter som faktiskt finns på bilen .",
		"uds0004": "Välj alla",
		"uds0005": "Avbryt Markera alla",
		"uds0006": "Starta diagnos",
		"uds0007": "Anpassad leverantör"
	},
	"yjdl": {
		"yxdl": "E-postinloggning",
		"dlts": "Ange den grafiska Captcha först och få sedan e-postmeddelandet Captcha",
		"sryx": "Ange din e-postadress",
		"sryzm": "Vänligen ange Captcha",
		"xyb": "Nästa",
		"xgyx": "Ändra brevlåda",
		"yxdz": "E-postadress",
		"fsyzm": "skicka åtkomstkod till e-post",
		"yzm": "Åtkomstkod",
		"cxfs": "sekunder att skicka om",
		"dl": "Logga in",
		"srtxyzm": "Ange vänster grafisk Captcha",
		"yxbzq": "E-postadressen är felaktig",
		"txyzmbzq": "Den grafiska Captcha är felaktig",
		"fsdx": "Skicka Captcha",
		"yxyzmfscg": "E-post Captcha har skickats",
		"yxbky": "Att skicka e-post är onormalt! Kontrollera om e-postadressen har angetts korrekt och om e-postmeddelandet kan tas emot normalt.",
		"zzyz": "Verifierar",
		"yzmcw": "E-postmeddelandet Captcha är felaktigt",
		"clxxgl": "Fordonsinformationshantering",
		"gxxx": "Uppdatera information",
		"dlcg": "Inloggningen lyckades",
		"dlsb": "Inloggning misslyckades",
		"clxx": "Fordonsinformation",
		"czxx": "Information om bilägare",
		"wdl": "Inte inloggad",
		"cl": "Fordon"
	},

	"OBDxncs": {
		"bt": "Jämförelse av adaptrar",
		"fbt": "större betyder snabbare",
		"zjsd": "Optimal hastighet",
		"dqsd": "Aktuell hastighet",
		"xzmc": "Hastigheten med vilken parametrar läses från ECU per sekund (enhet: parametrar/sekund)",
		"sec_dt": "Testat med Galaxy Note 8 och Pixel 2",
		"sec_dd1": "(1) Wi-Fi-adaptrar rekommenderas i allmänhet inte för Android, eftersom de flesta telefoner förlorar sin dataanslutning till internet när de används.",
		"sec_dd2": "(2) Alla testade adaptrar är standard Bluetooth såvida inte 'WiFi', 'USB' eller 'BLE' är en del av deras namn",
		"text2": "Jämförelse av OBD"
	},

	"tsxx": {
		"qxz": "välj",
		"qsr": "Vänligen ange",
		"qqr": "Bekräfta",
		"qqx": "Avbryt",
		"notConnected": "Anslut din enhet först",
		"save": "Spara formuläret framgångsrikt.",
		"dsyh": "Tomgångsbränsleförbrukning avser bränsleförbrukningen i det aktuella ögonblicket när fordonet står stilla, med tiden som statistisk enhet.",
		"xsyh": "Körbränsleförbrukning avser bränsleförbrukningen i det aktuella ögonblicket när fordonet är i körtillstånd och tar avståndet som statistisk enhet.",
		"pjyh": "Den genomsnittliga bränsleförbrukningen avser bränsleförbrukningen per 100 kilometer av fordonet under denna körprocess, och den visas endast efter att ha kört mer än 1 km.",
		"cqyh": "Långsiktig bränsleförbrukning avser den bränsleförbrukning som fordonet förbrukar under 100 kilometer under driften av APP.",
		"yhsupport": "Denna bil stöder inte visning av bränsleförbrukning",
		"cg": "framgång",
		"noTrouble": "Grattis, din bil är felfri, fortsätt så.",
		"noVin": "Ange det 17-siffriga ramnumret så att vi kan ge dig bättre service.",
		"gzzsd": "MIL är en förkortning av Felfunktionsindikatorlampa. När MIL-lampan lyser betyder det att motorsystemet kan vara felaktigt. Anledningen till att MIL-lampan tänds kan vara att det finns för mycket kolavlagring inuti gasspjäll eller motorn, eller så är blandningsförhållandet ur balans efter att syrgassensorn misslyckas, eller motorlampan lyser på grund av bensinens dåliga bränslekvalitet och fordonets otillräckliga förbränning.",
		"noDevelopment": "Under utveckling, håll utkik. ",
		"zc": "För närvarande tillgänglig för testning",
		"noSupport": "För närvarande inte tillgänglig för testning",
		"noNetwork": "Ditt nätverk är för närvarande inte tillgängligt. Inget nätverk kommer att påverka din upplevelse.",
		"jy": "Inaktiverad",
		"ywc": "Statustest avslutat",
		"noCompelte": "Statustest inte avslutat",
		"noSupportPid": "Ditt fordon har inte detta test!",
		"useReminders": "Påminnelse: Efter paus kan du zooma eller roama genom att dra fingret på reglaget eller på pekskärmen.",
		"noCompelteDes": "Om redo-tillståndet kan testas men inte slutföras, kan följande åtgärder vidtas punkt för punkt: helt köra, underhålla fordonet, rengöra enheten, uppgradera ECU, etc. Förhoppningen är att körprocessen kommer att drivas i enlighet med specifikationerna i framtiden, och regelbundet underhåll kommer att utföras.",
		"fgf": "Denna funktion är exklusiv för officiella produkter, använd den efter köp!",
		"b25": "Denna funktion är exklusiv för B25, använd den efter köp!"
	},

	"pid": {
		"dsyh": "Tomgångsbränsleförbrukning",
		"xsyh": "bränsleförbrukning",
		"ssyh": "Genomsnittlig förbrukning",
		"pjyh": "Omedelbar konsumtion",
		"cqyh": "Långsiktig bränsleförbrukning",
		"pjsd": "Genomsnittlig hastighet",
		"xslc": "Kört avstånd",
		"DTC_legnth": "Antal felkoder lagrade i denna ECU",
		"MIL": "Felfunktionsindikatorlampans status",
		"mil_0": "ljus släckt",
		"mil_1": "ljus på",
		"shxt": "Felbrandövervakning",
		"ryxt": "Övervakning av bränslesystem",
		"zhzj": "Omfattande komponentövervakning",

		"fdjlx": "Motortyp",
		"ysfdj": "kompressionständning",
		"dhfdj": "gnisttändning",
		"chj": "Katalysatorövervakning",
		"jrchj": "Övervakning av uppvärmd katalysator",
		"zfxt": "Evaporativ systemövervakning",
		"eckqxt": "Sekundär luftsystemövervakning",
		"ktxtzlj": "A/C-systems köldmedieövervakning",
		"ycgqjrq": "Overvakning av syresensorvärmare",
		"ycgqjk": "Syrgassensorövervakning",
		"erg": "EGR/VVT-systemövervakning",
		"NMHC": "NMHC Katalysatorövervakning ",
		"NOx": "NOx/SCR-övervakning",
		"yl": "Reserverad",
		"zyyl": "Boosttrycksövervakning",
		"fqcgq": "Övervakning av avgassensor",
		"pmglq": "PM-filter Övervakning"
	},

	"sygl": {
		"xieyi": "Protokoll",
		"tips1": "Anslut enheten",
		"tips2": "Sätt på Bluetooth! Visa hjälp",
		"tips3": "Kan du inte hitta enheten? Se hjälp",
		"tips4": "Vänligen slå på platstjänster",
		"tips5": " Universal",
		"tips6": " Kostnadseffektiv version",
		"sdlj": "Välj en anslutning manuellt"
	},

	"djz": {
		"noData": "Det finns för närvarande inga frysta ramdata",
		"previousFrame": "Föregående ram",
		"nextFrame": "Nästa ram"
	},

	"fwgl": {
		"ybp": "Dashboard",
		"UDS": "Unified Diagnostic Service (Test)",
		"UDS_des": "Tillhandahålla enhetlig diagnostjänst för fordon, fler ECU:er och fler funktioner",
		"DTC": "DTC-övervakning",
		"DTC_des": "Tillhandahålla professionella lösningar för fordonsfelkoder",
		"xcfx": "Resanalys",
		"xcfx_des": "Analysera alla dina resedata",
		"xncs": "Tester av fordonsprestanda",
		"xncs_des": "Tillhandahålla en analysrapport för professionell fordonsprestanda",
		"sssjl": "dataström i realtid",
		"sssjl_des": "Begär aktuella diagnostiska data för drivlinan",
		"gzzsd": "Felindikatordetektering",
		"gzzsd_des": "Tillhandahåller information om fordonets drift efter att fellampan är på eller av",

		"pid0141": "Diagnostisk redo status",
		"pid0141_des": "Tillhandahåller fordonets övervakningsstatus sedan felkoden raderades och den aktuella körcykelövervakarens driftstatus",
		"$05": "Syrgassensorövervakningsresultat",
		"$05_des": "Läs testresultat av övervakning av fordonets syresensor",
		"$06": "Specifika övervakningsresultat",
		"$06_des": "tillåt åtkomst till resultaten av diagnostiska övervakningstester ombord för specifika komponenter/system.",
		"$09": "Fordonsinformation",
		"$09_des": "Läs fordonsspecifik fordonsinformation och info",

		"clnj": "",
		"clnj_des": "",

		"obdTest": "OBD-prestandatest",
		"obdTest_des": "Testa olika prestandaindikatorer för OBD genom automatiska testverktyg.",
		"djz": "Frysa ram",
		"djz_des": "När en felkod visas i avgassystemet, lagrar ECU data när felkoden visas",
		"yjjc": "Detektering av fullständig fordon med ett klick",
		"yjjc_des": "Omfattande detektering av alla fordonssensordata, fordonsinformation, felkoder, frysta ramar och fordonsövervakningsinformation."
	},

	"yjjc": {
		"cljkxx": "information om fordonsövervakning",
		"xx_09": "Detekterar fordonsinformation",
		"xx_03": "Detekterar felinformation",
		"xx_01": "Detekterar fordonsövervakningsinformation",
		"xx_02": "Detekterar frysbildsinformation",
		"xx_05": "Detekterar information om syrgassensor",
		"xx_06": "Läser specifik information om övervakningsresultat"
	},

	"ybpgl": {
		"dcdy": "Batterispänning",
		"xhyb": "Cruising Meter",
		"yhyb": "Bränsleförbrukningsmätare",
		"zdyyb": "Anpassad mätare",
		"xz": "Lägg till instrumentpanel",
		"bj": "Redigera instrumentpanel",
		"sc": "Ta bort instrumentpanel",
		"delete_tips": "Är du säker på att ta bort instrumentpanelen?"
	},


	"status": {
		"1000": "Bluetooth är inte påslagen",
		"1001": "Bluetooth är avstängd",
		"1002": "Väntar på bränslebesparing",
		"1003": "Söker efter OBD",
		"1004": "Ansluter OBD",
		"1005": "Bluetooth är ansluten",
		"1006": "har lyckats skriva data",
		"1007": "Det gick inte att skriva data",
		"1008": "Aktivera meddelande framgångsrikt",
		"1009": "Ingen enhet hittades"
	},


	"szgl": {
		"bt": "Inställning",
		"label1": "Språk",
		"value1": "Följ systemet",
		"label2": "Sekretesspolicy",
		"label3": "Anslutningshjälp",
		"label4": "Om",
		"label5": "Officiell galleria",
		"value5": "1688 Mall",
		"label6": "Version",
		"cjwt": "Vanligt problem",
		"unittitle": "Enhet",
		"unitvalue1": "Mätriskt system",
		"unitvalue2": "Kejsarliga enheter",
		"unitinfo": "Bekräfta om du vill byta enhet?"
	},

	"yygl": {
		"label": "Följ system",
		"des": "När den har slagits på kommer den automatiskt att ställas in enligt systemspråket",
		"en": "Engelska",
		"zh": "Förenklad kinesiska",
		"zwft": "Traditionell kinesiska",
		"es": "Spanska",
		"kr": "koreanska",
		"ru": "Ryska",
		"ja": "japanska",
		"it": "Italienska",
		"hi": "Hindi",
		"pt": "Portugisiska",
		"de": "Tyska",
		"fr": "Franska",
		"nl": "holländska",
		"fi": "finska",
		"pl": "polska",
		"bn": "bengaliska",
		"hu": "Ungerska",
		"cs": "Tjeckiska",
		"th": "Thailand",
		"tr": "Turkiska",
		"ms": "Malayisk",
		"ro": "rumänska",
		"sv": "Svenska",
		"da": "danska"
	},


	"obdManage": {
		"bt": "OBD-hantering",
		"search_tip": "Sök igen eller köp våra produkter",
		"buy_tip": "Gå till köpcentret för att köpa",
		"searchAgain": "Sök igen",
		"nearBy": "Utrustning i närheten",
		"ls": "Historisk utrustning",
		"bz": "Visa hjälp",
		"del": "Ta bort",
		"delConfirm": "Är du säker på att ta bort den här posten?",
		"switched": "Enheten håller på att bytas, är du säker?",
		"qrxx": "Bekräfta att omkopplaren för Bluetooth och platsinformation på mobiltelefonen är påslagen.",
		"searchAgain_message": "Är du säker på att du ska söka efter närliggande enheter?"
	},


	"gzjc": {
		"bt": "Diagnostik",
		"btn": "Börja testa",
		"des": "Starta en fullständig genomsökning av ditt fordon",
		"FaultCodeQuery": "Felkodsfråga",
		"zzjc": "Testar",
		"clearFaultCode": "Rensa felkod",
		"kscz": "sök",
		"fxgz": "Felkod hittades",
		"notFound": "inga problem hittades",
		"cxjc": "Kontrollera igen",
		"modalTitle": "Är du säker på att du vill rensa felkoden?",
		"modalContent": "Innan felet är löst rekommenderas det att inte rensa felkoden efter behag. De flesta ECU:er tillåter inte att felkoden raderas när motorn är igång. Huruvida felkoden kan rensas eller inte är i slutändan bestäms av ECU:n. Att radera felkoder är inte riktigt lösningen på problemet.",
		"sdjc": "Djupinspektionsrapport",
		"num": "Antal felkoder",
		"gzmxx": "Felkodsdetaljer",
		"label1": "kategori",
		"label2": "Felkodsförklaring",
		"definition_03": "Diagnostiska felkoder",
		"definition_07": "Väntande diagnostiska felkoder",
		"definition_0A": "Permanenta felkoder för diagnostik",
		"03_des": "När en avvikelse upptäcks av ECU (Vehicle Control Unit), lagras en felkod i minnet. Denna felkod hänvisar till en onormal situation som upptäcktes under den senaste körningen. Dessa felkoder sparas i minnet. under en viss tid, när felkoden hittas igen, uppdatera lagringsperioden.",
		"07_des": "Detta är en obekräftad avvikelse under körning. Om avvikelsen upprepas och identifieras kommer den tillfälliga felkoden att klassificeras som en bekräftad felkod. Om den inte sparas kommer den att raderas när motorn stängs av.",
		"0A_des": "Eftersom den visar en historik över tidigare felkoder, representerar den inte den aktuella fordonsstatusen. Det kanske inte är möjligt att programmässigt radera motsvarande felkodskoder.",
		"sys_P": "Driftsystem (definierat av tillverkare)",
		"sys_B": "Kroppssystem (definierat av tillverkare)",
		"sys_C": "Chassisupphängningssystem (tillverkardefinierat)",
		"sys_U": "Nätverkskommunikationssystem (definierat av tillverkare)",
		"zzs": "Alla biltillverkare"
	},

	"clgl": {
		"bt": "Min bil",
		"info1": "Grundläggande bilinformation",
		"clpp": "Bilmärken",
		"xh": "Bilmodell",
		"nk": "År",
		"rylx": "Bränsletyp",
		"info2": "Annan fordonsinformation",
		"atdp": "Kommunikationsprotokoll",
		"ati": "Adapterversion",
		"vin": "Fordonets identifieringsnummer",
		"cid": "Kalibreringsidentifikationer",
		"cvn": "Kalibreringsverifieringsnummer",
		"ecu": "Elektronisk kontrollenhet",
		"ESN": "Motorns serienummer",
		"EROTAN": "Avgasreglering eller typgodkännandenummer",
		"FEOCNTR": "Fueled Engine Operation Tändningscykelräknare",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Vänligen fyll i fordonsmärket",
		"warn2": "bilmodell krävs",
		"warn3": "bilår krävs",
		"warn4": "vin krävs",
		"warn5": "Vänligen fyll i rätt fordonsidentifikationsnummer",
		"warn6": "bilägarens namn krävs",
		"warn7": "telefon krävs",
		"warn8": "Ange rätt telefon",
		"warn9": "Ange rätt e-postadress",
		"bt": "OBD-anslutningen lyckades",
		"title_sub": "Följande information är mycket viktig för korrekt diagnos, för att förbättra din upplevelse. Var noga med att fylla i noggrant.",
		"ts_vin": "Placeringen av VIN-koden: vanligtvis placerad på vänster sida av instrumentpanelen, den nedre vänstra delen av den främre vindrutan; det finns också en dörrgångjärnskolumn, en dörrlåspelare eller en av kolumnerna anslutna till dörrlåspelaren; eller dörren nära förarsätet inuti.",
		"vin": "Vin",
		"czxm": "Namn",
		"lxdh": "Telefon",
		"lxyx": "E-post"
	},
	"ota": {
		"bt": "OTA-uppgradering",
		"jcdxbb": "Ny firmwareversion upptäckt",
		"gxnr": "Uppdatera innehåll",
		"fxsm": "Uppgraderingsinstruktioner",
		"fxsm_des": "OTA-uppgradering (over-the-air technology) innebär att mobilterminalen laddar ner uppgraderingspaketet på distans på servern för att uppgradera OBD-firmwaren. Uppgraderingen kommer inte att påverka ditt fordon och din körsäkerhet, använd gärna it. Om det uppmanas att uppgraderingen har misslyckats, vänligen lämna inte gränssnittet, sätt tillbaka OBD:n och fortsätt uppgraderingen.",
		"zysx": "Varning",
		"zysx_des": "Uppgradera inte under körning och ta inte bort eller stäng inte av OBD under uppgraderingen.",
		"mssj": "Uppgradera nu",
		"kssj": "Starta uppgraderingen",
		"sjcg": "OTA-uppgraderingen lyckades",
		"kqqxty": "Öppna en ny upplevelse",
		"xzgj": "Ladda ner firmware",
		"zzxr": "Skriver",
		"zzsj": "Uppgraderar",
		"zzjy": "Verifierar integriteten",
		"sjsb": "Uppgraderingen misslyckades, försök igen"
	},

	"xcfx": {
		"ksxc": "Starta resan",
		"jsxc": "Avsluta resan",
		"lsjl": "Historikpost",
		"zlc": "Total körsträcka",
		"hs": "Tidskrävande",
		"kssj": "Starttid",
		"zyh": "Totalt antal liter"
	},

	"xncs": {
		"jsxn": "Accelererad",
		"scxn": "Bromsning",
		"jlxn": "Avstånd",
		"des1": "Hastighetstestintervall",
		"des2": "hastighet vid inbromsning",
		"des3": "testavstånd",
		"aqtx": "var uppmärksam på körsäkerhet!",
		"kscs": "Börja testa",
		"cxcs": "Testa igen",
		"tz": "Stopp",
		"tip1": "Justera fordonshastigheten till",
		"tip2": "Trampa på gaspedalen för att accelerera till",
		"tip2_end": "Ovan",
		"tip3": "Trampa på bromsarna för att minska hastigheten till",
		"tip4": "Vänligen kör",
		"tip5": "Reste",
		"max_sd": "Topphastighet",
		"max_jsd": "Maximal acceleration",
		"max_zs": "Maximal hastighet",
		"tx1": "Starthastigheten kan inte vara högre än sluthastigheten",
		"tx2": "Vänligen fyll i bromshastighet större än 0",
		"tx3": "Vänligen fyll i testavståndet större än 0"
	},

	"bzxx": {
		"title1": "Steg 1: Starta fordonet",
		"title2": "Steg 2: Anslut enheten",
		"title3": "Steg 3: Slå på Bluetooth och plats",
		"title4": "Steg 4: Öppna APPEN",
		"title5": "Steg 5: Anslut enheten",
		"text1": "Hitta platsen för fordonets OBD-gränssnitt. OBD-gränssnittet är ett 16-stifts hongränssnitt. Gränssnittet är trapetsformat. Vissa modeller har ett lock på OBD-gränssnittet. Vanliga OBD-portar är svarta, vita eller blå. Placeringen är vanligtvis i den inre trimpanelen under ratten, nära förarens knän. Placeringen av OBD-gränssnittet kan vara olika för olika modeller och modeller. Följande bild visar den möjliga placeringen av OBD-gränssnittet:",
		"text2": "När du har hittat OBD-gränssnittet ansluter du enheten till OBD-gränssnittet. Se till att den är ansluten hela vägen (många bilar är inkopplade ungefär halvvägs och strömmen är på, men signalstiften kanske inte är anslutna ansluten), och den röda strömindikatorn eller skärmen är på.",
		"text3": "Slå på Bluetooth och platsknapparna på din telefon. Metod: Svep nedåt längst upp på telefonskärmen, öppna genvägsmenyn och klicka på Bluetooth och platsinformation. Aktivera Bluetooth på din iOS-enhet.",
		"text4": "Öppna appen och låt appen använda platsinformation.",
		"text5": "När du har slutfört stegen ovan, ange APP, APP kommer automatiskt att skanna OBD-enheten och fråga dig om du ska ansluta enheten. iOS-enheten frågar om du vill tillåta åtkomst till adressen, klicka på Tillåt.",
		"text6": "Välj enheten som ska anslutas och klicka för att ansluta. När anslutningen har lyckats kommer APP:s hemsida att visa OBD-enhetens namn, Bluetooth-adress och en läsning visas på instrumentpanelen."
	},

	"06fw": {
		"MID": "Monitornamn",
		"TID": "Testnamn",
		"CID": "Komponentnummer",
		"O2Sensor": "O2-sensornamn",
		"MIN": "Minimumgräns",
		"MAX": "Maximal gräns",
		"CURRENT": "Testvärde"
	},

	"09fw": {
		"ipt": "Spårning av prestanda under användning",
		"IPT_08_1": "OBD-övervakningsförhållanden som påträffats, antal",
		"IPT_08_2": "Tändningscykelräknare",
		"IPT_08_3": "Catalyst Monitor Completion Counts Bank 1",
		"IPT_08_4": "Katalysatorövervakare tillstånd som påträffats räknas bank 1",
		"IPT_08_5": "Catalyst Monitor Completion Counts Bank 2",
		"IPT_08_6": "Katalysatorövervakares tillstånd som uppstått räknas bank 2",
		"IPT_08_7": "O2-sensormonitorns slutförande räknar bank 1",
		"IPT_08_8": "O2-sensorövervakningsförhållanden som påträffats räknas bank 1",
		"IPT_08_9": "O2 Sensor Monitor Completion Counts Bank 2",
		"IPT_08_10": "O2-sensorövervakningsförhållanden som påträffats räknas bank 2",
		"IPT_08_11": "EGR- och/eller VVT-övervakares slutförandet räknas",
		"IPT_08_12": "EGR- och/eller VVT-övervakningsförhållanden som har påträffats",
		"IPT_08_13": "AIR Monitor Completion Condition Counts (Secondary Air)",
		"IPT_08_14": "Antal påträffade AIR Monitor-förhållanden (sekundär luft)",
		"IPT_08_15": "EVAP Monitor Completion Condition Counts",
		"IPT_08_16": "EVAP-övervakningsförhållanden som påträffats, räknas",
		"IPT_08_17": "Sekundär O2-sensormonitors slutförande räknar bank 1",
		"IPT_08_18": "Sekundära O2-sensorövervakningsförhållanden påträffade räknar bank 1",
		"IPT_08_19": "Sekundär O2-sensormonitors slutförande räknar bank 2",
		"IPT_08_20": "Sekundära O2-sensorövervakningsförhållanden påträffade räknas bank 2",

		"IPT_08_des_1": "visar antalet gånger som fordonet har körts under de angivna OBD-övervakningsförhållandena (allmän nämnare).",
		"IPT_08_des_2": "visar antalet gånger som motorn har startats.",
		"IPT_08_des_3": "visar antalet gånger som alla villkor som krävs för att upptäcka ett fel i katalysatorsystem bank 1 har påträffats (täljare).",
		"IPT_08_des_4": "visar antalet gånger som fordonet har körts under de angivna katalysatorövervakningsförhållandena (nämnaren).",
		"IPT_08_des_5": "visar antalet gånger som alla villkor som krävs för att upptäcka ett fel på katalysatorsystembank 2 har påträffats (täljare).",
		"IPT_08_des_6": "visar antalet gånger som fordonet har körts under de angivna katalysatorövervakningsförhållandena (nämnaren).",
		"IPT_08_des_7": "visar antalet gånger som alla villkor som är nödvändiga för att upptäcka ett fel på syrgassensorbank 1 har påträffats (täljare).",
		"IPT_08_des_8": "visar antalet gånger som fordonet har körts under de angivna syrgassensorns övervakningsförhållanden (nämnare).",
		"IPT_08_des_9": "visar antalet gånger som alla tillstånd som krävs för att upptäcka ett fel på syrgassensorbank 2 har påträffats (täljare).",
		"IPT_08_des_10": "visar antalet gånger som fordonet har körts under de angivna syrgassensorns övervakningsförhållanden (nämnare).",
		"IPT_08_des_11": "visar antalet gånger som alla tillstånd som krävs för att upptäcka ett EGR/VVT-systemfel har påträffats (täljare).",
		"IPT_08_des_12": "visar antalet gånger som fordonet har körts under de specificerade EGR/VVT-systemets övervakningsförhållanden (nämnare).",
		"IPT_08_des_13": "visar antalet gånger som alla villkor som krävs för att upptäcka ett AIR-systemfel har påträffats (täljare).",
		"IPT_08_des_14": "visar antalet gånger som fordonet har körts under de angivna AIR-systemets övervakningsförhållanden (nämnare).",
		"IPT_08_des_15": "visar antalet gånger som alla villkor som krävs för att detektera ett 0,020” (eller 0,040”) läckagefel i EVAP-systemet har påträffats (täljare).",
		"IPT_08_des_16": "visar antalet gånger som fordonet har körts under de specificerade EVAP-systemets läckagefelsövervakningsförhållanden (nämnare).",
		"IPT_08_des_17": "visar antalet gånger som alla tillstånd som krävs för att upptäcka en sekundär syrgassensor bank 1-fel har påträffats (täljare).",
		"IPT_08_des_18": "visar antalet gånger som fordonet har körts under de angivna sekundära syresensorövervakningsförhållandena (nämnare).",
		"IPT_08_des_19": "visar antalet gånger som alla villkor som krävs för att upptäcka en sekundär syrgassensorbank 2-fel har påträffats (täljare).",
		"IPT_08_des_20": "visar antalet gånger som fordonet har körts under de angivna sekundära syresensorövervakningsförhållandena (nämnare).",

		"IPT_0B_1": "OBD-övervakningsförhållanden som påträffats, antal",
		"IPT_0B_2": "Tändningscykelräknare",
		"IPT_0B_3": "NMHC Catalyst Monitor Färdigställande tillstånd räknas",
		"IPT_0B_4": "NMHC Catalyst Monitor Conditions påträffade räkningar",
		"IPT_0B_5": "NOx/SCR Catalyst Monitor Completion Condition Condition Counts",
		"IPT_0B_6": "NOx/SCR Katalysatorövervakningsförhållanden som påträffats",
		"IPT_0B_7": "NOx Adsorber Monitor Completion Condition Condition Counts",
		"IPT_0B_8": "Nox Adsorber Monitor Conditions påträffade räkningar",
		"IPT_0B_9": "PM-filterövervakarens slutförandet räknas",
		"IPT_0B_10": "PM-filterövervakningsförhållanden som har påträffats",
		"IPT_0B_11": "Avgassensorövervakarens slutförande tillstånd räknas",
		"IPT_0B_12": "Avgassensorövervakningsförhållanden som påträffats, räknas",
		"IPT_0B_13": "EGR- och/eller VVT-övervakares slutförandet räknas",
		"IPT_0B_14": "EGR- och/eller VVT-övervakningsförhållanden som har påträffats",
		"IPT_0B_15": "Boost Pressure Monitor Complete Condition Condition Counts",
		"IPT_0B_16": "Boosttrycksövervakningsförhållanden som påträffats, räknas",
		"IPT_0B_17": "Fullständig tillstånd för bränsleövervakning räknas",
		"IPT_0B_18": "Bränsleövervakningsförhållanden som påträffats räknas",

		"IPT_0B_des_1": "visar antalet gånger som fordonet har körts under de angivna OBD-övervakningsförhållandena (allmän nämnare).",
		"IPT_0B_des_2": "visar antalet gånger som motorn har startats.",
		"IPT_0B_des_3": "visar antalet gånger som alla villkor som krävs för att upptäcka ett fel på NMHC-katalysatorsystemet har påträffats (täljare).",
		"IPT_0B_des_4": "visar antalet gånger som fordonet har körts under de specificerade NMHC-katalysatorövervakningsförhållandena (nämnare).",
		"IPT_0B_des_5": "visar antalet gånger som alla villkor som krävs för att upptäcka ett fel på NOx-katalysatorsystemet har påträffats (täljare).",
		"IPT_0B_des_6": "visar antalet gånger som fordonet har körts under de specificerade NOx-katalysatorövervakningsförhållandena (nämnare).",
		"IPT_0B_des_7": "visar antalet gånger som alla tillstånd som krävs för att upptäcka ett fel i NOx-adsorbersystemet har påträffats (täljare).",
		"IPT_0B_des_8": "visar antalet gånger som fordonet har körts i den specificerade nämnaren för NOx-adsorberövervakningsförhållanden).",
		"IPT_0B_des_9": "visar antalet gånger som alla villkor som krävs för att upptäcka ett fel på PM-filtersystemet har påträffats (täljare).",
		"IPT_0B_des_10": "visar antalet gånger som fordonet har körts i den specificerade nämnaren för övervakningsförhållanden för PM-filter).",
		"IPT_0B_des_11": "visar antalet gånger som alla villkor som krävs för att upptäcka ett fel på avgassensorn har påträffats (täljare)",
		"IPT_0B_des_12": "visar antalet gånger som fordonet har körts under de specificerade avgassensorernas övervakningsförhållanden (nämnare).",
		"IPT_0B_des_13": "visar antalet gånger som alla villkor som krävs för att upptäcka ett EGR/VVT-systemfel har påträffats (täljare).",
		"IPT_0B_des_14": "visar antalet gånger som fordonet har körts under de specificerade EGR/VVT-systemets övervakningsförhållanden (nämnare).",
		"IPT_0B_des_15": "visar antalet gånger som alla villkor som är nödvändiga för att upptäcka ett fel på laddtryckssystemet har påträffats (täljare).",
		"IPT_0B_des_16": "visar antalet gånger som fordonet har körts under de specificerade laddtryckssystemets övervakningsförhållanden (nämnare).",
		"IPT_0B_des_17": "visar antalet gånger som alla förhållanden som är nödvändiga för att upptäcka ett fel i bränslesystemet har påträffats (täljare).",
		"IPT_0B_des_18": "visar antalet gånger som fordonet har körts under de angivna bränslesystemets övervakningsförhållanden (nämnare)."
	}
}
