// 土耳其语
var i18n = {
	"mt": "Gün",
	"xs": "Saat",
	"fz": "Dakika",
	"wxts": "İpuçları",
	"zzjz": "yükleniyor...",
	"noData": "VERİ YOK",
	"jchj" :"Giriş ortamı kontrol ediliyor",
	"ckfw": "Referans aralığı",
	"bbgl": {
		"bbts": "Sürüm güncelleme hatırlatıcısı",
		"official": "Yayınlanan yeni özellikler var, en son sürümü indirmek ve yükseltmek için lütfen resmi web sitesine gidin.",
		"apple": "Yeni özellikler yayınlandı, lütfen yükseltilmiş sürümü indirmek için App Store'a gidin.",
		"google": "Yayınlanan yeni özellikler var, lütfen yükseltilmiş sürümü indirmek için Google Play'e gidin."
	},
	"uds": {
	"uds0001": "Modül Seçin",
	"uds0002": "Okunacak modülü seçin",
	"uds0003": "Liste, seçilen markanın desteklenen tüm modüllerini içerir, yalnızca araçta mevcut olan modüllerin seçilmesi önerilir. Ancak, tüm modüller seçilebilir. Sistem, araçta gerçekte bulunan birimleri otomatik olarak algılar .",
	"uds0004": "Tümünü seç",
	"uds0005": "Tümünü Seçmeyi İptal Et",
	"uds0006": "Teşhis Başlat",
	"uds0007": "Satıcı Özel"
	},
	"yjdl": {
		"yxdl": "E-posta Girişi",
		"dlts": "Önce grafik Captcha'yı girin ve ardından e-posta Captcha'yı alın",
		"sryx": "Lütfen e-posta adresinizi giriniz",
		"sryzm": "Lütfen Captcha'yı girin",
		"xyb": "Sonraki",
		"xgyx": "Posta kutusunu değiştir",
		"yxdz": "E-posta adresi",
		"fsyzm": "e-postaya erişim kodu gönder",
		"yzm": "Erişim Kodu",
		"cxfs": "tekrar göndermek için saniye",
		"dl": "Giriş",
		"srtxyzm": "Sol grafik Captcha'yı girin",
		"yxbzq": "E-posta hatalı",
		"txyzmbzq": "Grafik Captcha hatalı",
		"fsdx": "Captcha Gönderiliyor",
		"yxyzmfscg": "E-posta Captcha başarıyla gönderildi",
		"yxbky": "E-posta gönderimi anormal! Lütfen e-posta adresinin doğru girilip girilmediğini ve e-postanın normal şekilde alınıp alınmadığını kontrol edin.",
		"zzyz": "Doğrulanıyor",
		"yzmcw": "E-posta Captcha hatalı",
		"clxxgl": "Araç Bilgi Yönetimi",
		"gxxx": "Bilgileri güncelle",
		"dlcg": "Giriş başarılı",
		"dlsb": "Giriş başarısız oldu",
		"clxx": "Araç Bilgileri",
		"czxx": "Araç sahibi bilgileri",
		"wdl": "Giriş yapılmadı",
		"cl": "Araç"
	},
	
	"OBDxncs": {
		"bt": "Adaptör karşılaştırması",
		"fbt": "daha büyük, daha hızlı demektir",
		"zjsd": "En uygun hız",
		"dqsd": "Mevcut hız",
		"xzmc": "ECU'dan saniyede parametre okuma hızı (birim: parametreler/saniye)",
		"sec_dt": "Galaxy Note 8 ve Pixel 2 ile test edilmiştir",
		"sec_dd1": "(1) Çoğu telefon kullanımdayken internete olan veri bağlantısını kaybettiğinden, Wi-Fi bağdaştırıcıları genellikle Android için önerilmez.",
		"sec_dd2": "(2) 'WiFi', 'USB' veya 'BLE' adlarının bir parçası olmadıkça test edilen tüm bağdaştırıcılar standart Bluetooth'tur",
		"text2": "OBD Karşılaştırması"
	},
	
	"tsxx": {
		"qxz": "seç",
		"qsr": "Lütfen giriniz",
		"qqr": "Onayla",
		"qqx": "İptal",
		"notConnected": "Lütfen önce cihazınızı bağlayın",
		"save": "Formu başarıyla kaydedin.",
		"dsyh": "Rölanti yakıt tüketimi, istatistiksel birim olarak zaman ile birlikte, aracın hareketsiz olduğu andaki yakıt tüketimini ifade eder.",
		"xsyh": "Sürüş yakıt tüketimi, aracın sürüş durumunda olduğu andaki yakıt tüketimini ifade eder ve istatistiksel birim olarak mesafeyi alır.",
		"pjyh": "Ortalama yakıt tüketimi, aracın bu sürüş sürecinde 100 kilometrelik yakıt tüketimini ifade eder ve yalnızca 1 km'den fazla sürdükten sonra görüntülenir.",
		"cqyh": "Uzun süreli yakıt tüketimi, APP'nin çalışması sırasında aracın 100 kilometre boyunca tükettiği yakıt tüketimini ifade eder.",
		"yhsupport": "Bu araba yakıt tüketimi görüntülemeyi desteklemiyor",
		"cg": "başarı",
		"noTrouble": "Tebrikler, aracınız kusursuz, lütfen böyle devam edin.",
		"noVin": "Size daha iyi hizmet verebilmemiz için lütfen 17 haneli çerçeve numarasını giriniz.",
		"gzzsd": "MIL, Arıza Gösterge Lambasının kısaltmasıdır. MIL ışığının yanması motor sisteminde arıza olabileceği anlamına gelir. MIL ışığının yanma nedeni motor içinde çok fazla karbon birikmesi olabilir. gaz kelebeği veya motor veya oksijen sensörü arızalandıktan sonra karışım oranı dengesiz veya benzinin yakıt kalitesinin düşük olması ve aracın yetersiz yanması nedeniyle motor lambası yanıyor.",
		"noDevelopment": "Geliştirme aşamasında, bizi izlemeye devam edin.",
		"zc": "Şu anda test için kullanılabilir",
		"noSupport": "Şu anda test için uygun değil",
		"noNetwork": "Ağınız şu anda kullanılamıyor. Hiçbir ağ deneyiminizi etkilemeyecek.",
		"jy": "Kapalı",
		"ywc": "Durum testi tamamlandı",
		"noCompelte": "Durum testi tamamlanmadı",
		"noSupportPid": "Aracınızda bu test yok!",
		"useReminders": "Hatırlatma: Duraklattıktan sonra kaydırıcıda veya dokunmatik ekranda parmağınızı kaydırarak yakınlaştırabilir veya gezinebilirsiniz.",
		"noCompelteDes": "Hazır durumu test edilebiliyor ancak tamamlanamıyorsa, aşağıdaki önlemler madde madde alınabilir: tam sürüş, aracın bakımı, montajın temizlenmesi, ECU'nun yükseltilmesi vb. gelecekte şartnamelere uygun olarak çalıştırılacak ve düzenli bakımları yapılacaktır.",
		"fgf": "Bu işlev resmi ürünlere özeldir, lütfen satın aldıktan sonra kullanın!",
		"b25": "Bu işlev B25'e özeldir, lütfen satın aldıktan sonra kullanın!"
	},
	
	"pid": {
		"dsyh": "Rölantide Yakıt Tüketimi",
		"xsyh": "yakıt Tüketimi",
		"ssyh": "Ortalama Tüketim",
		"pjyh": "Anında Tüketim",
		"cqyh": "Uzun süreli yakıt tüketimi",
		"pjsd": "Ortalama hız",
		"xslc": "Sürülen mesafe",
		"DTC_legnth":"Bu ECU'da saklanan DTC sayısı",
		"MIL":"Arıza Gösterge Lambası Durumu",
		"mil_0": "ışık kapalı",
		"mil_1": "ışık açık",
		"shxt": "Tekleme izleme",
		"ryxt": "Yakıt sistemi izleme",
		"zhzj": "Kapsamlı bileşen izleme",
		
		"fdjlx": "Motor tipi",
		"ysfdj": "sıkıştırmalı ateşleme",
		"dhfdj": "kıvılcım ateşleme",
		"chj": "Katalizör izleme",
		"jrchj": "Isıtılmış katalizör izleme",
		"zfxt": "Evaporatif sistem izleme",
		"eckqxt": "İkincil hava sistemi izleme",
		"ktxtzlj": "A/C sistemi soğutucu akışkan izleme",
		"ycgqjrq": "Oksijen sensörü ısıtıcı izleme",
		"ycgqjk": "Oksijen sensörü izleme",
		"erg": "EGR/VVT Sistemi izleme",
		"NMHC": "NMHC Katalizör izleme",
		"NOx": "NOx/SCR izleme",
		"yl": "Ayrıldı",
		"zyyl": "Takviye Basıncı izleme",
		"fqcgq": "Egzoz Gazı Sensörü izleme",
		"pmglq": "PM filtresi Monitör izleme"
	},

	"sygl": {
		"xieyi": "Protokol",
		"tips1": "Cihazı bağlayın",
		"tips2": "Lütfen Bluetooth'u açın! Yardımı görüntüle",
		"tips3": "Cihazı bulamıyor musunuz? Yardımı görüntüle",
		"tips4": "Lütfen konum hizmetlerini açın",
		"tips5": " Evrensel",
		"tips6": " Uygun maliyetli sürüm",
		"sdlj": "Manuel olarak bir bağlantı seçin"
	},
	
	"djz": {
		"noData": "Şu anda donmuş çerçeve verisi yok",
		"previousFrame": "Önceki Çerçeve",
		"nextFrame": "Sonraki Çerçeve"
	},
	
	"fwgl": {
		"ybp": "Pano",
		"UDS": "Birleşik Teşhis Hizmeti (Test)",
		"UDS_des": "Araç birleşik teşhis hizmeti, daha fazla ECU ve daha fazla fonksiyon sağlayın",
		"DTC": "DTC izleme",
		"DTC_des": "Araç arıza kodları için profesyonel çözümler sağlayın",
		"xcfx": "Gezi Analizi",
		"xcfx_des": "Her yolculuk verilerinizi analiz edin",
		"xncs": "Araç Performans Testi",
		"xncs_des": "Profesyonel araç performans analizi raporu sağlayın",
		"sssjl": "gerçek zamanlı veri akışı",
		"sssjl_des": "Mevcut aktarma organı teşhis verilerini talep et",
		"gzzsd": "Hata göstergesi algılama",
		"gzzsd_des": "Arıza ışığı yandıktan veya söndükten sonra aracın çalışma bilgisini verir",
		
		"pid0141": "Tanı Hazır Durumu",
		"pid0141_des": "DTC silindiğinden beri araç izleme durumunu ve mevcut sürüş döngüsü izleme çalışma durumunu sağlar",
		"$05": "Oksijen sensörü izleme sonuçları",
		"$05_des": "Araç oksijen sensörü izleme test sonuçlarını okuyun",
		"$06": "Belirli izleme sonuçları",
		"$06_des": "Belirli bileşenler/sistemler için Yerleşik Teşhis izleme testlerinin sonuçlarına erişime izin ver.",
		"$09": "Araç Bilgileri",
		"$09_des": "Araca özel araç bilgilerini ve bilgilerini oku",
		
		"clnj": "",
		"clnj_des": "",
		
		"obdTest": "OBD performans testi",
		"obdTest_des": "OBD'nin çeşitli performans göstergelerini otomatik test araçlarıyla test edin.",
		"djz": "Çerçeveyi Dondur",
		"djz_des": "Egzoz sisteminde bir DTC görüntülendiğinde, DTC görüntülendiğinde ECU verileri depolar",
		"yjjc": "Tek tıkla tam araç tespiti",
		"yjjc_des": "Tüm araç sensör verilerinin, araç bilgilerinin, sorun kodlarının, donma çerçevelerinin ve araç izleme bilgilerinin kapsamlı tespiti."
	},
	
	"yjjc": {
		"cljkxx": "araç izleme bilgisi",
		"xx_09": "Araç bilgisi algılanıyor",
		"xx_03": "Hata bilgisi algılanıyor",
		"xx_01": "Araç izleme bilgisi algılanıyor",
		"xx_02": "Çerçeve dondurma bilgisi algılanıyor",
		"xx_05": "Oksijen sensörü bilgisi algılanıyor",
		"xx_06": "Belirli izleme sonucu bilgilerinin okunması"
	},
	
	"ybpgl":{
		"dcdy": "Akü voltajı",
		"xhyb": "Seyahat Ölçer",
		"yhyb": "Yakıt Tüketimi Ölçer",
		"zdyyb": "Özel Sayaç",
		"xz": "Gösterge Tablosu Ekle",
		"bj": "Gösterge Panosunu Düzenle",
		"sc": "Gösterge Tablosunu Sil",
		"delete_tips": "Gösterge tablosunu silmek istediğinizden emin misiniz?"
	},
	
		
	"status": {
		"1000": "Bluetooth açık değil",
		"1001": "Bluetooth kapalı",
		"1002": "Yakıt tasarrufu bekleniyor",
		"1003": "OBD aranıyor",
		"1004": "OBD Bağlanıyor",
		"1005": "Bluetooth bağlı",
		"1006": "veri yazmak başarıyla",
		"1007": "Veriler yazılamadı",
		"1008": "Bildirimi başarıyla etkinleştir",
		"1009": "Cihaz bulunamadı"
	},

  
	"szgl": {
		"bt": "Ayar",
		"label1": "Dil",
		"value1": "Sistemi takip et",
		"label2": "Gizlilik Politikası",
		"label3": "Bağlantı yardımı",
		"label4": "Hakkında",
		"label5": "Resmi alışveriş merkezi",
		"value5": "1688 Alışveriş Merkezi",
		"label6": "Sürüm",
		"cjwt": "Ortak sorun",
		"unittitle": "Birim",
		"unitvalue1": "Metrik sistem",
		"unitvalue2": "İngiliz Birimleri",
		"unitinfo": "Birimlerin değiştirilip değiştirilmeyeceği onaylansın mı?"
	},

	"yygl": {
		"label": "Sistemi takip et",
		"des": "Açıldıktan sonra otomatik olarak sistem diline göre ayarlanacaktır",
		"en": "İngilizce",
		"zh": "Basitleştirilmiş Çince",
		"zwft": "Geleneksel Çince",
		"es": "İspanyolca",
		"kr": "Korece",
		"ru": "Rusça",
		"ja": "Japonca",
		"it": "İtalyanca",
		"hi": "Hintçe",
		"pt": "Portekizce",
		"de": "Almanca",
		"fr": "Fransızca",
		"nl": "Hollandaca",
		"fi": "Fince",
		"pl": "Lehçe",
		"bn": "Bengalce",
		"hu": "Macarca",
		"cs": "Çek",
		"th": "Tayca",
		"tr": "Türkçe",
		"ms": "Malayca",
		"ro": "Rumence",
		"sv": "İsveççe",
		"da": "Danimarkalı"
	},

	
	"obdManage": {
		"bt": "OBD Yönetimi",
		"search_tip": "Lütfen tekrar arayın veya ürünlerimizi satın alın",
		"buy_tip": "Lütfen satın almak için alışveriş merkezine gidin",
		"searchAgain": "Tekrar ara",
		"nearBy": "Yakındaki ekipman",
		"ls": "Tarihi ekipman",
		"bz": "Yardımı görüntüle",
		"del": "Sil",
		"delConfirm": "Bu kaydı silmek istediğinizden emin misiniz?",
		"switched": "Cihaz değiştirilmek üzere, emin misiniz?",
		"qrxx": "Lütfen cep telefonunun Bluetooth ve konum bilgisi anahtarının açık olduğunu doğrulayın.",
		"searchAgain_message": "Yakındaki cihazları tekrar aramak istediğinizden emin misiniz?"
	},

	
"gzjc": {
		"bt": "Teşhis",
		"btn": "Test başlat",
		"des": "Aracınızın tam taramasını başlatın",
		"FaultCodeQuery": "Hata kodu sorgulama",
		"zzjc": "Test",
		"clearFaultCode": "Hata kodunu temizle",
		"kscz": "ara",
		"fxgz": "Hata kodu bulundu",
		"notFound": "sorun bulunamadı",
		"cxjc": "Yeniden kontrol et",
		"modalTitle": "Hata kodunu silmek istediğinizden emin misiniz?",
		"modalContent": "Arıza çözülmeden önce, isteyerek hata kodunun silinmemesi önerilir. Çoğu ECU, motor çalışırken hata kodunun silinmesine izin vermez. Hata kodunun silinip silinemeyeceği nihai olarak tartışılır. ECU tarafından belirlenir.Arıza kodlarını silmek aslında sorunun çözümü değildir.",
		"sdjc": "Derinlik inceleme raporu",
		"num": "Hata kodu sayısı",
		"gzmxx": "Hata kodu ayrıntıları",
		"label1": "kategori",
		"label2": "Hata kodu açıklaması",
		"definition_03": "Diyagnoz hata kodları",
		"definition_07": "Bekleyen teşhis hata kodları",
		"definition_0A": "Kalıcı arıza teşhis kodları",
		"03_des": "ECU (Araç Kontrol Ünitesi) tarafından bir anormallik algılandığında, hafızada bir arıza kodu saklanır. Bu arıza kodu, son sürüş işlemi sırasında bulunan anormal bir durumu ifade eder. Bu arıza kodları hafızada tutulur. bir süre için, hata kodu tekrar bulunduğunda saklama süresini güncelleyin.",
		"07_des": "Bu, sürüş sırasında onaylanmayan bir anormalliktir. Anormallik tekrarlanır ve tanımlanırsa, geçici arıza kodu onaylanmış bir arıza kodu olarak sınıflandırılır. Kaydedilmezse, motor kapatıldığında silinir." ,
		"0A_des": "Geçmiş DTC'lerin geçmişini gösterdiği için mevcut araç durumunu temsil etmez. İlgili DTC'leri programlı olarak silmek mümkün olmayabilir.",
		"sys_P": "Güç aktarım sistemi (üretici tanımlı)",
		"sys_B": "Gövde sistemi (üretici tanımlı)",
		"sys_C": "Şasi askı sistemi (üretici tanımlı)",
		"sys_U": "Ağ iletişim sistemi (üretici tanımlı)",
		"zzs": "Tüm otomobil üreticileri"
	},

	"clgl": {
		"bt": "Arabam",
		"info1": "Temel Araç Bilgileri",
		"clpp": "Otomobil Markaları",
		"xh": "Araba Modeli",
		"nk": "Yıl",
		"rylx": "Yakıt Tipi",
		"info2": "Diğer Araç Bilgileri",
		"atdp": "İletişim Protokolü",
		"ati": "Adaptör Sürümü",
		"vin": "Araç Kimlik Numarası",
		"cid": "Kalibrasyon Kimlikleri",
		"cvn": "Kalibrasyon Doğrulama Numaraları",
		"ecu": "Elektronik Kontrol Ünitesi",
		"ESN": "Motor Seri Numarası",
		"EROTAN": "Egzoz Yönetmeliği Veya Tip Onay Numarası",
		"FEOCNTR":"Yakıtlı Motor Çalışması Ateşleme Çevrim Sayacı",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Lütfen araç markasını giriniz",
		"warn2": "araç modeli gereklidir",
		"warn3": "araba yılı gereklidir",
		"warn4": "vin gereklidir",
		"warn5": "Lütfen doğru araç tanımlama numarasını giriniz",
		"warn6": "araç sahibinin adı gereklidir",
		"warn7": "telefon gereklidir",
		"warn8": "Lütfen doğru telefonu giriniz",
		"warn9": "Lütfen doğru e-postayı girin",
		"bt": "OBD bağlantısı başarılı",
		"title_sub": "Deneyiminizi iyileştirmek için aşağıdaki bilgiler doğru teşhis için çok önemlidir. Dikkatlice doldurduğunuzdan emin olun.",
		"ts_vin": "VIN kodunun yeri: genellikle gösterge panelinin sol tarafında, ön camın sol alt kısmında bulunur; ayrıca bir kapı menteşe kolonu, bir kapı kilit kolonu veya bunlara bağlı kolonlardan biri vardır. kapı kilit direği; veya içeride sürücü koltuğunun yanındaki kapı.",
		"vin": "Vin",
		"czxm": "Ad",
		"lxdh": "Telefon",
		"lxyx": "E-posta"
	},
	"ota": {
		"bt": "OTA yükseltmesi",
		"jcdxbb": "Yeni üretici yazılımı sürümü algılandı",
		"gxnr": "İçeriği güncelle",
		"fxsm": "Yükseltme Talimatları",
		"fxsm_des": "OTA (kablosuz teknoloji) yükseltmesi, mobil terminalin OBD sabit yazılımını yükseltmek için yükseltme paketini sunucuya uzaktan indirmesi anlamına gelir. Yükseltme, aracınızı ve sürüş güvenliğinizi etkilemeyecektir, lütfen kullanmaktan çekinmeyin Yükseltmenin başarısız olduğunu sorarsa, lütfen arayüzden çıkmayın, OBD'yi yeniden takın ve yükseltmeye devam edin.",
		"zysx": "Uyarı",
		"zysx_des": "Sürüş sırasında yükseltme yapmayın ve yükseltme sırasında OBD'yi çıkarmayın veya kapatmayın.",
		"mssj": "Şimdi yükselt",
		"kssj": "Yükseltmeyi başlat",
		"sjcg": "OTA güncellemesi başarılı",
		"kqqxty": "Yeni bir deneyim aç",
		"xzgj": "Firmware'i indir",
		"zzxr": "Yazıyor",
		"zzsj": "Yükseltme",
		"zzjy": "Bütünlük doğrulanıyor",
		"sjsb": "Yükseltme başarısız oldu, tekrar deneyin"
	},

	"xcfx": {
		"ksxc": "Yolculuğu başlat",
		"jsxc": "Geziyi sonlandır",
		"lsjl": "Geçmiş kaydı",
		"zlc": "Toplam kilometre",
		"hs": "Zaman alıcı",
		"kssj": "Başlangıç zamanı",
		"zyh": "Toplam litre"
	},

	"xncs": {
		"jsxn": "Hızlandırılmış",
		"scxn": "Frenleme",
		"jlxn": "Mesafe",
		"des1": "Hız testi aralığı",
		"des2": "frenleme sırasındaki hız",
		"des3": "test mesafesi",
		"aqtx": "Lütfen sürüş güvenliğine dikkat edin!",
		"kscs": "Test başlat",
		"cxcs": "Tekrar test et",
		"tz": "Dur",
		"tip1": "Lütfen araç hızını şu şekilde ayarlayın",
		"tip2": "Hızlanmak için lütfen gaz pedalına basın",
		"tip2_end": "Üst",
		"tip3": "Hızı düşürmek için lütfen frene basın",
		"tip4": "Lütfen sürün",
		"tip5": "Gezildi",
		"max_sd": "En yüksek hız",
		"max_jsd": "Maksimum hızlanma",
		"max_zs": "Maksimum hız",
		"tx1": "Başlangıç hızı bitiş hızından büyük olamaz",
		"tx2": "Lütfen fren hızını 0'dan büyük olarak giriniz",
		"tx3": "Lütfen test mesafesini 0'dan büyük olarak girin"
	},

	"bzxx": {
		"title1": "Adım 1: Aracı çalıştırın",
		"title2": "2. Adım: Cihazın fişini takın",
		"title3": "3. Adım: Bluetooth'u ve Konumu Açın",
		"title4": "4. Adım: APP'yi açın",
		"title5": "5. Adım: Cihazı Bağlayın",
		"text1": "Aracın OBD arabiriminin yerini bulun. OBD arabirimi 16 pinli dişi arabirimdir. Arabirim trapez şeklindedir. Bazı modellerde OBD arabiriminde kapak bulunur. Ortak OBD bağlantı noktaları siyah, beyaz veya mavidir. Konum genellikle direksiyon simidinin altındaki iç trim panelinde, sürücünün dizlerinin yanındadır. OBD arayüzünün konumu, farklı model ve modeller için farklı olabilir. Aşağıdaki şekilde OBD arayüzünün olası konumu gösterilmektedir:",
		"text2": "OBD arayüzünü bulduktan sonra, cihazı OBD arayüzüne takın. Fişin tam olarak takılı olduğundan emin olun (birçok araba yarı yolda takılıdır ve güç açıktır, ancak sinyal pimleri olmayabilir) bağlı) ve kırmızı güç göstergesi veya ekran açık.",
		"text3": "Telefonunuzdaki Bluetooth ve konum anahtarlarını açın. Yöntem: Telefon ekranının üst kısmından aşağı kaydırın, kısayol menüsünü açın ve Bluetooth ve konum bilgilerini tıklayın. iOS cihazınızda Bluetooth'u açın.",
		"text4": "Uygulamayı açın ve uygulamanın konum bilgilerini kullanmasına izin verin.",
		"text5": "Yukarıdaki adımları tamamladıktan sonra APP'ye girin, APP otomatik olarak OBD cihazını tarayacak ve size cihazı bağlayıp bağlamayacağınızı soracaktır. iOS cihazı, adrese erişime izin verilip verilmeyeceğini sorar, İzin Ver'e tıklayın.",
		"text6": "Bağlanacak cihazı seçin ve bağlanmak için tıklayın. Bağlantı başarılı olduktan sonra, uygulamanın ana sayfası OBD cihaz adını, Bluetooth adresini gösterecek ve kontrol panelinde bir okuma görünecektir."
	},
	
	"06fw": {
		"MID": "Monitör Adı",
		"TID": "Test Adı",
		"CID": "Bileşen Numarası",
		"O2Sensor": "O2 Sensör Adı",
		"MIN": "Minimum Limit",
		"MAX": "Maksimum Limit",
		"CURRENT": "Test Değeri"
	},
	
	"09fw": {
		"ipt": "Kullanım Sırasında Performans Takibi",
		"IPT_08_1": "OBD İzleme Koşullarında Karşılaşılan Sayımlar",
		"IPT_08_2": "Ateşleme Döngüsü Sayacı",
		"IPT_08_3": "Catalyst Monitor Tamamlama Banka 1'i Sayar",
		"IPT_08_4": "Karşılaşılan Katalizör İzleme Koşulları Banka 1'i Sayıyor",
		"IPT_08_5": "Catalyst Monitor Tamamlama Sıra 2'yi Sayar",
		"IPT_08_6": "Karşılaşılan Katalizör İzleme Koşulları Banka 2'yi Sayar",
		"IPT_08_7": "O2 Sensör İzleme Tamamlama Sayımları Sıra 1",
		"IPT_08_8": "O2 Sensörü İzleme Koşulları Karşılaşılan Sayımlar Sıra 1",
		"IPT_08_9": "O2 Sensör İzleme Tamamlama Sayımları Sıra 2",
		"IPT_08_10": "O2 Sensörü İzleme Koşulları Karşılaşılan Sayımlar Sıra 2",
		"IPT_08_11": "EGR ve/veya VVT İzleme Tamamlama Koşulu Sayımları",
		"IPT_08_12": "EGR ve/veya VVT İzleme Koşulları Karşılaşılan Sayımlar",
		"IPT_08_13": "AIR Monitor Tamamlanma Durumu Sayımları (İkincil Hava)",
		"IPT_08_14": "AIR Monitor Karşılaşılan Sayım Koşulları (İkincil Hava)",
		"IPT_08_15": "EVAP İzleme Tamamlama Koşulu Sayımları",
		"IPT_08_16": "EVAP İzlenen Koşullar Karşılaşılan Sayımlar",
		"IPT_08_17": "İkincil O2 Sensörü İzleme Tamamlama Sayımları Sıra 1",
		"IPT_08_18": "İkincil O2 Sensörü İzleme Koşulları Karşılaşılan Sayımlar Sıra 1",
		"IPT_08_19": "İkincil O2 Sensörü İzleme Tamamlama Sayımları Sıra 2",
		"IPT_08_20": "İkincil O2 Sensörü İzleme Koşulları Karşılaşılan Sayımlar Sıra 2",
		
		"IPT_08_des_1": "aracın belirtilen OBD izleme koşullarında (genel payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_08_des_2": "motorun çalıştırılma sayısını görüntüler.",
		"IPT_08_des_3": "bir katalizör sistemi sıra 1 arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_4": "aracın belirtilen katalizör izleme koşullarında (payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_08_des_5": "bir katalizör sistemi sıra 2 arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_6": "aracın belirtilen katalizör izleme koşullarında (payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_08_des_7": "bir oksijen sensörü sıra 1 arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_8": "aracın belirtilen oksijen sensörü izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler.",
		"IPT_08_des_9": "bir oksijen sensörü sıra 2 arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_10": "aracın belirtilen oksijen sensörü izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler.",
		"IPT_08_des_11": "bir EGR/VVT sistemi arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_12": "aracın belirtilen EGR/VVT sistemi izleme koşullarında (payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_08_des_13": "bir AIR sistemi arızasının tespit edilmesi için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_14": "aracın belirtilen AIR sistemi izleme koşullarında (payda) çalıştırılma sayısını görüntüler.",
		"IPT_08_des_15": "0,020“ (veya 0,040”) EVAP sistemi kaçak arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_16": "aracın belirtilen EVAP sistemi kaçak arızası izleme koşullarında (payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_08_des_17": "ikinci bir oksijen sensörü sıra 1 arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_18": "aracın belirtilen ikincil oksijen sensörü izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler.",
		"IPT_08_des_19": "bir ikincil oksijen sensörü sıra 2 arızalarının tespit edilmesi için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_08_des_20": "aracın belirtilen ikincil oksijen sensörü izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler.",
		
		"IPT_0B_1": "OBD İzleme Koşullarında Karşılaşılan Sayımlar",
		"IPT_0B_2": "Ateşleme Döngüsü Sayacı",
		"IPT_0B_3": "NMHC Catalyst Monitor Tamamlanma Durumu Sayımları",
		"IPT_0B_4": "NMHC Catalyst Monitor Karşılaşılan Sayım Koşulları",
		"IPT_0B_5": "NOx/SCR Catalyst Monitor Tamamlanma Durumu Sayımları",
		"IPT_0B_6": "NOx/SCR Catalyst Monitor Karşılaşılan Sayım Koşulları",
		"IPT_0B_7": "NOx Adsorber Monitor Tamamlanma Durumu Sayımları",
		"IPT_0B_8": "NOx Adsorber Monitor Karşılaşılan Sayım Koşulları",
		"IPT_0B_9": "PM Filtre İzleme Tamamlama Koşulu Sayımları",
		"IPT_0B_10": "PM Filtre İzleme Koşulları Karşılaşılan Sayımlar",
		"IPT_0B_11": "Egzoz Gazı Sensörü İzleme Tamamlanma Durumu Sayımları",
		"IPT_0B_12": "Egzoz Gazı Sensörü Monitör Karşılaşılan Sayım Koşulları",
		"IPT_0B_13": "EGR ve/veya VVT İzleme Tamamlama Koşulu Sayımları",
		"IPT_0B_14": "EGR ve/veya VVT İzleme Koşulları Karşılaşılan Sayımlar",
		"IPT_0B_15": "Takviye Basıncı Monitörü Tamamlanma Durumu Sayımları",
		"IPT_0B_16": "Takviye Basıncı İzleme Koşulları Karşılaşılan Sayımlar",
		"IPT_0B_17": "Yakıt Monitörü Tamamlanma Durumu Sayımları",
		"IPT_0B_18": "Karşılaşılan Yakıt İzleme Koşulları Sayımları",
		
		"IPT_0B_des_1": "aracın belirtilen OBD izleme koşullarında (genel payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_0B_des_2": "motorun çalıştırılma sayısını görüntüler.",
		"IPT_0B_des_3": "bir NMHC katalizör sistemi arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_0B_des_4": "aracın belirtilen NMHC katalizör izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler.",
		"IPT_0B_des_5": "bir NOx katalizör sistemi arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_0B_des_6": "aracın belirtilen NOx katalizörü izleme koşullarında (payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_0B_des_7": "bir NOx adsorber sistemi arızasının tespit edilmesi için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_0B_des_8": "aracın belirtilen NOx adsorber izleme koşulları paydasında kaç kez çalıştırıldığını görüntüler.",
		"IPT_0B_des_9": "bir PM filtre sistemi arızasının tespit edilmesi için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_0B_des_10": "aracın belirtilen PM filtre izleme koşulları paydasında kaç kez çalıştırıldığını görüntüler.",
		"IPT_0B_des_11": "bir egzoz gazı sensörü arızasının tespit edilmesi için gerekli tüm koşulların kaç kez karşı karşıya kaldığını görüntüler (pay)",
		"IPT_0B_des_12": "aracın belirtilen egzoz gazı sensörü izleme koşullarında (payda) kaç kez çalıştırıldığını gösterir.",
		"IPT_0B_des_13": "bir EGR/VVT sistem arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_0B_des_14": "aracın belirtilen EGR/VVT sistemi izleme koşullarında (payda) çalıştırılma sayısını gösterir.",
		"IPT_0B_des_15": "bir takviye basınç sistemi arızasını tespit etmek için gerekli tüm koşulların kaç kez karşılaşıldığını görüntüler (pay).",
		"IPT_0B_des_16": "aracın belirtilen takviye basınç sistemi izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler.",
		"IPT_0B_des_17": "bir yakıt sistemi arızasını tespit etmek için gerekli tüm koşulların kaç kez karşı karşıya kaldığını görüntüler (pay).",
		"IPT_0B_des_18": "aracın belirtilen yakıt sistemi izleme koşullarında (payda) kaç kez çalıştırıldığını görüntüler."
	}
}