// 匈牙利语
var i18n = {
  "mt": "nap",
  "xs": "Óra",
  "fz": "Percek",
  "wxts": "Tippek",
  "zzjz": "betöltés...",
  "noData": "NO DATA",
  "jchj": "Bejelentkezési környezet ellenőrzése",
  "ckfw": "Referencia tartomány",
  "bbgl": {
    "bbts": "Verziófrissítési emlékeztető",
    "official": "Új funkciók jelentek meg. Kérjük, látogasson el a hivatalos webhelyre a legújabb verzió letöltéséhez és frissítéséhez.",
    "apple": "Új funkciók jelentek meg. Kérjük, keresse fel az App Store-t a frissített verzió letöltéséhez.",
    "google": "Új funkciók jelentek meg. Kérjük, keresse fel a Google Playt a frissített verzió letöltéséhez."
  },
  "uds": {
    "uds0001": "Modul kiválasztása",
    "uds0002": "Válassza ki az olvasandó modult",
    "uds0003": "A lista a kiválasztott márka összes támogatott modulját tartalmazza, javasolt csak az autóban már meglévő modulokat kiválasztani. Azonban minden modul kiválasztható. A rendszer automatikusan felismeri az autóban ténylegesen található egységeket .",
    "uds0004": "Összes kijelölése",
    "uds0005": "Összes kijelölés törlése",
    "uds0006": "Diagnosztika indítása",
    "uds0007": "Vendor Custom"
  },
  "yjdl": {
    "yxdl": "Bejelentkezés e-mailben",
    "dlts": "Először írja be a Captcha grafikát, majd kapja meg a Captcha e-mailt",
    "sryx": "Kérjük, adja meg e-mail címét",
    "sryzm": "Kérjük, írja be a Captcha-t",
    "xyb": "Következő",
    "xgyx": "Postaláda módosítása",
    "yxdz": "E-mail cím",
    "fsyzm": "hozzáférési kód küldése e-mailre",
    "yzm": "Hozzáférési kód",
    "cxfs": "másodpercek az újraküldéshez",
    "dl": "Bejelentkezés",
    "srtxyzm": "Adja meg a bal oldali Captcha grafikát",
    "yxbzq": "Az e-mail cím hibás",
    "txyzmbzq": "A Captcha grafika hibás",
    "fsdx": "Captcha küldése",
    "yxyzmfscg": "A Captcha e-mail sikeresen elküldve",
    "yxbky": "Az e-mail küldése rendellenes! Kérjük, ellenőrizze, hogy helyesen adta-e meg az e-mail címet, és hogy az e-mail megfelelően fogadható-e.",
    "zzyz": "Ellenőrzés",
    "yzmcw": "Az e-mail Captcha hibás",
    "clxxgl": "Járműinformáció-kezelés",
    "gxxx": "Információ frissítése",
    "dlcg": "Bejelentkezés sikeres",
    "dlsb": "A bejelentkezés sikertelen",
    "clxx": "Járműinformáció",
    "czxx": "Az autó tulajdonosának adatai",
    "wdl": "Nincs bejelentkezve",
    "cl": "Jármű"
  },

  "OBDxncs": {
    "bt": "Adapterek összehasonlítása",
    "fbt": "nagyobb gyorsabb",
    "zjsd": "Optimális sebesség",
    "dqsd": "Jelenlegi sebesség",
    "xzmc": "Az ECU-ból a paraméterek másodpercenkénti olvasási sebessége (egység: paraméter/másodperc)",
    "sec_dt": "Galaxy Note 8 és Pixel 2 segítségével tesztelve",
    "sec_dd1": "(1) A Wi-Fi adapterek általában nem ajánlottak Androidhoz, mivel a legtöbb telefon használat közben elveszíti adatkapcsolatát az internettel.",
    "sec_dd2": "(2) Minden tesztelt adapter szabványos Bluetooth, kivéve, ha a WiFi, USB vagy BLE a nevük része",
    "text2": "Az OBD összehasonlítása"
  },

  "tsxx": {
    "qxz": "választás",
    "qsr": "Kérem írja be",
    "qqr": "Megerősítés",
    "qqx": "Mégse",
    "notConnected": "Kérjük, először csatlakoztassa az eszközt",
    "save": "Az űrlap mentése sikeresen.",
    "dsyh": "Alapjárati üzemanyag-fogyasztás az aktuális pillanatban, amikor a jármű áll, az üzemanyag-fogyasztást jelenti, statisztikai egységként az időt.",
    "xsyh": "A vezetési üzemanyag-fogyasztás az aktuális pillanatban mért üzemanyag-fogyasztást jelenti, amikor a jármű vezetési állapotban van, és a távolságot veszi statisztikai egységnek.",
    "pjyh": "Az átlagos üzemanyag-fogyasztás a jármű 100 kilométerére eső üzemanyag-fogyasztást jelenti ezen vezetési folyamat során, és csak 1 km-nél hosszabb vezetés után jelenik meg.",
    "cqyh": "A hosszú távú üzemanyag-fogyasztás a jármű által az APP működése során 100 kilométeren megtett üzemanyag-fogyasztást jelenti.",
    "yhsupport": "Ez az autó nem támogatja az üzemanyag-fogyasztás kijelzését",
    "cg": "siker",
    "noTrouble": "Gratulálunk, autója hibátlan, csak így tovább.",
    "noVin": "Kérjük, adja meg a 17 jegyű keretszámot, hogy jobb szolgáltatást tudjunk nyújtani.",
    "gzzsd": "A MIL a hibajelző lámpa rövidítése. Ha a MIL lámpa világít, az azt jelenti, hogy a motorrendszer hibásan működik. A MIL jelzőfény világításának oka az lehet, hogy túl sok szénlerakódás van a motor belsejében. fojtószelep vagy a motor, vagy a keverék aránya kibillent az oxigénérzékelő meghibásodása után, vagy a motor lámpa világít a benzin rossz üzemanyagminősége és a jármű elégtelen égése miatt.",
    "noDevelopment": "Fejlesztés alatt, maradj velünk. ",
    "zc": "Jelenleg tesztelhető",
    "noSupport": "Jelenleg nem tesztelhető",
    "noNetwork": "Az Ön hálózata jelenleg nem érhető el. A hálózat nem befolyásolja az élményt.",
    "jy": "Letiltva",
    "ywc": "Állapotteszt befejezve",
    "noCompelte": "Az állapotteszt nem fejeződött be",
    "noSupportPid": "Az Ön járművében nincs ilyen teszt!",
    "useReminders": "Emlékeztető: A szünet után nagyíthat vagy barangolhat úgy, hogy ujját csúsztatja a csúszkán vagy az érintőképernyőn.",
    "noCompelteDes": "Ha a kész állapot tesztelhető, de nem fejeződött be, akkor a következő intézkedések tételesen megtehetők: teljes vezetés, a jármű karbantartása, a szerelvény tisztítása, az ECU frissítése, stb. Remélhetőleg a vezetési folyamat a jövőben az előírásoknak megfelelően üzemeltetjük, és rendszeres karbantartást végeznek.",
    "fgf": "Ez a funkció kizárólag a hivatalos termékekre vonatkozik, kérjük, vásárlás után használja!",
    "b25": "Ez a funkció kizárólag a B25-re vonatkozik, kérjük, használja a vásárlás után!"
  },

  "pid": {
    "dsyh": "Üresjárati üzemanyag-fogyasztás",
    "xsyh": "üzemanyag-fogyasztás",
    "ssyh": "Átlagos fogyasztás",
    "pjyh": "Azonnali fogyasztás",
    "cqyh": "Hosszú távú üzemanyag-fogyasztás",
    "pjsd": "Átlagsebesség",
    "xslc": "Megtett távolság",
    "DTC_legnth": "Az ECU-ban tárolt DTC-k száma",
    "MIL": "Hibajelző lámpa állapota",
    "mil_0": "világítás kikapcsolva",
    "mil_1": "fény világít",
    "shxt": "Tűzkimaradás figyelése",
    "ryxt": "Üzemanyagrendszer-felügyelet",
    "zhzj": "Átfogó komponens felügyelet",

    "fdjlx": "Motortípus",
    "ysfdj": "kompressziós gyújtás",
    "dhfdj": "szikragyújtás",
    "chj": "Katalizátorfigyelés",
    "jrchj": "Fűtött katalizátor figyelése",
    "zfxt": "Elpárolgási rendszer figyelése",
    "eckqxt": "Másodlagos levegőrendszer felügyelete",
    "ktxtzlj": "A/C rendszer hűtőközeg-felügyelet",
    "ycgqjrq": "Oxigénszenzoros fűtés figyelése",
    "ycgqjk": "Oxigénérzékelő figyelése",
    "erg": "EGR/VVT rendszerfelügyelet",
    "NMHC": "NMHC Catalyst Monitoring",
    "NOx": "NOx/SCR monitorozás",
    "yl": "Fenntartva",
    "zyyl": "Boost Pressure monitoring",
    "fqcgq": "Kipufogógáz-érzékelő figyelése",
    "pmglq": "PM-szűrő Monitorfigyelés"
  },

  "sygl": {
    "xieyi": "Protokoll",
    "tips1": "Csatlakoztassa az eszközt",
    "tips2": "Kérjük, kapcsolja be a Bluetooth-t! Súgó megtekintése",
    "tips3": "Nem találja az eszközt? Súgó megtekintése",
    "tips4": "Kérjük, kapcsolja be a helyszolgáltatásokat",
    "tips5": "Univerzális",
    "tips6": "Költséghatékony verzió",
    "sdlj": "Kapcsolat manuális kiválasztása"
  },

  "djz": {
    "noData": "Jelenleg nincs kimerevített képkocka adat",
    "previousFrame": "Previous Frame",
    "nextFrame": "Next Frame"
  },

  "fwgl": {
    "ybp": "Irányítópult",
    "UDS": "Egységes diagnosztikai szolgáltatás (teszt)",
    "UDS_des": "Egységes járműdiagnosztikai szolgáltatás, több ECU és több funkció biztosítása",
    "DTC": "DTC figyelés",
    "DTC_des": "Professzionális megoldások biztosítása a jármű hibakódjaira",
    "xcfx": "Utazás elemzése",
    "xcfx_des": "Elemezze minden utazási adatait",
    "xncs": "Jármű teljesítményteszt",
    "xncs_des": "Professzionális járműteljesítmény-elemzési jelentés biztosítása",
    "sssjl": "valós idejű adatfolyam",
    "sssjl_des": "Aktuális hajtáslánc-diagnosztikai adatok kérése",
    "gzzsd": "Hibajelző észlelése",
    "gzzsd_des": "A jármű működésével kapcsolatos információkat biztosít a hibajelző lámpa be- vagy kikapcsolása után",

    "pid0141": "Diagnosztikai kész állapot",
    "pid0141_des": "Megmutatja a jármű felügyeleti állapotát a DTC törlése óta, valamint az aktuális menetciklus-figyelő működési állapotát",
    "$05": "Oxigénérzékelő megfigyelési eredményei",
    "$05_des": "Olvassa el a jármű oxigénérzékelőjének ellenőrzésének vizsgálati eredményeit",
    "$06": "Speciális megfigyelési eredmények",
    "$06_des": "Hozzáférés engedélyezése a fedélzeti diagnosztikai megfigyelési tesztek eredményeihez meghatározott alkatrészek/rendszerek esetében.",
    "$09": "Járműinformációk",
    "$09_des": "Olvassa el a járműspecifikus információkat és információkat",

    "clnj": "",
    "clnj_des": "",

    "obdTest": "OBD teljesítményteszt",
    "obdTest_des": "Tesztelje az OBD különböző teljesítménymutatóit automatizált tesztelőeszközökkel.",
    "djz": "Freeze Frame",
    "djz_des": "Ha egy hibakód megjelenik a kipufogórendszerben, az ECU tárolja az adatokat, amikor megjelenik a hibakód",
    "yjjc": "Egy kattintással teljes járműérzékelés",
    "yjjc_des": "Az összes járműérzékelő adat, járműinformáció, hibakód, kimerevítő kép és járműfigyelő információ átfogó észlelése."
  },

  "yjjc": {
    "cljkxx": "járműfigyelő információ",
    "xx_09": "Járműadatok észlelése",
    "xx_03": "Hibainformációk észlelése",
    "xx_01": "Járműfigyelő információ észlelése",
    "xx_02": "A kimerevített képkocka információinak észlelése",
    "xx_05": "Az oxigénérzékelő információinak észlelése",
    "xx_06": "Speciális megfigyelési eredmények információinak olvasása"
  },

  "ybpgl": {
    "dcdy": "Akkumulátorfeszültség",
    "xhyb": "Sebességmérő",
    "yhyb": "Üzemanyag-fogyasztás mérő",
    "zdyyb": "Egyéni mérő",
    "xz": "Irányítópult hozzáadása",
    "bj": "Irányítópult szerkesztése",
    "sc": "Irányítópult törlése",
    "delete_tips": "Biztosan törli az irányítópultot?"
  },


  "status": {
    "1000": "Bluetooth nincs bekapcsolva",
    "1001": "Bluetooth ki van kapcsolva",
    "1002": "Várakozás az üzemanyag-megtakarításra",
    "1003": "OBD keresése",
    "1004": "OBD csatlakoztatása",
    "1005": "Bluetooth csatlakoztatva van",
    "1006": "Az adatok írása sikeresen megtörtént",
    "1007": "Nem sikerült beírni az adatokat",
    "1008": "Értesítés sikeres engedélyezése",
    "1009": "Nem található eszköz"
  },


  "szgl": {
    "bt": "Beállítás",
    "label1": "Nyelv",
    "value1": "Rendszer követése",
    "label2": "Adatvédelmi szabályzat",
    "label3": "Kapcsolódási segítség",
    "label4": "Névjegy",
    "label5": "Hivatalos bevásárlóközpont",
    "value5": "1688 Mall",
    "label6": "Verzió",
    "cjwt": "Gyakori probléma",
    "unittitle": "Unit",
    "unitvalue1": "Metrikus rendszer",
    "unitvalue2": "Imperial Units",
    "unitinfo": "Megerősíti, hogy váltson-e egységet?"
  },

  "yygl": {
    "label": "Rendszer követése",
    "des": "Bekapcsolás után automatikusan a rendszer nyelvének megfelelően lesz beállítva",
    "en": "angol",
    "zh": "egyszerűsített kínai",
    "zwft": "hagyományos kínai",
    "es": "spanyol",
    "kr": "koreai",
    "ru": "orosz",
    "ja": "japán",
    "it": "olasz",
    "hi": "hindi",
    "pt": "portugál",
    "de": "német",
    "fr": "francia",
    "nl": "holland",
    "fi": "finn",
    "pl": "lengyel",
    "bn": "bengáli",
		"hu": "magyar",
		"cs": "cseh",
		"th": "thai",
		"tr": "török",
		"ms": "maláj",
		"ro": "román",
		"sv": "svéd",
		"da": "dán"
  },


  "obdManage": {
    "bt": "OBD menedzsment",
    "search_tip": "Kérjük, keressen újra, vagy vásárolja meg termékeinket",
    "buy_tip": "Kérjük, menjen a plázába vásárolni",
    "searchAgain": "Keresés újra",
    "nearBy": "Közeli berendezések",
    "ls": "Történelmi berendezések",
    "bz": "Súgó megtekintése",
    "del": "Törlés",
    "delConfirm": "Biztosan törli ezt a rekordot?",
    "switched": "A készülék váltás előtt áll, biztos vagy benne?",
    "qrxx": "Kérjük, ellenőrizze, hogy a mobiltelefon Bluetooth és helyinformációs kapcsolója be van-e kapcsolva.",
    "searchAgain_message": "Biztosan újrakeresi a közeli eszközöket?"
  },


  "gzjc": {
    "bt": "Diagnosztikai",
    "btn": "Tesztelés indítása",
    "des": "Indítsa el a jármű teljes vizsgálatát",
    "FaultCodeQuery": "Hibakód lekérdezés",
    "zzjc": "Tesztelés",
    "clearFaultCode": "Hibakód törlése",
    "kscz": "keresés",
    "fxgz": "Hibakód található",
    "notFound": "nincs probléma",
    "cxjc": "Újraellenőrzés",
    "modalTitle": "Biztosan törölni akarja a hibakódot?",
    "modalContent": "A hiba elhárítása előtt nem ajánlott tetszőlegesen törölni a hibakódot. A legtöbb ECU nem teszi lehetővé a hibakód törlését, amikor a motor jár. Hogy a hibakód törölhető-e vagy sem, az végső soron az ECU határozza meg. A hibakódok törlése nem igazán megoldás a problémára.",
    "sdjc": "Mélységi vizsgálati jelentés",
    "num": "Hibakódok száma",
    "gzmxx": "A hibakód részletei",
    "label1": "kategória",
    "label2": "Hibakód magyarázata",
    "definition_03": "Diagnosztikai hibakódok",
    "definition_07": "Függőben lévő diagnosztikai hibakódok",
    "definition_0A": "Állandó diagnosztikai hibakódok",
    "03_des": "Amikor az ECU (Vehicle Control Unit) rendellenességet észlel, egy hibakód tárolódik a memóriában. Ez a hibakód a legutóbbi vezetési folyamat során észlelt rendellenes helyzetre utal. Ezeket a hibakódokat a memória tárolja. egy ideig, amikor a hibakód ismét megjelenik, frissítse a megőrzési időszakot.",
    "07_des": "Ez egy vezetés közbeni nyugtázatlan anomália. Ha a rendellenesség ismétlődik és azonosításra kerül, az ideiglenes hibakód megerősített hibakódként lesz besorolva. Ha nem menti, akkor a motor leállításakor törlődik.",
    "0A_des": "Mivel a múltbeli DTC-k előzményeit mutatja, nem a jármű aktuális állapotát mutatja. Előfordulhat, hogy nem lehet programozottan törölni a megfelelő DTC-ket.",
    "sys_P": "Erőátviteli rendszer (a gyártó által meghatározott)",
    "sys_B": "Karosszériarendszer (a gyártó által meghatározott)",
    "sys_C": "Alváz felfüggesztési rendszer (gyártó által meghatározott)",
    "sys_U": "Hálózati kommunikációs rendszer (gyártó által meghatározott)",
    "zzs": "Minden autógyártó"
  },

  "clgl": {
    "bt": "Az én autóm",
    "info1": "Alapvető autóinformációk",
    "clpp": "Autómárkák",
    "xh": "Autómodell",
    "nk": "Év",
    "rylx": "Üzemanyag típus",
    "info2": "Egyéb járműinformációk",
    "atdp": "Kommunikációs protokoll",
    "ati": "Adapter verzió",
    "vin": "Jármű azonosító száma",
    "cid": "Kalibrációs azonosítások",
    "cvn": "Kalibrálási ellenőrző számok",
    "ecu": "Elektronikus vezérlőegység",
    "ESN": "Motor sorozatszáma",
    "EROTAN": "kipufogógáz-előírás vagy típus-jóváhagyási szám",
    "FEOCNTR": "Üzemanyaggal működő motor működésű gyújtásciklus számláló",
    "obd": "OBDSUP"
  },

  "clbj": {
    "warn1": "Kérjük, adja meg a jármű márkáját",
    "warn2": "autómodell szükséges",
    "warn3": "az autó évjárata kötelező",
    "warn4": "vin is igényel",
    "warn5": "Kérjük, írja be a megfelelő járműazonosító számot",
    "warn6": "az autó tulajdonosának neve szükséges",
    "warn7": "telefon szükséges",
    "warn8": "Kérjük, adja meg a megfelelő telefonszámot",
    "warn9": "Kérjük, adja meg a helyes e-mail-címet",
    "bt": "OBD kapcsolat sikeres",
    "title_sub": "A következő információk nagyon fontosak a pontos diagnózishoz, hogy még jobb élményt nyújthassunk. Gondosan töltse ki.",
    "ts_vin": "A VIN-kód helye: általában a műszerfal bal oldalán, az első szélvédő bal alsó részén található; van még egy ajtó zsanéroszlop, egy ajtózár oszlop vagy az egyik oszlop, amelyhez csatlakoztatva van az ajtózár oszlopa; vagy a vezetőülés közelében lévő ajtó belül.",
    "vin": "Vin",
    "czxm": "Név",
    "lxdh": "Telefon",
    "lxyx": "E-mail"
  },
  "ota": {
    "bt": "OTA frissítés",
    "jcdxbb": "Új firmware-verzió észlelve",
    "gxnr": "Tartalom frissítése",
    "fxsm": "Frissítési utasítások",
    "fxsm_des": "Az OTA (over-the-air technológia) frissítés azt jelenti, hogy a mobil terminál távolról letölti a frissítési csomagot a szerveren az OBD firmware frissítéséhez. A frissítés nincs hatással járműve és vezetési biztonságára, kérjük, használja bátran Ha azt jelzi, hogy a frissítés meghiúsult, kérjük, ne lépjen ki az interfészből, helyezze be újra az OBD-t, és folytassa a frissítést.",
    "zysx": "Figyelem",
    "zysx_des": "Ne frissítsen vezetés közben, és ne távolítsa el vagy ne kapcsolja ki az OBD-t a frissítés során.",
    "mssj": "Frissítés most",
    "kssj": "Indítsa el a frissítést",
    "sjcg": "OTA frissítés sikeres",
    "kqqxty": "Új élmény megnyitása",
    "xzgj": "Firmware letöltése",
    "zzxr": "Írás",
    "zzsj": "Frissítés",
    "zzjy": "Az integritás ellenőrzése",
    "sjsb": "Nem sikerült a frissítés, próbáld újra"
  },

  "xcfx": {
    "ksxc": "Kezdje el az utazást",
    "jsxc": "Végezze be az utazást",
    "lsjl": "Előzmény rekord",
    "zlc": "Összes futásteljesítmény",
    "hs": "Időigényes",
    "kssj": "Kezdési idő",
    "zyh": "Összes liter"
  },

  "xncs": {
    "jsxn": "Gyorsított",
    "scxn": "Fékezés",
    "jlxn": "Távolság",
    "des1": "Sebességteszt tartomány",
    "des2": "sebesség fékezéskor",
    "des3": "teszt távolság",
    "aqtx": "kérem, ügyeljen a vezetés biztonságára!",
    "kscs": "Tesztelés indítása",
    "cxcs": "Újrateszt",
    "tz": "Stop",
    "tip1": "Kérjük, állítsa be a jármű sebességét",
    "tip2": "Kérjük, lépjen a gázpedálra, hogy felgyorsuljon",
    "tip2_end": "Fent",
    "tip3": "Kérjük, lépjen a fékre, hogy csökkentse a sebességet",
    "tip4": "Kérjük, vezessen",
    "tip5": "Utazott",
    "max_sd": "Csúcssebesség",
    "max_jsd": "Maximális gyorsulás",
    "max_zs": "Maximális sebesség",
    "tx1": "A kezdősebesség nem lehet nagyobb, mint a végsebesség",
    "tx2": "Kérjük, adja meg a 0-nál nagyobb fékezési sebességet",
    "tx3": "Kérjük, töltse ki a teszt távolságot, amely nagyobb, mint 0"
  },

  "bzxx": {
    "title1": "1. lépés: Indítsa el a járművet",
    "title2": "2. lépés: Csatlakoztassa az eszközt",
    "title3": "3. lépés: Kapcsolja be a Bluetooth-t és a helymeghatározást",
    "title4": "4. lépés: Nyissa meg az APP-t",
    "title5": "5. lépés: Csatlakoztassa az eszközt",
    "text1": "Keresse meg a jármű OBD interfészének helyét. Az OBD interfész egy 16 érintkezős női interfész. Az interfész trapéz alakú. Egyes modelleken az OBD interfészen burkolat található. A gyakori OBD-portok fekete, fehér vagy kék színűek. A hely általában a belső kárpitpanelben a kormánykerék alatt, a vezető térdeinek közelében található. Az OBD interfész elhelyezkedése a különböző modelleknél és modelleknél eltérő lehet. A következő ábra az OBD interfész lehetséges helyét mutatja:",
    "text2": "Miután megtalálta az OBD interfészt, csatlakoztassa az eszközt az OBD interfészhez. Győződjön meg arról, hogy teljesen be van dugva (sok autó kb. félidőben be van dugva, és a tápellátás be van kapcsolva, de előfordulhat, hogy a jeltűk nincsenek csatlakoztatva), és a piros bekapcsolásjelző vagy a képernyő világít.",
    "text3": "Kapcsolja be a Bluetooth és a helymeghatározás kapcsolóit a telefonján. Módszer: Csúsztassa lefelé az ujját a telefon képernyőjének tetején, nyissa meg a helyi menüt, majd kattintson a Bluetooth és helyadatok lehetőségre. Kapcsolja be a Bluetooth-t iOS-eszközén.",
    "text4": "Nyissa meg az alkalmazást, és engedélyezze, hogy az alkalmazás használja a helyadatokat.",
    "text5": "A fenti lépések végrehajtása után lépjen be az APP-ba, az APP automatikusan átvizsgálja az OBD-eszközt, és megkérdezi, hogy csatlakoztassa-e az eszközt. Az iOS-eszköz megkérdezi, hogy engedélyezi-e a hozzáférést a címhez, kattintson az Engedélyezés gombra.",
    "text6": "Válassza ki a csatlakoztatni kívánt eszközt, és kattintson a csatlakozáshoz. Sikeres csatlakozás után az APP kezdőlapján megjelenik az OBD eszköz neve, Bluetooth-címe, és a műszerfalon megjelenik egy olvasás."
  },

  "06fw": {
    "MID": "Monitor neve",
    "TID": "Teszt neve",
    "CID": "Alkatrész száma",
    "O2Sensor": "O2 érzékelő neve",
    "MIN": "Minimális határ",
    "MAX": "Maximális határ",
    "CURRENT": "Tesztérték"
  },

  "09fw": {
    "ipt": "Használat közbeni teljesítménykövetés",
    "IPT_08_1": "Az OBD megfigyelési körülményei között előfordult számok",
    "IPT_08_2": "Gyújtásciklus-számláló",
    "IPT_08_3": "A katalizátor-figyelő befejezett számai, 1. bank",
    "IPT_08_4": "Catalyst Monitor Conditions Encountered Conditions Counts 1 Bank",
    "IPT_08_5": "A katalizátor-figyelő befejezett számai, 2. bank",
    "IPT_08_6": "Catalyst Monitor Conditions Encountered Conditions Counts 2 Bank",
    "IPT_08_7": "O2 szenzorfigyelő befejezett számlálások, 1. bank",
    "IPT_08_8": "Az O2 érzékelő megfigyelési körülményei számlál 1. bank",
    "IPT_08_9": "O2 szenzorfigyelő befejezési számlálja, 2. bank",
    "IPT_08_10": "Az O2-érzékelő megfigyelési körülményei számlál 2. bank",
    "IPT_08_11": "EGR- és/vagy VVT-monitor befejezési állapotának száma",
    "IPT_08_12": "Az EGR- és/vagy VVT-monitorkörülmények száma",
    "IPT_08_13": "AIR Monitor befejezési állapotának száma (másodlagos levegő)",
    "IPT_08_14": "AIR Monitor Conditions Encounted Counts (Secondary Air)",
    "IPT_08_15": "Az EVAP-monitor befejezési feltételeinek száma",
    "IPT_08_16": "EVAP Monitor Conditions Encounted Counts",
    "IPT_08_17": "Másodlagos O2-érzékelő-figyelő befejezése számlálja, 1. bank",
    "IPT_08_18": "A másodlagos O2-érzékelő megfigyelési körülményei számlál 1. bank",
    "IPT_08_19": "Másodlagos O2-érzékelő-figyelő befejezése számlálja, 2. bank",
    "IPT_08_20": "A másodlagos O2-érzékelő megfigyelési körülményei számlál 2. bank",

    "IPT_08_des_1": "megjeleníti, hogy a járművet hányszor üzemelték a megadott OBD-felügyeleti feltételek mellett (általános nevező).",
    "IPT_08_des_2": "megjeleníti a motor beindításának számát.",
    "IPT_08_des_3": "az 1. bank katalizátorrendszerének hibájának észleléséhez szükséges összes feltétel azon alkalmak számát jeleníti meg (számláló).",
    "IPT_08_des_4": "megjeleníti, hogy a jármű hányszor működött a megadott katalizátor-felügyeleti körülmények között (nevező).",
    "IPT_08_des_5": "megjeleníti, hogy hányszor fordult elő a katalizátorrendszer 2. banki hibájának észleléséhez szükséges összes feltétel (számláló).",
    "IPT_08_des_6": "megjeleníti, hogy a jármű hányszor működött a megadott katalizátor-felügyeleti körülmények között (nevező).",
    "IPT_08_des_7": "megjeleníti, hogy hányszor fordult elő az oxigénérzékelő 1. banki hibájának észleléséhez szükséges összes körülmény (számláló).",
    "IPT_08_des_8": "megjeleníti, hogy a jármű hányszor működött a megadott oxigénérzékelő felügyeleti feltételek mellett (nevező).",
    "IPT_08_des_9": "megjeleníti, hogy hányszor jelentkezett az oxigénérzékelő 2. banki hibájának észleléséhez szükséges összes körülmény (számláló).",
    "IPT_08_des_10": "megjeleníti, hogy a jármű hányszor működött a megadott oxigénérzékelő felügyeleti feltételek mellett (nevező).",
    "IPT_08_des_11": "az EGR/VVT rendszer meghibásodásának észleléséhez szükséges összes körülmény előfordulásának számát mutatja (számláló).",
    "IPT_08_des_12": "megjeleníti, hogy a jármű hányszor működött a megadott EGR/VVT rendszer megfigyelési feltételei között (nevező).",
    "IPT_08_des_13": "az AIR rendszer hibájának észleléséhez szükséges összes körülmény előfordulásának számát mutatja (számláló).",
    "IPT_08_des_14": "megjeleníti, hogy a jármű hányszor működött a megadott AIR rendszer megfigyelési feltételei között (nevező).",
    "IPT_08_des_15": "megjeleníti a 0,020” (vagy 0,040” EVAP rendszerszivárgás észleléséhez szükséges összes körülmény előfordulásának számát (számláló).)",
    "IPT_08_des_16": "megjeleníti, hogy a járművet hányszor üzemelték a megadott EVAP-rendszer szivárgási hibás működésének megfigyelési körülményei között (nevező).",
    "IPT_08_des_17": "megjeleníti azon alkalmak számát, amikor a másodlagos oxigénérzékelő 1. banki hibájának észleléséhez szükséges összes körülmény előfordult (számláló).",
    "IPT_08_des_18": "megjeleníti, hogy a jármű hányszor működött a megadott másodlagos oxigénérzékelő felügyeleti feltételek között (nevező).",
    "IPT_08_des_19": "megjeleníti azon alkalmak számát, ahányszor a másodlagos oxigénérzékelő 2. bankcsoportjának hibáinak észleléséhez szükséges összes körülmény jelentkezett (számláló).",
    "IPT_08_des_20": "megjeleníti, hogy a jármű hányszor működött a megadott másodlagos oxigénérzékelő felügyeleti feltételek mellett (nevező).",

    "IPT_0B_1": "Az OBD megfigyelési körülményei között előfordult számok",
    "IPT_0B_2": "Gyújtásciklus-számláló",
    "IPT_0B_3": "NMHC Catalyst Monitor Completion Condition Counts",
    "IPT_0B_4": "NMHC Catalyst Monitor Conditions Encounted Counts",
    "IPT_0B_5": "NOx/SCR katalizátorfigyelő befejezési állapotának száma",
    "IPT_0B_6": "NOx/SCR katalizátor-figyelő körülmények között előforduló számok",
    "IPT_0B_7": "NOx-adszorber-figyelő befejezési állapotának száma",
    "IPT_0B_8": "Az NOx adszorber figyelő körülményei előfordult száma",
    "IPT_0B_9": "PM Filter Monitor Completion Condition Conditions Counts",
    "IPT_0B_10": "PM Filter Monitor Conditions Encounted Counts",
    "IPT_0B_11": "Kipufogógáz-érzékelő ellenőrzésének befejezési állapotának száma",
    "IPT_0B_12": "Kipufogógáz-érzékelő-figyelő állapotok száma",
    "IPT_0B_13": "EGR- és/vagy VVT-monitor befejezési állapotának száma",
    "IPT_0B_14": "Az EGR- és/vagy VVT-monitorkörülmények száma",
    "IPT_0B_15": "A töltőnyomás-figyelő befejezési feltételeinek száma",
    "IPT_0B_16": "Töltőnyomás-ellenőrzési állapotok száma",
    "IPT_0B_17": "Üzemanyag-ellenőrzés befejezett állapotának száma",
    "IPT_0B_18": "Üzemanyag-figyelő állapotok száma",

    "IPT_0B_des_1": "megjeleníti, hogy a jármű hányszor működött a megadott OBD-felügyeleti feltételek mellett (általános nevező).",
    "IPT_0B_des_2": "megjeleníti a motor beindításának számát.",
    "IPT_0B_des_3": "az NMHC katalizátorrendszer meghibásodásának észleléséhez szükséges összes körülmény előfordulásának számát mutatja (számláló).",
    "IPT_0B_des_4": "megjeleníti, hogy a jármű hányszor működött a megadott NMHC-katalizátor-felügyeleti körülmények között (nevező).",
    "IPT_0B_des_5": "az NOx katalizátorrendszer meghibásodásának észleléséhez szükséges összes körülmény előfordulásának számát mutatja (számláló).",
    "IPT_0B_des_6": "megjeleníti, hogy a jármű hányszor működött a megadott NOx-katalizátor-ellenőrzési körülmények között (nevező).",
    "IPT_0B_des_7": "az NOx adszorber rendszer hibájának észleléséhez szükséges összes feltétel azon alkalmak számát jeleníti meg (számláló).",
    "IPT_0B_des_8": "megjeleníti, hogy a jármű hányszor működött a megadott NOx adszorber megfigyelési feltételeinek nevezőjében).",
    "IPT_0B_des_9": "megjeleníti azon alkalmak számát, amikor a PM szűrőrendszer meghibásodásának észleléséhez szükséges összes körülmény felmerült (számláló).",
    "IPT_0B_des_10": "megjeleníti, hogy a jármű hányszor működött a megadott PM-szűrő megfigyelési feltételeinek nevezőjében).",
    "IPT_0B_des_11": "megjeleníti a kipufogógáz-érzékelő hibás működésének észleléséhez szükséges összes körülmény előfordulásának számát (számláló)",
    "IPT_0B_des_12": "megjeleníti, hogy a jármű hányszor működött a megadott kipufogógáz-érzékelő felügyeleti feltételek mellett (nevező).",
    "IPT_0B_des_13": "az EGR/VVT rendszer meghibásodásának észleléséhez szükséges összes körülmény előfordulásának számát mutatja (számláló).",
    "IPT_0B_des_14": "megjeleníti, hogy a jármű hányszor működött a megadott EGR/VVT rendszer megfigyelési feltételei között (nevező).",
    "IPT_0B_des_15": "megjeleníti azon alkalmak számát, amikor a töltőnyomás-rendszer hibájának észleléséhez szükséges összes körülmény fennáll (számláló).",
    "IPT_0B_des_16": "megjeleníti, hogy a jármű hányszor működött a töltőnyomás-rendszer meghatározott felügyeleti feltételei között (nevező).",
    "IPT_0B_des_17": "az üzemanyagrendszer meghibásodásának észleléséhez szükséges összes körülmény előfordulásának számát mutatja (számláló).",
    "IPT_0B_des_18": "megjeleníti, hogy a járművet hányszor üzemelték a megadott üzemanyagrendszer-felügyeleti feltételek mellett (nevező)."
  }
}