// 马来语
var i18n = {
	"mt": "Hari",
	"xs": "Jam",
	"fz": "Minit",
	"wxts": "Petua",
	"zzjz": "memuatkan...",
	"noData": "TIADA DATA",
	"jchj": "Menyemak persekitaran log masuk",
	"ckfw": "Julat rujukan",
	"bbgl": {
		"bbts": "Peringatan kemas kini versi",
		"official": "Terdapat ciri baharu yang dikeluarkan, sila pergi ke tapak web rasmi untuk memuat turun dan menaik taraf versi terkini.",
		"apple": "Terdapat ciri baharu yang dikeluarkan, sila pergi ke App Store untuk memuat turun versi yang dinaik taraf.",
		"google": "Terdapat ciri baharu yang dikeluarkan, sila pergi ke Google Play untuk memuat turun versi yang dinaik taraf."
	},
	"uds": {
		"uds0001": "Pilih Modul",
		"uds0002": "Pilih modul untuk dibaca",
		"uds0003": "Senarai mengandungi semua modul yang disokong bagi jenama yang dipilih, adalah disyorkan untuk memilih hanya modul yang sedia ada pada kereta. Walau bagaimanapun, semua modul boleh dipilih. Sistem akan secara automatik mengesan unit yang sebenarnya terdapat pada kereta. .",
		"uds0004": "Pilih semua",
		"uds0005": "Batalkan Pilih Semua",
		"uds0006": "Mulakan Diagnosis",
		"uds0007": "Vendor Custom"
	},
	"yjdl": {
		"yxdl": "Log Masuk E-mel",
		"dlts": "Masukkan Captcha grafik dahulu, dan kemudian dapatkan e-mel Captcha",
		"sryx": "Sila masukkan e-mel anda",
		"sryzm": "Sila masukkan Captcha",
		"xyb": "Seterusnya",
		"xgyx": "Ubah suai peti mel",
		"yxdz": "Alamat e-mel",
		"fsyzm": "hantar kod akses ke e-mel",
		"yzm": "Kod Akses",
		"cxfs": "saat untuk menghantar semula",
		"dl": "Log masuk",
		"srtxyzm": "Masukkan Captcha grafik kiri",
		"yxbzq": "E-mel tidak betul",
		"txyzmbzq": "Captcha grafik tidak betul",
		"fsdx": "Menghantar Captcha",
		"yxyzmfscg": "E-mel Captcha berjaya dihantar",
		"yxbky": "Penghantaran e-mel adalah tidak normal! Sila semak sama ada alamat e-mel dimasukkan dengan betul dan sama ada e-mel itu boleh diterima seperti biasa.",
		"zzyz": "Mengesahkan",
		"yzmcw": "E-mel Captcha tidak betul",
		"clxxgl": "Pengurusan Maklumat Kenderaan",
		"gxxx": "Kemas kini maklumat",
		"dlcg": "Log masuk berjaya",
		"dlsb": "Log masuk gagal",
		"clxx": "Maklumat Kenderaan",
		"czxx": "Maklumat pemilik kereta",
		"wdl": "Tidak log masuk",
		"cl": "Kenderaan"
	},

	"OBDxncs": {
		"bt": "Perbandingan penyesuai",
		"fbt": "lebih besar bermakna lebih cepat",
		"zjsd": "Kelajuan optimum",
		"dqsd": "Kelajuan semasa",
		"xzmc": "Kadar di mana parameter dibaca daripada ECU sesaat (unit: parameter/saat)",
		"sec_dt": "Diuji dengan Galaxy Note 8 dan Pixel 2",
		"sec_dd1": "(1) Penyesuai Wi-Fi biasanya tidak disyorkan untuk Android, kerana kebanyakan telefon kehilangan sambungan datanya ke Internet semasa digunakan.",
		"sec_dd2": "(2) Semua penyesuai yang diuji ialah Bluetooth standard melainkan 'WiFi', 'USB' atau 'BLE' adalah sebahagian daripada namanya",
		"text2": "Perbandingan OBD"
	},

	"tsxx": {
		"qxz": "pilih",
		"qsr": "Sila masukkan",
		"qqr": "Sahkan",
		"qqx": "Batal",
		"notConnected": "Sila sambungkan peranti anda dahulu",
		"save": "Berjaya menyimpan borang.",
		"dsyh": "Penggunaan bahan api melahu merujuk kepada penggunaan bahan api pada saat semasa apabila kenderaan tidak bergerak, dengan masa sebagai unit statistik.",
		"xsyh": "Penggunaan bahan api memandu merujuk kepada penggunaan bahan api pada saat semasa apabila kenderaan berada dalam keadaan memandu, dan mengambil jarak sebagai unit statistik.",
		"pjyh": "Purata penggunaan bahan api merujuk kepada penggunaan bahan api bagi setiap 100 kilometer kenderaan semasa proses pemanduan ini, dan ia hanya dipaparkan selepas memandu lebih daripada 1 km.",
		"cqyh": "Penggunaan bahan api jangka panjang merujuk kepada penggunaan bahan api yang digunakan oleh kenderaan selama 100 kilometer semasa operasi APP.",
		"yhsupport": "Kereta ini tidak menyokong paparan penggunaan bahan api",
		"cg": "berjaya",
		"noTrouble": "Tahniah, kereta anda bebas kerosakan, sila teruskan.",
		"noVin": "Sila masukkan nombor bingkai 17 digit supaya kami dapat memberikan perkhidmatan yang lebih baik kepada anda.",
		"gzzsd": "MIL ialah singkatan dari Lampu Penunjuk Malfungsi. Apabila lampu MIL menyala, ini bermakna sistem enjin mungkin tidak berfungsi. Sebab lampu MIL menyala mungkin terdapat terlalu banyak pemendapan karbon di dalam injap pendikit atau enjin, atau nisbah campuran tidak seimbang selepas penderia oksigen gagal, atau lampu enjin menyala kerana kualiti bahan api petrol yang lemah dan pembakaran kenderaan yang tidak mencukupi.",
		"noDevelopment": "Dalam pembangunan, nantikan. ",
		"zc": "Sedang tersedia untuk ujian",
		"noSupport": "Pada masa ini tidak tersedia untuk ujian",
		"noNetwork": "Rangkaian anda tidak tersedia pada masa ini. Tiada rangkaian akan menjejaskan pengalaman anda.",
		"jy": "Dilumpuhkan",
		"ywc": "Ujian status selesai",
		"noCompelte": "Ujian status tidak selesai",
		"noSupportPid": "Kenderaan anda tidak mempunyai ujian ini!",
		"useReminders": "Peringatan: Selepas menjeda, anda boleh mengezum atau merayau dengan meleret jari anda pada peluncur atau pada skrin sentuh.",
		"noCompelteDes": "Sekiranya keadaan sedia boleh diuji tetapi tidak dilengkapkan, langkah-langkah berikut boleh diambil item demi item: memandu sepenuhnya, menyelenggara kenderaan, membersihkan pemasangan, menaik taraf ECU, dsb. Diharapkan proses pemanduan akan dikendalikan mengikut spesifikasi pada masa hadapan, dan penyelenggaraan tetap akan dijalankan.",
		"fgf": "Fungsi ini eksklusif untuk produk rasmi, sila gunakannya selepas membeli!",
		"b25": "Fungsi ini eksklusif untuk B25, sila gunakannya selepas membeli!"
	},

	"pid": {
		"dsyh": "Penggunaan Bahan Api Terbiar",
		"xsyh": "Penggunaan bahan api",
		"ssyh": "Purata Penggunaan",
		"pjyh": "Penggunaan Semerta",
		"cqyh": "Penggunaan bahan api jangka panjang",
		"pjsd": "Kelajuan purata",
		"xslc": "Jarak dipandu",
		"DTC_legnth": "# DTC disimpan dalam ECU ini",
		"MIL": "Status Lampu Penunjuk Kepincangan",
		"mil_0": "lampu padam",
		"mil_1": "lampu hidup",
		"shxt": "Pemantauan misfire",
		"ryxt": "Pemantauan sistem bahan api",
		"zhzj": "Pemantauan komponen menyeluruh",

		"fdjlx": "Jenis enjin",
		"ysfdj": "pencucuhan mampatan",
		"dhfdj": "pencucuhan percikan",
		"chj": "Pemantauan pemangkin",
		"jrchj": "Pemantauan mangkin dipanaskan",
		"zfxt": "Pemantauan sistem penyejatan",
		"eckqxt": "Pemantauan sistem udara kedua",
		"ktxtzlj": "Pemantauan penyejuk sistem A/C",
		"ycgqjrq": "Pemantauan pemanas sensor oksigen",
		"ycgqjk": "Pemantauan sensor oksigen",
		"erg": "Pemantauan Sistem EGR/VVT",
		"NMHC": "Pemantauan Pemangkin NMHC ",
		"NOx": "Pemantauan NOx/SCR",
		"yl": "Terpelihara",
		"zyyl": "Tingkatkan Pemantauan Tekanan",
		"fqcgq": "Pemantauan Sensor Gas Ekzos",
		"pmglq": "Pemantauan penapis PM"
	},

	"sygl": {
		"xieyi": "Protokol",
		"tips1": "Sambungkan peranti",
		"tips2": "Sila hidupkan Bluetooth! Lihat bantuan",
		"tips3": "Tidak dapat mencari peranti? Lihat bantuan",
		"tips4": "Sila hidupkan perkhidmatan lokasi",
		"tips5": " Universal",
		"tips6": "Versi kos efektif",
		"sdlj": "Pilih sambungan secara manual"
	},

	"djz": {
		"noData": "Pada masa ini tiada data bingkai beku",
		"previousFrame": "Bingkai Sebelumnya",
		"nextFrame": "Bingkai Seterusnya"
	},

	"fwgl": {
		"ybp": "Papan pemuka",
		"UDS": "Perkhidmatan Diagnostik Bersatu (Ujian)",
		"UDS_des": "Sediakan perkhidmatan diagnosis bersatu kenderaan, lebih banyak ECU dan lebih banyak fungsi",
		"DTC": "Pemantauan DTC",
		"DTC_des": "Sediakan penyelesaian profesional untuk kod kerosakan kenderaan",
		"xcfx": "Analisis Perjalanan",
		"xcfx_des": "Analisis setiap data perjalanan anda",
		"xncs": "Ujian Prestasi Kenderaan",
		"xncs_des": "Sediakan laporan analisis prestasi kenderaan profesional",
		"sssjl": "strim data masa nyata",
		"sssjl_des": "Minta data diagnostik rangkaian kuasa semasa",
		"gzzsd": "Pengesanan penunjuk kesalahan",
		"gzzsd_des": "Menyediakan maklumat pengendalian kenderaan selepas lampu kerosakan dihidupkan atau dimatikan",

		"pid0141": "Status Sedia Diagnostik",
		"pid0141_des": "Menyediakan status pemantauan kenderaan sejak DTC dikosongkan dan kitaran pemanduan semasa memantau status operasi",
		"$05": "Hasil pemantauan sensor oksigen",
		"$05_des": "Baca keputusan ujian pemantauan sensor oksigen kenderaan",
		"$06": "Hasil pemantauan khusus",
		"$06_des": "benarkan akses kepada keputusan ujian pemantauan Diagnostik Atas Papan untuk komponen/sistem tertentu.",
		"$09": "Maklumat Kenderaan",
		"$09_des": "Baca maklumat dan maklumat kenderaan khusus kenderaan",

		"clnj": "",
		"clnj_des": "",

		"obdTest": "Ujian prestasi OBD",
		"obdTest_des": "Uji pelbagai penunjuk prestasi OBD melalui alat ujian automatik.",
		"djz": "Bekukan Bingkai",
		"djz_des": "Apabila DTC muncul dalam sistem ekzos, ECU menyimpan data apabila DTC muncul",
		"yjjc": "Pengesanan kenderaan penuh satu klik",
		"yjjc_des": "Pengesanan menyeluruh semua data penderia kenderaan, maklumat kenderaan, kod masalah, bingkai beku dan maklumat pemantauan kenderaan."
	},

	"yjjc": {
		"cljkxx": "maklumat pemantauan kenderaan",
		"xx_09": "Mengesan maklumat kenderaan",
		"xx_03": "Mengesan maklumat kesalahan",
		"xx_01": "Mengesan maklumat pemantauan kenderaan",
		"xx_02": "Mengesan maklumat bingkai beku",
		"xx_05": "Mengesan maklumat penderia oksigen",
		"xx_06": "Membaca maklumat hasil pemantauan khusus"
	},

	"ybpgl": {
		"dcdy": "Voltan bateri",
		"xhyb": "Meter Pelayaran",
		"yhyb": "Meter Penggunaan Bahan Api",
		"zdyyb": "Meter Tersuai",
		"xz": "Tambah Papan Pemuka",
		"bj": "Edit Papan Pemuka",
		"sc": "Padam Papan Pemuka",
		"delete_tips": "Adakah anda pasti memadamkan papan pemuka?"
	},


	"status": {
		"1000": "Bluetooth tidak dihidupkan",
		"1001": "Bluetooth dimatikan",
		"1002": "Menunggu penjimatan minyak",
		"1003": "Mencari OBD",
		"1004": "Menyambungkan OBD",
		"1005": "Bluetooth disambungkan",
		"1006": "berjaya menulis data",
		"1007": "Gagal menulis data",
		"1008": "Dayakan pemberitahuan berjaya",
		"1009": "Tiada peranti ditemui"
	},


	"szgl": {
		"bt": "Tetapan",
		"label1": "Bahasa",
		"value1": "Ikuti sistem",
		"label2": "Dasar Privasi",
		"label3": "Bantuan sambungan",
		"label4": "Perihal",
		"label5": "Pusat beli-belah rasmi",
		"value5": "1688 Mall",
		"label6": "Versi",
		"cjwt": "Masalah biasa",
		"unittitle": "Unit",
		"unitvalue1": "Sistem metrik",
		"unitvalue2": "Unit Imperial",
		"unitinfo": "Sahkan sama ada hendak menukar unit?"
	},

	"yygl": {
		"label": "Ikuti sistem",
		"des": "Selepas ia dihidupkan, ia akan ditetapkan secara automatik mengikut bahasa sistem",
		"en": "Bahasa Inggeris",
		"zh": "Cina Ringkas",
		"zwft": "Cina Tradisional",
		"es": "Bahasa Sepanyol",
		"kr": "Bahasa Korea",
		"ru": "Rusia",
		"ja": "Bahasa Jepun",
		"it": "Itali",
		"hi": "Hindi",
		"pt": "Portugis",
		"de": "Jerman",
		"fr": "Bahasa Perancis",
		"nl": "Belanda",
		"fi": "Finland",
		"pl": "Poland",
		"bn": "Bengali",
		"hu": "Hungary",
		"cs": "Czech",
		"th": "Thailand",
		"tr": "Turki",
		"ms": "Melayu",
		"ro": "Romania",
		"sv": "Sweden",
		"da": "Denmark"
	},


	"obdManage": {
		"bt": "Pengurusan OBD",
		"search_tip": "Sila cari semula atau beli produk kami",
		"buy_tip": "Sila pergi ke pusat membeli-belah untuk membeli",
		"searchAgain": "Cari sekali lagi",
		"nearBy": "Peralatan berdekatan",
		"ls": "Peralatan sejarah",
		"bz": "Lihat bantuan",
		"del": "Padam",
		"delConfirm": "Adakah anda pasti akan memadamkan rekod ini?",
		"switched": "Peranti akan ditukar, adakah anda pasti?",
		"qrxx": "Sila sahkan bahawa suis Bluetooth dan maklumat lokasi telefon mudah alih dihidupkan.",
		"searchAgain_message": "Adakah anda pasti akan mencari semula peranti berdekatan?"
	},


	"gzjc": {
		"bt": "Diagnostik",
		"btn": "Mulakan ujian",
		"des": "Mulakan imbasan penuh kenderaan anda",
		"FaultCodeQuery": "Pertanyaan kod kesalahan",
		"zzjc": "Ujian",
		"clearFaultCode": "Kosongkan kod kesalahan",
		"kscz": "cari",
		"fxgz": "Kod kesalahan ditemui",
		"notFound": "tiada masalah ditemui",
		"cxjc": "Semak semula",
		"modalTitle": "Adakah anda pasti mahu mengosongkan kod kesalahan?",
		"modalContent": "Sebelum kerosakan diselesaikan, adalah disyorkan untuk tidak mengosongkan kod kerosakan sesuka hati. Kebanyakan ECU tidak membenarkan untuk memadam kod kerosakan semasa enjin hidup. Sama ada kod kerosakan boleh dibersihkan atau tidak, akhirnya ditentukan oleh ECU. Memadamkan kod masalah sebenarnya bukan penyelesaian kepada masalah itu.",
		"sdjc": "Laporan pemeriksaan mendalam",
		"num": "Bilangan kod kesalahan",
		"gzmxx": "Butiran kod kesalahan",
		"label1": "kategori",
		"label2": "Penjelasan kod kesalahan",
		"definition_03": "Kod masalah diagnostik",
		"definition_07": "Kod masalah diagnostik belum selesai",
		"definition_0A": "Kod masalah diagnostik kekal",
		"03_des": "Apabila keabnormalan dikesan oleh ECU (Unit Kawalan Kenderaan), kod masalah disimpan dalam ingatan. Kod masalah ini merujuk kepada situasi tidak normal yang ditemui semasa proses pemanduan baru-baru ini. Kod masalah ini disimpan dalam ingatan untuk tempoh masa , apabila kod kesalahan ditemui semula, kemas kini tempoh pengekalan.",
		"07_des": "Ini adalah anomali yang tidak diketahui semasa memandu. Jika anomali itu berulang dan dikenal pasti, kod masalah sementara akan diklasifikasikan sebagai kod masalah yang disahkan. Jika tidak disimpan, ia akan dipadamkan apabila enjin dimatikan.",
		"0A_des": "Oleh kerana ia menunjukkan sejarah DTC yang lalu, ia tidak mewakili status kenderaan semasa. Ia mungkin tidak boleh memadamkan DTC yang sepadan secara pemprograman.",
		"sys_P": "Sistem powertrain (pengilang ditakrifkan)",
		"sys_B": "Sistem badan (pengilang ditakrifkan)",
		"sys_C": "Sistem penggantungan casis (ditakrifkan pengilang)",
		"sys_U": "Sistem komunikasi rangkaian (ditakrifkan pengilang)",
		"zzs": "Semua pengeluar kereta"
	},

	"clgl": {
		"bt": "Kereta Saya",
		"info1": "Maklumat Asas Kereta",
		"clpp": "Jenama Kereta",
		"xh": "Model Kereta",
		"nk": "Tahun",
		"rylx": "Jenis Bahan Api",
		"info2": "Maklumat Kenderaan Lain",
		"atdp": "Protokol Komunikasi",
		"ati": "Versi Penyesuai",
		"vin": "Nombor Pengenalan Kenderaan",
		"cid": "Pengenalan Kalibrasi",
		"cvn": "Nombor Pengesahan Penentukuran",
		"ecu": "Unit Kawalan Elektronik",
		"ESN": "Nombor Siri Enjin",
		"EROTAN": "Peraturan Ekzos Atau Nombor Kelulusan Jenis",
		"FEOCNTR": "Kaunter Kitaran Pencucuhan Operasi Enjin Berbahan Api",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Sila isikan jenama kenderaan",
		"warn2": "model kereta diperlukan",
		"warn3": "tahun kereta diperlukan",
		"warn4": "vin diperlukan",
		"warn5": "Sila isikan nombor pengenalan kenderaan yang betul",
		"warn6": "nama pemilik kereta diperlukan",
		"warn7": "telefon diperlukan",
		"warn8": "Sila masukkan telefon yang betul",
		"warn9": "Sila masukkan e-mel yang betul",
		"bt": "Sambungan OBD berjaya",
		"title_sub": "Maklumat berikut adalah sangat penting untuk diagnosis yang tepat, untuk meningkatkan pengalaman anda. Pastikan anda mengisi dengan teliti.",
		"ts_vin": "Lokasi kod VIN: biasanya terletak di sebelah kiri panel instrumen, kiri bawah cermin depan; terdapat juga lajur engsel pintu, lajur kunci pintu atau salah satu lajur yang disambungkan ke lajur kunci pintu; atau pintu berhampiran tempat duduk pemandu di dalam.",
		"vin": "Vin",
		"czxm": "Nama",
		"lxdh": "Telefon",
		"lxyx": "E-mel"
	},
	"ota": {
		"bt": "Naik taraf OTA",
		"jcdxbb": "Versi perisian tegar baharu dikesan",
		"gxnr": "Kemas kini kandungan",
		"fxsm": "Arahan Naik Taraf",
		"fxsm_des": "Naik taraf OTA (teknologi over-the-air) bermaksud terminal mudah alih memuat turun pakej naik taraf pada pelayan dari jauh untuk menaik taraf perisian tegar OBD. Naik taraf tidak akan menjejaskan keselamatan kenderaan dan pemanduan anda, sila gunakan itu. Jika Ia menggesa bahawa peningkatan telah gagal, sila jangan keluar dari antara muka, masukkan semula OBD dan teruskan naik taraf.",
		"zysx": "Amaran",
		"zysx_des": "Jangan naik taraf semasa memandu, dan jangan keluarkan atau matikan OBD semasa naik taraf.",
		"mssj": "Tingkatkan sekarang",
		"kssj": "Mulakan naik taraf",
		"sjcg": "Naik taraf OTA berjaya",
		"kqqxty": "Buka pengalaman baharu",
		"xzgj": "Muat turun perisian tegar",
		"zzxr": "Menulis",
		"zzsj": "Menaik taraf",
		"zzjy": "Mengesahkan integriti",
		"sjsb": "Naik taraf gagal, cuba lagi"
	},

	"xcfx": {
		"ksxc": "Mulakan perjalanan",
		"jsxc": "Tamatkan perjalanan",
		"lsjl": "Rekod sejarah",
		"zlc": "Jumlah perbatuan",
		"hs": "Memakan masa",
		"kssj": "Masa mula",
		"zyh": "Jumlah liter"
	},

	"xncs": {
		"jsxn": "Dipercepatkan",
		"scxn": "Membrek",
		"jlxn": "Jarak",
		"des1": "Julat ujian kelajuan",
		"des2": "kelajuan semasa membrek",
		"des3": "jarak ujian",
		"aqtx": "sila beri perhatian kepada keselamatan memandu!",
		"kscs": "Mulakan ujian",
		"cxcs": "Ujian semula",
		"tz": "Berhenti",
		"tip1": "Sila laraskan kelajuan kenderaan kepada",
		"tip2": "Sila pijak pemecut untuk memecut ke",
		"tip2_end": "Di atas",
		"tip3": "Sila injak brek untuk mengurangkan kelajuan ke",
		"tip4": "Sila memandu",
		"tip5": "Mengembara",
		"max_sd": "Kelajuan tertinggi",
		"max_jsd": "Pecutan maksimum",
		"max_zs": "Kelajuan maksimum",
		"tx1": "Kelajuan mula tidak boleh lebih besar daripada kelajuan tamat",
		"tx2": "Sila isikan kelajuan brek lebih besar daripada 0",
		"tx3": "Sila isikan jarak ujian yang lebih besar daripada 0"
	},

	"bzxx": {
		"title1": "Langkah 1: Mulakan kenderaan",
		"title2": "Langkah 2: Palamkan peranti",
		"title3": "Langkah 3: Hidupkan Bluetooth dan Lokasi",
		"title4": "Langkah 4: Buka APP",
		"title5": "Langkah 5: Sambungkan Peranti",
		"text1": "Cari lokasi antara muka OBD kenderaan. Antara muka OBD ialah antara muka wanita 16-pin. Antara muka adalah trapezoid. Sesetengah model mempunyai penutup pada antara muka OBD. Port OBD biasa adalah hitam, putih atau biru. Lokasi secara amnya adalah dalam panel trim dalaman di bawah stereng, berhampiran lutut pemandu. Lokasi antara muka OBD mungkin berbeza untuk model dan model yang berbeza. Rajah berikut menunjukkan kemungkinan lokasi antara muka OBD:",
		"text2": "Selepas mencari antara muka OBD, palamkan peranti ke antara muka OBD. Pastikan ia dipalamkan sepenuhnya (banyak kereta dipasang kira-kira separuh jalan dan kuasa dihidupkan, tetapi pin isyarat mungkin tidak disambungkan), dan penunjuk kuasa merah atau skrin dihidupkan.",
		"text3": "Hidupkan Bluetooth dan suis lokasi pada telefon anda. Kaedah: Leret ke bawah pada bahagian atas skrin telefon, buka menu pintasan dan klik Bluetooth dan maklumat lokasi. Hidupkan Bluetooth pada peranti iOS anda.",
		"text4": "Buka apl dan benarkan apl menggunakan maklumat lokasi.",
		"text5": "Selepas melengkapkan langkah di atas, masukkan APP, APP akan mengimbas peranti OBD secara automatik dan bertanya kepada anda sama ada hendak menyambungkan peranti itu. Peranti iOS bertanya sama ada untuk membenarkan akses kepada alamat, klik Benarkan.",
		"text6": "Pilih peranti untuk disambungkan dan klik untuk menyambung. Selepas sambungan berjaya, halaman utama APP akan memaparkan nama peranti OBD, alamat Bluetooth dan bacaan akan muncul pada papan pemuka."
	},

	"06fw": {
		"MID": "Nama Pantau",
		"TID": "Nama Ujian",
		"CID": "Nombor Komponen",
		"O2Sensor": "Nama Penderia O2",
		"MIN": "Had Minimum",
		"MAX": "Had Maksimum",
		"CURRENT": "Nilai Ujian"
	},

	"09fw": {
		"ipt": "Penjejakan Prestasi Dalam Penggunaan",
		"IPT_08_1": "Pengiraan Keadaan Pemantauan OBD Dihadapi",
		"IPT_08_2": "Pembilang Kitaran Pencucuhan",
		"IPT_08_3": "Catalyst Monitor Completion Counts Bank 1",
		"IPT_08_4": "Keadaan Pemantau Pemangkin Mengira Bank 1",
		"IPT_08_5": "Catalyst Monitor Completion Counts Bank 2",
		"IPT_08_6": "Keadaan Pemantau Pemangkin Mengira Bank 2",
		"IPT_08_7": "O2 Sensor Monitor Siap Mengira Bank 1",
		"IPT_08_8": "Keadaan Monitor Penderia O2 Dihadapi Mengira Bank 1",
		"IPT_08_9": "O2 Sensor Monitor Siap Mengira Bank 2",
		"IPT_08_10": "Keadaan Monitor Penderia O2 Mengira Bank 2",
		"IPT_08_11": "Kiraan Keadaan Penyiapan Monitor EGR dan/atau VVT",
		"IPT_08_12": "Pengiraan Keadaan Monitor EGR dan/atau VVT",
		"IPT_08_13": "Kiraan Keadaan Siap Monitor AIR (Udara Kedua)",
		"IPT_08_14": "Pengiraan Keadaan Monitor AIR (Udara Kedua)",
		"IPT_08_15": "Kiraan Keadaan Penyiapan Monitor EVAP",
		"IPT_08_16": "Pengiraan Keadaan Monitor EVAP yang Dihadapi",
		"IPT_08_17": "Pengiraan Penyiapan Monitor Penderia O2 Menengah Bank 1",
		"IPT_08_18": "Keadaan Monitor Penderia O2 Sekunder Dihadapi Mengira Bank 1",
		"IPT_08_19": "Pengiraan Penyiapan Monitor Penderia O2 Menengah Bank 2",
		"IPT_08_20": "Keadaan Monitor Penderia O2 Sekunder Dihadapi Mengira Bank 2",

		"IPT_08_des_1": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan OBD yang ditentukan (penyebut am)",
		"IPT_08_des_2": "memaparkan kiraan bilangan kali enjin telah dihidupkan.",
		"IPT_08_des_3": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem pemangkin bank 1 telah dihadapi (pembilang)",
		"IPT_08_des_4": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan pemangkin yang ditentukan (penyebut)",
		"IPT_08_des_5": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem pemangkin bank 2 telah dihadapi (pembilang)",
		"IPT_08_des_6": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan pemangkin yang ditentukan (penyebut)",
		"IPT_08_des_7": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan bank sensor oksigen 1 telah dihadapi (pembilang)",
		"IPT_08_des_8": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sensor oksigen yang ditentukan (penyebut)",
		"IPT_08_des_9": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan bank sensor oksigen 2 telah dihadapi (pembilang)",
		"IPT_08_des_10": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sensor oksigen yang ditentukan (penyebut)",
		"IPT_08_des_11": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem EGR/VVT telah ditemui (pembilang)",
		"IPT_08_des_12": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sistem EGR/VVT yang ditentukan (penyebut)",
		"IPT_08_des_13": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem AIR telah dihadapi (pembilang)",
		"IPT_08_des_14": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sistem AIR yang ditentukan (penyebut)",
		"IPT_08_des_15": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan kebocoran sistem EVAP 0.020” (atau 0.040”) telah ditemui (penghitung)",
		"IPT_08_des_16": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan kerosakan kebocoran sistem EVAP yang ditentukan (penyebut)",
		"IPT_08_des_17": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan bank sensor oksigen sekunder 1 telah dihadapi (pembilang)",
		"IPT_08_des_18": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sensor oksigen sekunder yang ditentukan (penyebut)",
		"IPT_08_des_19": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan bank sensor oksigen sekunder 2 kerosakan telah dihadapi (pembilang)",
		"IPT_08_des_20": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sensor oksigen sekunder yang ditentukan (penyebut)",

		"IPT_0B_1": "Pengiraan Keadaan Pemantauan OBD Dihadapi",
		"IPT_0B_2": "Pembilang Kitaran Pencucuhan",
		"IPT_0B_3": "Pengiraan Keadaan Penyiapan Monitor Pemangkin NMHC",
		"IPT_0B_4": "Pengiraan Pemantauan Pemangkin NMHC Keadaan yang Dihadapi",
		"IPT_0B_5": "Pengiraan Keadaan Penyiapan Monitor Pemangkin NOx/SCR",
		"IPT_0B_6": "Pengiraan Pemantau Pemangkin NOx/SCR",
		"IPT_0B_7": "Pengiraan Keadaan Penyiapan Monitor Penyerap NOx",
		"IPT_0B_8": "Keadaan Pemantau NOx Adsorber Dihadapi Kiraan",
		"IPT_0B_9": "Kiraan Keadaan Penyiapan Monitor Penapis PM",
		"IPT_0B_10": "Perkiraan Keadaan Monitor Penapis PM",
		"IPT_0B_11": "Pengiraan Keadaan Lengkap Monitor Penderia Gas Ekzos",
		"IPT_0B_12": "Keadaan Pemantau Gas Ekzos Dihadapi Kiraan",
		"IPT_0B_13": "Kiraan Keadaan Penyiapan Monitor EGR dan/atau VVT",
		"IPT_0B_14": "Pengiraan Keadaan Monitor EGR dan/atau VVT",
		"IPT_0B_15": "Pengiraan Keadaan Penyiapan Monitor Tekanan Naik",
		"IPT_0B_16": "Peningkatan Tekanan Monitor Keadaan Dihadapi Kiraan",
		"IPT_0B_17": "Kiraan Keadaan Penyiapan Monitor Bahan Api",
		"IPT_0B_18": "Pengiraan Keadaan Monitor Bahan Api",

		"IPT_0B_des_1": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan OBD yang ditentukan (penyebut am)",
		"IPT_0B_des_2": "memaparkan kiraan bilangan kali enjin telah dihidupkan.",
		"IPT_0B_des_3": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan sistem pemangkin NMHC telah dihadapi (pembilang)",
		"IPT_0B_des_4": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan pemangkin NMHC yang ditentukan (penyebut)",
		"IPT_0B_des_5": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan sistem mangkin NOx telah dihadapi (pembilang)",
		"IPT_0B_des_6": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan pemangkin NOx (penyebut) yang ditentukan",
		"IPT_0B_des_7": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem penjerap NOx telah dihadapi (pembilang)",
		"IPT_0B_des_8": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam penyebut keadaan pemantauan penyerap NOx yang ditentukan)",
		"IPT_0B_des_9": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem penapis PM telah dihadapi (pembilang)",
		"IPT_0B_des_10": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam penyebut keadaan pemantauan penapis PM yang ditentukan)",
		"IPT_0B_des_11": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan penderia gas ekzos telah dihadapi (pembilang)",
		"IPT_0B_des_12": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sensor gas ekzos (penyebut) yang ditentukan",
		"IPT_0B_des_13": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem EGR/VVT telah dihadapi (pembilang)",
		"IPT_0B_des_14": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sistem EGR/VVT yang ditentukan (penyebut)",
		"IPT_0B_des_15": "memaparkan bilangan kali semua keadaan yang diperlukan untuk mengesan kerosakan sistem tekanan rangsangan telah dihadapi (penumerator)",
		"IPT_0B_des_16": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sistem tekanan rangsangan yang ditentukan (penyebut)",
		"IPT_0B_des_17": "memaparkan bilangan kali semua syarat yang diperlukan untuk mengesan kerosakan sistem bahan api telah dihadapi (pembilang)",
		"IPT_0B_des_18": "memaparkan bilangan kali kenderaan itu telah dikendalikan dalam keadaan pemantauan sistem bahan api (penyebut) yang ditentukan."
	}
}
