// 荷兰语
var i18n = {
  "mt": "Dag",
  "xs": "Uren",
  "fz": "Minuten",
  "wxts": "Tips",
  "zzjz": "bezig met laden...",
  "noData": "GEEN GEGEVENS",
  "jchj": "Inlogomgeving controleren",
  "ckfw": "Referentiebereik",
  "bbgl": {
    "bbts": "Herinnering versie-update",
    "official": "Er zijn nieuwe functies uitgebracht. Ga naar de officiële website om de nieuwste versie te downloaden en te upgraden.",
    "apple": "Er zijn nieuwe functies uitgebracht, ga naar de App Store om de bijgewerkte versie te downloaden.",
    "google": "Er zijn nieuwe functies uitgebracht. Ga naar Google Play om de bijgewerkte versie te downloaden."
  },
  "uds": {
    "uds0001": "Module selecteren",
    "uds0002": "Selecteer module om te lezen",
    "uds0003": "De lijst bevat alle ondersteunde modules van het geselecteerde merk, het wordt aanbevolen om alleen de modules te selecteren die al in de auto aanwezig zijn. Alle modules kunnen echter worden geselecteerd. Het systeem detecteert automatisch de eenheden die daadwerkelijk in de auto aanwezig zijn .",
    "uds0004": "Alles selecteren",
    "uds0005": "Annuleren Alles selecteren",
    "uds0006": "Diagnose starten",
    "uds0007": "Aangepaste leverancier"
  },
  "yjdl": {
    "yxdl": "E-mail login",
    "dlts": "Voer eerst de grafische Captcha in en ontvang dan de e-mail Captcha",
    "sryx": "Voer uw e-mailadres in",
    "sryzm": "Voer captcha in",
    "xyb": "Volgende",
    "xgyx": "Postvak wijzigen",
    "yxdz": "E-mailadres",
    "fsyzm": "toegangscode naar e-mail sturen",
    "yzm": "Toegangscode",
    "cxfs": "seconden om opnieuw te verzenden",
    "dl": "Inloggen",
    "srtxyzm": "Voer linker grafische Captcha in",
    "yxbzq": "E-mail is onjuist",
    "txyzmbzq": "De grafische Captcha is onjuist",
    "fsdx": "Captcha verzenden",
    "yxyzmfscg": "E-mail Captcha succesvol verzonden",
    "yxbky": "Het verzenden van e-mail is abnormaal! Controleer of het e-mailadres correct is ingevoerd en of de e-mail normaal kan worden ontvangen.",
    "zzyz": "Verifiëren",
    "yzmcw": "De e-mail Captcha is onjuist",
    "clxxgl": "Voertuiginformatiebeheer",
    "gxxx": "Informatie bijwerken",
    "dlcg": "Inloggen gelukt",
    "dlsb": "Inloggen mislukt",
    "clxx": "Voertuiginformatie",
    "czxx": "Informatie auto-eigenaar",
    "wdl": "Niet ingelogd",
    "cl": "Voertuig"
  },

  "OBDxncs": {
    "bt": "Vergelijking van adapters",
    "fbt": "groter betekent sneller",
    "zjsd": "Optimale snelheid",
    "dqsd": "Huidige snelheid",
    "xzmc": "De snelheid waarmee parameters per seconde uit de ECU worden gelezen (eenheid: parameters/seconde)",
    "sec_dt": "Getest met Galaxy Note 8 en Pixel 2",
    "sec_dd1": "(1) Wi-Fi-adapters worden over het algemeen niet aanbevolen voor Android, aangezien de meeste telefoons hun dataverbinding met internet verliezen tijdens het gebruik.",
    "sec_dd2": "(2) Alle geteste adapters zijn standaard Bluetooth tenzij 'WiFi', 'USB' of 'BLE' deel uitmaakt van hun naam",
    "text2": "Vergelijking van OBD"
  },

  "tsxx": {
    "qxz": "kiezen",
    "qsr": "Voer alstublieft in",
    "qqr": "Bevestigen",
    "qqx": "Annuleren",
    "notConnected": "Sluit eerst uw apparaat aan",
    "save": "Sla het formulier succesvol op.",
    "dsyh": "Inactief brandstofverbruik verwijst naar het brandstofverbruik op het moment dat het voertuig stilstaat, met tijd als statistische eenheid.",
    "xsyh": "Brandstofverbruik tijdens het rijden verwijst naar het brandstofverbruik op het moment dat het voertuig rijdt, en neemt de afstand als statistische eenheid.",
    "pjyh": "Het gemiddelde brandstofverbruik verwijst naar het brandstofverbruik per 100 kilometer van het voertuig tijdens dit rijproces en wordt pas weergegeven na meer dan 1 km te hebben gereden.",
    "cqyh": "Langdurig brandstofverbruik verwijst naar het brandstofverbruik van het voertuig gedurende 100 kilometer tijdens de werking van de APP.",
    "yhsupport": "Deze auto ondersteunt geen weergave van het brandstofverbruik",
    "cg": "succes",
    "noTrouble": "Gefeliciteerd, uw auto is storingsvrij, ga zo door.",
    "noVin": "Voer het 17-cijferige framenummer in zodat we u beter van dienst kunnen zijn.",
    "gzzsd": "De MIL is de afkorting van Malfunction Indicator Lamp. Als het MIL-lampje brandt, betekent dit dat het motorsysteem mogelijk defect is. De reden voor het branden van het MIL-lampje kan zijn dat er te veel koolstofafzetting in de gasklep of de motor, of de mengverhouding is uit balans nadat de zuurstofsensor uitvalt, of het motorlampje brandt vanwege de slechte brandstofkwaliteit van de benzine en de onvoldoende verbranding van het voertuig.",
    "noDevelopment": "In ontwikkeling, blijf op de hoogte. ",
    "zc": "Momenteel beschikbaar om te testen",
    "noSupport": "Momenteel niet beschikbaar voor testen",
    "noNetwork": "Uw netwerk is momenteel niet beschikbaar. Geen enkel netwerk heeft invloed op uw ervaring.",
    "jy": "Uitgeschakeld",
    "ywc": "Statustest voltooid",
    "noCompelte": "Statustest niet voltooid",
    "noSupportPid": "Uw voertuig heeft deze test niet!",
    "useReminders": "Herinnering: na het pauzeren kunt u zoomen of rondlopen door met uw vinger over de schuifregelaar of over het aanraakscherm te vegen.",
    "noCompelteDes": "Als de status Ready kan worden getest maar niet wordt voltooid, kunnen de volgende maatregelen worden genomen: volledig rijden, het voertuig onderhouden, de montage reinigen, de ECU upgraden, enz. Het is te hopen dat het rijproces zal in de toekomst volgens de specificaties worden bediend en er zal regelmatig onderhoud worden gepleegd.",
    "fgf": "Deze functie is exclusief voor officiële producten, gebruik deze na aankoop!",
    "b25": "Deze functie is exclusief voor B25, gebruik deze na aankoop!"
  },

  "pid": {
    "dsyh": "Inactief brandstofverbruik",
    "xsyh": "brandstofverbruik",
    "ssyh": "Gemiddeld verbruik",
    "pjyh": "Intant verbruik",
    "cqyh": "Brandstofverbruik op lange termijn",
    "pjsd": "Gemiddelde snelheid",
    "xslc": "Gereden afstand",
    "DTC_legnth": "# DTC's opgeslagen in deze ECU",
    "MIL": "Status indicatielampje storing",
    "mil_0": "licht uit",
    "mil_1": "licht aan",
    "shxt": "Misfire-bewaking",
    "ryxt": "Bewaking brandstofsysteem",
    "zhzj": "Uitgebreide componentbewaking",

    "fdjlx": "Motortype",
    "ysfdj": "compressie-ontsteking",
    "dhfdj": "vonkontsteking",
    "chj": "Katalysator bewaken",
    "jrchj": "Bewaking van verwarmde katalysator",
    "zfxt": "Bewaking van het verdampingssysteem",
    "eckqxt": "Bewaking secundaire luchtsysteem",
    "ktxtzlj": "Koelmiddelbewaking airconditioningsysteem",
    "ycgqjrq": "Zuurstofsensor verwarming bewaken",
    "ycgqjk": "Zuurstofsensorbewaking",
    "erg": "EGR/VVT-systeembewaking",
    "NMHC": "NMHC-katalysatorbewaking ",
    "NOx": "NOx/SCR-bewaking",
    "yl": "Gereserveerd",
    "zyyl": "Boostdrukbewaking",
    "fqcgq": "Bewaking uitlaatgassensor",
    "pmglq": "PM-filter monitorbewaking"
  },

  "sygl": {
    "xieyi": "Protocol",
    "tips1": "Sluit het apparaat aan",
    "tips2": "Schakel Bluetooth in! Bekijk hulp",
    "tips3": "Kunt u het apparaat niet vinden? Bekijk hulp",
    "tips4": "Schakel locatieservices in",
    "tips5": " Universeel",
    "tips6": " Voordelige versie",
    "sdlj": "Selecteer handmatig een verbinding"
  },

  "djz": {
    "noData": "Er zijn momenteel geen stilstaand beeldgegevens",
    "previousFrame": "Vorige Frame",
    "nextFrame": "Volgend frame"
  },

  "fwgl": {
    "ybp": "Dashboard",
    "UDS": "Geünificeerde diagnostische service (test)",
    "UDS_des": "Bied uniforme voertuigdiagnoseservice, meer ECU's en meer functies",
    "DTC": "DTC-bewaking",
    "DTC_des": "Professionele oplossingen bieden voor voertuigfoutcodes",
    "xcfx": "Reisanalyse",
    "xcfx_des": "Analyseer al uw reisgegevens",
    "xncs": "Voertuigprestatietesten",
    "xncs_des": "Professioneel analyserapport van voertuigprestaties leveren",
    "sssjl": "realtime gegevensstroom",
    "sssjl_des": "Huidige aandrijflijn diagnostische gegevens opvragen",
    "gzzsd": "Detectie foutindicator",
    "gzzsd_des": "Geeft informatie over de werking van het voertuig nadat het storingslampje aan of uit is",

    "pid0141": "Status Diagnostische gereedheid",
    "pid0141_des": "Geeft de voertuigbewakingsstatus sinds de storingscode is gewist en de huidige werkingsstatus van de rijcyclusbewaking",
    "$05": "Resultaten monitoring zuurstofsensor",
    "$05_des": "Lees de testresultaten van de bewaking van de zuurstofsensor in voertuigen",
    "$06": "Specifieke monitoringresultaten",
    "$06_des": "toegang geven tot de resultaten van On-Board Diagnostic bewakingstests voor specifieke componenten/systemen.",
    "$09": "Voertuiginformatie",
    "$09_des": "Lees voertuigspecifieke voertuiginformatie en info",

    "clnj": "",
    "clnj_des": "",

    "obdTest": "OBD prestatietest",
    "obdTest_des": "Test verschillende prestatie-indicatoren van OBD via geautomatiseerde testtools.",
    "djz": "Frame stilzetten",
    "djz_des": "Als er een storingscode in het uitlaatsysteem verschijnt, slaat de ECU de gegevens op als de storingscode verschijnt",
    "yjjc": "Volledige voertuigdetectie met één klik",
    "yjjc_des": "Uitgebreide detectie van alle voertuigsensorgegevens, voertuiginformatie, foutcodes, stilstaande beelden en voertuigbewakingsinformatie."
  },

  "yjjc": {
    "cljkxx": "informatie over voertuigbewaking",
    "xx_09": "Voertuiginformatie detecteren",
    "xx_03": "Foutinformatie detecteren",
    "xx_01": "Informatie over voertuigbewaking detecteren",
    "xx_02": "Bevroren frame-informatie detecteren",
    "xx_05": "Zuurstofsensor informatie detecteren",
    "xx_06": "Specifieke monitoring resultaat informatie lezen"
  },

  "ybpgl": {
    "dcdy": "Accuspanning",
    "xhyb": "Cruisemeter",
    "yhyb": "Brandstofverbruiksmeter",
    "zdyyb": "Aangepaste meter",
    "xz": "Dashboard toevoegen",
    "bj": "Dashboard bewerken",
    "sc": "Dashboard verwijderen",
    "delete_tips": "Weet u zeker dat u het dashboard wilt verwijderen?"
  },


  "status": {
    "1000": "Bluetooth is niet ingeschakeld",
    "1001": "Bluetooth staat uit",
    "1002": "Wachten op brandstofbesparing",
    "1003": "Zoeken naar OBD",
    "1004": "OBD verbinden",
    "1005": "Bluetooth is verbonden",
    "1006": "met succes gegevens schrijven",
    "1007": "Kon geen gegevens schrijven",
    "1008": "Melding succesvol inschakelen",
    "1009": "Geen apparaat gevonden"
  },


  "szgl": {
    "bt": "Instelling",
    "label1": "Taal",
    "value1": "Volg systeem",
    "label2": "Privacybeleid",
    "label3": "Hulp bij verbinding",
    "label4": "Over",
    "label5": "Officieel winkelcentrum",
    "value5": "1688 Winkelcentrum",
    "label6": "Versie",
    "cjwt": "Veelvoorkomend probleem",
    "unittitle": "Eenheid",
    "unitvalue1": "Metrisch systeem",
    "unitvalue2": "Keizerlijke eenheden",
    "unitinfo": "Bevestigen of eenheden moeten worden gewisseld?"
  },

  "yygl": {
    "label": "Volg systeem",
    "des": "Nadat het is ingeschakeld, wordt het automatisch ingesteld volgens de systeemtaal",
    "en": "Engels",
    "zh": "Vereenvoudigd Chinees",
    "zwft": "Traditioneel Chinees",
    "es": "Spaans",
    "kr": "Koreaans",
    "ru": "Russisch",
    "ja": "Japans",
    "it": "Italiaans",
    "hi": "Hindi",
    "pt": "Portugees",
    "de": "Duits",
    "fr": "Frans",
    "nl": "Nederlands",
    "fi": "Fins",
    "pl": "Pools",
    "bn": "Bengaals",
		"hu": "Hongaars",
		"cs": "Tsjechisch",
		"th": "Thais",
		"tr": "Turks",
		"ms": "Maleis",
		"ro": "Roemeens",
		"sv": "Zweeds",
		"da": "Deens"
  },


  "obdManage": {
    "bt": "OBD-beheer",
    "search_tip": "Zoek opnieuw of koop onze producten",
    "buy_tip": "Ga alsjeblieft naar het winkelcentrum om te kopen",
    "searchAgain": "Opnieuw zoeken",
    "nearBy": "Apparatuur in de buurt",
    "ls": "Historische uitrusting",
    "bz": "Bekijk hulp",
    "del": "Verwijderen",
    "delConfirm": "Weet u zeker dat u dit record wilt verwijderen?",
    "switched": "Het apparaat staat op het punt om te worden geschakeld, weet u het zeker?",
    "qrxx": "Bevestig dat de Bluetooth- en locatie-informatieschakelaar van de mobiele telefoon is ingeschakeld.",
    "searchAgain_message": "Weet u zeker dat u opnieuw wilt zoeken naar apparaten in de buurt?"
  },


  "gzjc": {
    "bt": "Diagnostiek",
    "btn": "Begin met testen",
    "des": "Start een volledige scan van uw voertuig",
    "FaultCodeQuery": "Foutcode opvragen",
    "zzjc": "Testen",
    "clearFaultCode": "Foutcode wissen",
    "kscz": "zoeken",
    "fxgz": "Foutcode gevonden",
    "notFound": "geen problemen gevonden",
    "cxjc": "Opnieuw controleren",
    "modalTitle": "Weet u zeker dat u de foutcode wilt wissen?",
    "modalContent": "Voordat de fout is opgelost, wordt aanbevolen om de foutcode niet naar believen te wissen. De meeste ECU's staan niet toe om de foutcode te wissen wanneer de motor draait. Of de foutcode kan worden gewist of niet, is uiteindelijk bepaald door de ECU. Foutcodes verwijderen is niet echt de oplossing voor het probleem.",
    "sdjc": "Diepte-inspectierapport",
    "num": "Aantal foutcodes",
    "gzmxx": "Details foutcode",
    "label1": "categorie",
    "label2": "Foutcode uitleg",
    "definition_03": "Diagnostische foutcodes",
    "definition_07": "Diagnostische foutcodes in behandeling",
    "definition_0A": "Permanente diagnostische foutcodes",
    "03_des": "Wanneer een afwijking wordt gedetecteerd door de ECU (Vehicle Control Unit), wordt een foutcode in het geheugen opgeslagen. Deze foutcode verwijst naar een abnormale situatie die is gevonden tijdens het recente rijproces. Deze foutcodes worden in het geheugen bewaard gedurende een bepaalde periode, wanneer de foutcode opnieuw wordt gevonden, de bewaarperiode updaten.",
    "07_des": "Dit is een niet-bevestigde storing tijdens het rijden. Als de storing wordt herhaald en geïdentificeerd, wordt de tijdelijke storingscode geclassificeerd als een bevestigde storingscode. Als deze niet wordt opgeslagen, wordt deze verwijderd wanneer de motor wordt uitgeschakeld.",
    "0A_des": "Omdat het een geschiedenis van eerdere DTC's toont, vertegenwoordigt het niet de huidige voertuigstatus. Het is misschien niet mogelijk om de overeenkomstige DTC's programmatisch te verwijderen.",
    "sys_P": "Aandrijflijnsysteem (gedefinieerd door de fabrikant)",
    "sys_B": "Lichaamssysteem (door fabrikant gedefinieerd)",
    "sys_C": "Chassisophangingssysteem (door fabrikant gedefinieerd)",
    "sys_U": "Netwerkcommunicatiesysteem (door fabrikant gedefinieerd)",
    "zzs": "Alle autofabrikanten"
  },

  "clgl": {
    "bt": "Mijn auto",
    "info1": "Basisinformatie over auto's",
    "clpp": "Automerken",
    "xh": "Automodel",
    "nk": "Jaar",
    "rylx": "Brandstoftype",
    "info2": "Overige voertuiginformatie",
    "atdp": "Communicatieprotocol",
    "ati": "Adapterversie",
    "vin": "Voertuigidentificatienummer",
    "cid": "Kalibratie-identificaties",
    "cvn": "Kalibratieverificatienummers",
    "ecu": "Elektronische regeleenheid",
    "ESN": "Serienummer van de motor",
    "EROTAN": "Uitlaatregeling of typegoedkeuringsnummer",
    "FEOCNTR": "Gevoede motorwerking Ontstekingscyclusteller",
    "obd": "OBDSUP"
  },

  "clbj": {
    "warn1": "Vul het merk van het voertuig in",
    "warn2": "automodel vereist",
    "warn3": "autojaar is vereist",
    "warn4": "vin is vereist",
    "warn5": "Vul het juiste voertuigidentificatienummer in",
    "warn6": "naam auto-eigenaar is verplicht",
    "warn7": "telefoon is vereist",
    "warn8": "Voer de juiste telefoon in",
    "warn9": "Voer het juiste e-mailadres in",
    "bt": "OBD-verbinding is gelukt",
    "title_sub": "De volgende informatie is erg belangrijk voor een nauwkeurige diagnose, om uw ervaring te verbeteren. Zorg ervoor dat u deze zorgvuldig invult.",
    "ts_vin": "De locatie van de VIN-code: meestal aan de linkerkant van het instrumentenpaneel, linksonder op de voorruit; er is ook een deurscharnierkolom, een deurslotkolom of een van de kolommen die is aangesloten op de deurslotkolom; of de deur bij de bestuurdersstoel binnenin.",
    "vin": "Vin",
    "czxm": "Naam",
    "lxdh": "Telefoon",
    "lxyx": "E-mail"
  },
  "ota": {
    "bt": "OTA-upgrade",
    "jcdxbb": "Nieuwe firmwareversie gedetecteerd",
    "gxnr": "Inhoud bijwerken",
    "fxsm": "Upgrade-instructies",
    "fxsm_des": "OTA-upgrade (over-the-air-technologie) betekent dat de mobiele terminal het upgradepakket op afstand downloadt op de server om de OBD-firmware te upgraden. De upgrade heeft geen invloed op uw voertuig- en rijveiligheid. Voel u vrij om deze te gebruiken Als het aangeeft dat de upgrade is mislukt, verlaat u de interface niet, plaatst u de OBD opnieuw en gaat u verder met de upgrade.",
    "zysx": "Waarschuwing",
    "zysx_des": "Upgrade niet tijdens het rijden en verwijder of schakel de OBD niet uit tijdens de upgrade.",
    "mssj": "Nu upgraden",
    "kssj": "Start de upgrade",
    "sjcg": "OTA-upgrade succesvol",
    "kqqxty": "Open een nieuwe ervaring",
    "xzgj": "Firmware downloaden",
    "zzxr": "Schrijven",
    "zzsj": "Upgraden",
    "zzjy": "Integriteit verifiëren",
    "sjsb": "Upgrade mislukt, probeer het opnieuw"
  },

  "xcfx": {
    "ksxc": "Start de reis",
    "jsxc": "Beëindig de reis",
    "lsjl": "Geschiedenisrecord",
    "zlc": "Totale kilometerstand",
    "hs": "Tijdrovend",
    "kssj": "Starttijd",
    "zyh": "Totaal liters"
  },

  "xncs": {
    "jsxn": "Versneld",
    "scxn": "Remmen",
    "jlxn": "Afstand",
    "des1": "Snelheidstestbereik",
    "des2": "snelheid bij remmen",
    "des3": "testafstand",
    "aqtx": "let op de rijveiligheid!",
    "kscs": "Begin met testen",
    "cxcs": "Opnieuw testen",
    "tz": "Stoppen",
    "tip1": "Pas de snelheid van het voertuig aan naar",
    "tip2": "Gelieve het gaspedaal in te trappen om naar toe te accelereren",
    "tip2_end": "Boven",
    "tip3": "Gelieve op de rem te trappen om de snelheid te verminderen tot",
    "tip4": "Gelieve te rijden",
    "tip5": "Reist",
    "max_sd": "Topsnelheid",
    "max_jsd": "Maximale versnelling",
    "max_zs": "Maximale snelheid",
    "tx1": "Startsnelheid kan niet hoger zijn dan eindsnelheid",
    "tx2": "Gelieve de remsnelheid groter dan 0 in te vullen",
    "tx3": "Vul de testafstand groter dan 0 in"
  },

  "bzxx": {
    "title1": "Stap 1: Start het voertuig",
    "title2": "Stap 2: sluit het apparaat aan",
    "title3": "Stap 3: Schakel Bluetooth en locatie in",
    "title4": "Stap 4: Open de APP",
    "title5": "Stap 5: Sluit het apparaat aan",
    "text1": "Zoek de locatie van de OBD-interface van het voertuig. De OBD-interface is een 16-pins vrouwelijke interface. De interface is trapeziumvormig. Sommige modellen hebben een deksel op de OBD-interface. Algemene OBD-poorten zijn zwart, wit of blauw. De locatie bevindt zich over het algemeen in het interieurbekledingspaneel onder het stuur, in de buurt van de knieën van de bestuurder. De locatie van de OBD-interface kan verschillen voor verschillende modellen en modellen. De volgende afbeelding toont de mogelijke locatie van de OBD-interface:",
    "text2": "Nadat u de OBD-interface hebt gevonden, sluit u het apparaat aan op de OBD-interface. Zorg ervoor dat het volledig is aangesloten (veel auto's zijn ongeveer halverwege aangesloten en de stroom is ingeschakeld, maar de signaalpennen zijn mogelijk niet aangesloten) en de rode voedingsindicator of het scherm brandt.",
    "text3": "Schakel de Bluetooth- en locatieschakelaars op je telefoon in. Methode: Veeg naar beneden aan de bovenkant van het telefoonscherm, open het snelmenu en klik op Bluetooth en locatie-informatie. Schakel Bluetooth in op je iOS-apparaat.",
    "text4": "Open de app en sta de app toe locatie-informatie te gebruiken.",
    "text5": "Ga na het voltooien van de bovenstaande stappen naar de APP, de APP zal automatisch het OBD-apparaat scannen en u vragen of u het apparaat wilt verbinden. Het iOS-apparaat vraagt of u toegang tot het adres wilt toestaan, klik op Toestaan.",
    "text6": "Selecteer het apparaat dat verbonden moet worden en klik om verbinding te maken. Nadat de verbinding tot stand is gebracht, zal de startpagina van de APP de naam van het OBD-apparaat, het Bluetooth-adres en een meting op het dashboard weergeven."
  },

  "06fw": {
    "MID": "Monitornaam",
    "TID": "Testnaam",
    "CID": "Onderdeelnummer",
    "O2Sensor": "O2 Sensor Naam",
    "MIN": "Minimumlimiet",
    "MAX": "Maximumlimiet",
    "CURRENT": "Testwaarde"
  },

  "09fw": {
    "ipt": "Prestaties tijdens gebruik volgen",
    "IPT_08_1": "OBD-bewakingsomstandigheden tellen mee",
    "IPT_08_2": "Ontstekingscyclusteller",
    "IPT_08_3": "Voltooiing katalysatormonitor telt Bank 1",
    "IPT_08_4": "Catalyst Monitor Condities Ondervonden Tellingen Bank 1",
    "IPT_08_5": "Voltooiing katalysatormonitor telt bank 2",
    "IPT_08_6": "Katalysator bewaakt de aangetroffen omstandigheden telt bank 2",
    "IPT_08_7": "O2 Sensor Monitor Voltooiing Tellingen Bank 1",
    "IPT_08_8": "Ontdekte O2-sensorcondities tellen bank 1",
    "IPT_08_9": "O2 Sensor Monitor Voltooiing Tellingen Bank 2",
    "IPT_08_10": "Ontdekte O2-sensorcondities tellen Bank 2",
    "IPT_08_11": "EGR en/of VVT monitor voltooiingsvoorwaarde telt",
    "IPT_08_12": "EGR- en/of VVT-monitorcondities tellen mee",
    "IPT_08_13": "AIR Monitor Voltooiing Conditie Tellingen (Secundaire Lucht)",
    "IPT_08_14": "LUCHT-monitorcondities tellen mee (secundaire lucht)",
    "IPT_08_15": "EVAP-monitor voltooiingsvoorwaarde telt",
    "IPT_08_16": "EVAP-monitorcondities tellen mee",
    "IPT_08_17": "Secundaire O2 Sensor Monitor Voltooiing Tellingen Bank 1",
    "IPT_08_18": "Secundaire O2-sensor monitorcondities aangetroffen telt bank 1",
    "IPT_08_19": "Secundaire O2 Sensor Monitor Voltooiing Tellingen Bank 2",
    "IPT_08_20": "Secundaire O2-sensor monitorcondities aangetroffen telt bank 2",

    "IPT_08_des_1": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde OBD-bewakingsomstandigheden (algemene noemer).",
    "IPT_08_des_2": "toont het aantal keren dat de motor is gestart.",
    "IPT_08_des_3": "toont het aantal keren dat alle voorwaarden die nodig zijn om een storing in katalysatorsysteembank 1 te detecteren, zijn opgetreden (teller).",
    "IPT_08_des_4": "toont het aantal keren dat het voertuig is gebruikt onder de gespecificeerde katalysatorbewakingsomstandigheden (noemer)",
    "IPT_08_des_5": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in katalysatorsysteembank 2 te detecteren (teller).",
    "IPT_08_des_6": "toont het aantal keren dat het voertuig is gebruikt onder de gespecificeerde katalysatorbewakingsomstandigheden (noemer).",
    "IPT_08_des_7": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in zuurstofsensorbank 1 te detecteren (teller).",
    "IPT_08_des_8": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde zuurstofsensorbewakingsomstandigheden (noemer).",
    "IPT_08_des_9": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in zuurstofsensorbank 2 te detecteren (teller).",
    "IPT_08_des_10": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde omstandigheden voor bewaking van de zuurstofsensor (noemer).",
    "IPT_08_des_11": "toont het aantal keren dat alle voorwaarden die nodig zijn om een storing in het EGR/VVT-systeem te detecteren, zijn opgetreden (teller).",
    "IPT_08_des_12": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde EGR/VVT-systeembewakingsomstandigheden (noemer).",
    "IPT_08_des_13": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het AIR-systeem te detecteren (teller).",
    "IPT_08_des_14": "toont het aantal keren dat het voertuig is bediend in de gespecificeerde AIR-systeembewakingsomstandigheden (noemer).",
    "IPT_08_des_15": "toont het aantal keren dat alle voorwaarden die nodig zijn om een 0,020” (of 0,040”) lekstoring in het EVAP-systeem te detecteren, zijn opgetreden (teller).",
    "IPT_08_des_16": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde condities voor het controleren van lekstoringen in het EVAP-systeem (noemer).",
    "IPT_08_des_17": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing van secundaire zuurstofsensor bank 1 te detecteren (teller).",
    "IPT_08_des_18": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde bewakingsomstandigheden van de secundaire zuurstofsensor (noemer).",
    "IPT_08_des_19": "toont het aantal keren dat alle voorwaarden die nodig zijn om een storing van secundaire zuurstofsensorbank 2 te detecteren, zijn opgetreden (teller).",
    "IPT_08_des_20": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde bewakingsomstandigheden van de secundaire zuurstofsensor (noemer).",

    "IPT_0B_1": "OBD-bewakingsomstandigheden tellen mee",
    "IPT_0B_2": "Ontstekingscyclusteller",
    "IPT_0B_3": "NMHC Catalyst Monitor Voltooiing Conditie Tellingen",
    "IPT_0B_4": "NMHC-katalysator bewaakt de aangetroffen omstandigheden",
    "IPT_0B_5": "NOx/SCR Katalysator Monitor Voltooiing Conditie Telt",
    "IPT_0B_6": "NOx/SCR-katalysatorbewakingscondities tellen",
    "IPT_0B_7": "NOx Adsorber Monitor Voltooiingsvoorwaarde telt",
    "IPT_0B_8": "NOx-adsorber-monitorcondities tellen mee",
    "IPT_0B_9": "PM Filter Monitor Voltooiing Conditie Tellingen",
    "IPT_0B_10": "Aangetroffen PM-filtercondities tellen",
    "IPT_0B_11": "Uitlaatgassensor controleert voltooiingsvoorwaarde telt",
    "IPT_0B_12": "Uitlaatgassensor controleert aangetroffen omstandigheden telt",
    "IPT_0B_13": "EGR en/of VVT monitor voltooiingsvoorwaarde telt",
    "IPT_0B_14": "EGR- en/of VVT-monitorcondities tellen mee",
    "IPT_0B_15": "Boostdrukmonitor voltooiingsvoorwaarde telt",
    "IPT_0B_16": "Boostdrukbewakingscondities tellen mee",
    "IPT_0B_17": "Voltooiingsvoorwaarde brandstofmonitor telt",
    "IPT_0B_18": "Brandstofmonitorcondities tellen mee",

    "IPT_0B_des_1": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde OBD-bewakingsomstandigheden (algemene noemer).",
    "IPT_0B_des_2": "toont het aantal keren dat de motor is gestart.",
    "IPT_0B_des_3": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het NMHC-katalysatorsysteem te detecteren (teller).",
    "IPT_0B_des_4": "toont het aantal keren dat het voertuig is bediend onder de gespecificeerde NMHC-katalysatorbewakingsomstandigheden (noemer).",
    "IPT_0B_des_5": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het NOx-katalysatorsysteem te detecteren (teller).",
    "IPT_0B_des_6": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde NOx-katalysatorbewakingsomstandigheden (noemer).",
    "IPT_0B_des_7": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het NOx-adsorbersysteem te detecteren (teller).",
    "IPT_0B_des_8": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde NOx-adsorber-bewakingsomstandigheden (noemer).",
    "IPT_0B_des_9": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het PM-filtersysteem te detecteren (teller).",
    "IPT_0B_des_10": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde noemer voor PM-filterbewakingsomstandigheden).",
    "IPT_0B_des_11": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in de uitlaatgassensor te detecteren (teller)",
    "IPT_0B_des_12": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde uitlaatgassensorbewakingsomstandigheden (noemer).",
    "IPT_0B_des_13": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het EGR/VVT-systeem te detecteren (teller).",
    "IPT_0B_des_14": "toont het aantal keren dat het voertuig is gebruikt in de opgegeven EGR/VVT-systeembewakingsomstandigheden (noemer).",
    "IPT_0B_des_15": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het vuldruksysteem te detecteren (teller)",
    "IPT_0B_des_16": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde bewakingsomstandigheden van het laaddruksysteem (noemer)",
    "IPT_0B_des_17": "toont het aantal keren dat aan alle voorwaarden is voldaan die nodig zijn om een storing in het brandstofsysteem te detecteren (teller)",
    "IPT_0B_des_18": "toont het aantal keren dat het voertuig is gebruikt in de gespecificeerde bewakingsomstandigheden van het brandstofsysteem (noemer)."
  }
}