// 葡萄牙语
var i18n =  {
  "mt": "Dia",
  "xs": "Horas",
  "fz": "Minutos",
  "wxts": "Dicas",
  "zzjz": "carregando...",
  "noData": "SEM DADOS",
  "jchj": "Verificando o ambiente de login",
  "ckfw": "Intervalo de referência",
  "bbgl": {
    "bbts": "Lembrete de atualização de versão",
    "official": "Há novos recursos lançados, acesse o site oficial para baixar e atualizar a versão mais recente.",
    "apple": "Há novos recursos lançados, acesse a App Store para baixar a versão atualizada.",
    "google": "Há novos recursos lançados, acesse o Google Play para baixar a versão atualizada."
  },
  "uds": {
    "uds0001": "Selecionar módulo",
    "uds0002": "Selecione o módulo para ler",
    "uds0003": "A lista contém todos os módulos suportados da marca selecionada, é recomendável selecionar apenas os módulos já presentes no carro. No entanto, todos os módulos podem ser selecionados. O sistema detectará automaticamente as unidades realmente presentes no carro .",
    "uds0004": "Selecionar tudo",
    "uds0005": "Cancelar seleção de tudo",
    "uds0006": "Iniciar diagnóstico",
    "uds0007": "Fornecedor Personalizado"
  },
  "yjdl": {
    "yxdl": "Login de e-mail",
    "dlts": "Digite primeiro o Captcha gráfico e depois obtenha o Captcha do e-mail",
    "sryx": "Por favor, digite seu e-mail",
    "sryzm": "Por favor, digite Captcha",
    "xyb": "Próximo",
    "xgyx": "Modificar caixa de correio",
    "yxdz": "Endereço de e-mail",
    "fsyzm": "enviar código de acesso para e-mail",
    "yzm": "Código de acesso",
    "cxfs": "segundos para reenviar",
    "dl": "Entrar",
    "srtxyzm": "Digite o Captcha gráfico esquerdo",
    "yxbzq": "E-mail incorreto",
    "txyzmbzq": "O Captcha gráfico está incorreto",
    "fsdx": "Enviando Captcha",
    "yxyzmfscg": "Email Captcha enviado com sucesso",
    "yxbky": "O envio de e-mail é anormal! Verifique se o endereço de e-mail foi digitado corretamente e se o e-mail pode ser recebido normalmente.",
    "zzyz": "Verificando",
    "yzmcw": "O captcha do e-mail está incorreto",
    "clxxgl": "Gerenciamento de informações do veículo",
    "gxxx": "Atualizar informações",
    "dlcg": "Login com sucesso",
    "dlsb": "Falha no login",
    "clxx": "Informações do veículo",
    "czxx": "Informações do proprietário do carro",
    "wdl": "Não logado",
    "cl": "Veículo"
  },

  "OBDxncs": {
    "bt": "Comparação de adaptadores",
    "fbt": "maior significa mais rápido",
    "zjsd": "Velocidade ideal",
    "dqsd": "Velocidade atual",
    "xzmc": "A taxa na qual os parâmetros são lidos da ECU por segundo (unidade: parâmetros/segundo)",
    "sec_dt": "Testado com Galaxy Note 8 e Pixel 2",
    "sec_dd1": "(1) Os adaptadores Wi-Fi geralmente não são recomendados para Android, pois a maioria dos telefones perde a conexão de dados com a Internet durante o uso.",
    "sec_dd2": "(2) Todos os adaptadores testados são Bluetooth padrão, a menos que 'WiFi', 'USB' ou 'BLE' seja parte de seu nome",
    "text2": "Comparação de OBD"
  },

  "tsxx": {
    "qxz": "escolha",
    "qsr": "Por favor, digite",
    "qqr": "Confirmar",
    "qqx": "Cancelar",
    "notConnected": "Por favor, conecte seu dispositivo primeiro",
    "save": "Salvar o formulário com sucesso.",
    "dsyh": "Consumo de combustível em marcha lenta refere-se ao consumo de combustível no momento atual quando o veículo está parado, tendo o tempo como unidade estatística.",
    "xsyh": "O consumo de combustível ao volante refere-se ao consumo de combustível no momento atual em que o veículo está em movimento e toma a distância como unidade estatística.",
    "pjyh": "O consumo médio de combustível refere-se ao consumo de combustível por 100 quilômetros do veículo durante este processo de condução, e só é exibido após a condução por mais de 1 km.",
    "cqyh": "Consumo de combustível a longo prazo refere-se ao consumo de combustível consumido pelo veículo por 100 quilômetros durante a operação do APP.",
    "yhsupport": "Este carro não suporta exibição de consumo de combustível",
    "cg": "sucesso",
    "noTrouble": "Parabéns, seu carro está impecável, continue assim.",
    "noVin": "Insira o número do quadro de 17 dígitos para que possamos oferecer um melhor serviço.",
    "gzzsd": "O MIL é a abreviação de Lâmpada Indicadora de Mau Funcionamento. Quando a luz MIL está acesa, significa que o sistema do motor pode estar com defeito. O motivo para a luz MIL acesa pode ser que há muita deposição de carbono dentro do acelerador ou do motor, ou a proporção da mistura está desequilibrada após a falha do sensor de oxigênio, ou a luz do motor está acesa devido à má qualidade do combustível da gasolina e à combustão insuficiente do veículo.",
    "noDevelopment": "Em desenvolvimento, fique atento.",
    "zc": "Atualmente disponível para teste",
    "noSupport": "Atualmente não disponível para teste",
    "noNetwork": "Sua rede está indisponível no momento. Nenhuma rede afetará sua experiência.",
    "jy": "Desativado",
    "ywc": "Teste de status concluído",
    "noCompelte": "Teste de status não concluído",
    "noSupportPid": "Seu veículo não possui este teste!",
    "useReminders": "Lembrete: Após pausar, você pode aplicar zoom ou roaming deslizando o dedo no controle deslizante ou na tela sensível ao toque.",
    "noCompelteDes": "Se o estado pronto pode ser testado, mas não concluído, as seguintes medidas podem ser tomadas item por item: dirigir totalmente, manter o veículo, limpar a montagem, atualizar a ECU, etc. Espera-se que o processo de condução será operado de acordo com as especificações no futuro e a manutenção regular será realizada.",
    "fgf": "Esta função é exclusiva para produtos oficiais, use-a após a compra!",
    "b25": "Esta função é exclusiva do B25, use-a após a compra!"
  },

  "pid": {
    "dsyh": "Consumo de combustível em marcha lenta",
    "xsyh": "consumo de combustível",
    "ssyh": "Consumo Médio",
    "pjyh": "Consumo Instantâneo",
    "cqyh": "Consumo de combustível a longo prazo",
    "pjsd": "Velocidade média",
    "xslc": "Distância percorrida",
    "DTC_legnth": "# de DTCs armazenados nesta ECU",
    "MIL": "Status da lâmpada indicadora de mau funcionamento",
    "mil_0": "luz apagada",
    "mil_1": "luz acesa",
    "shxt": "Monitoramento de falha de ignição",
    "ryxt": "Monitoramento do sistema de combustível",
    "zhzj": "Monitoramento abrangente de componentes",

    "fdjlx": "Tipo de motor",
    "ysfdj": "ignição por compressão",
    "dhfdj": "ignição por faísca",
    "chj": "Monitoramento do catalisador",
    "jrchj": "Monitoramento de catalisador aquecido",
    "zfxt": "Monitoramento do sistema evaporativo",
    "eckqxt": "Monitoramento do sistema de ar secundário",
    "ktxtzlj": "Monitoramento do refrigerante do sistema A/C",
    "ycgqjrq": "Monitoramento do aquecedor do sensor de oxigênio",
    "ycgqjk": "Monitoramento do sensor de oxigênio",
    "erg": "Monitoramento do sistema EGR/VVT",
    "NMHC": "Monitoramento do Catalisador NMHC",
    "NOx": "Monitoramento NOx/SCR",
    "yl": "Reservado",
    "zyyl": "Monitoramento da pressão de reforço",
    "fqcgq": "Monitoramento do Sensor de Gás de Exaustão",
    "pmglq": "Monitoramento do monitor do filtro PM"
  },

  "sygl": {
    "xieyi": "Protocolo",
    "tips1": "Conecte o dispositivo",
    "tips2": "Por favor, ligue o Bluetooth! Ver ajuda",
    "tips3": "Não consegue encontrar o dispositivo? Veja a ajuda",
    "tips4": "Ative os serviços de localização",
    "tips5": "Universal",
    "tips6": "Versão econômica",
    "sdlj": "Selecione uma conexão manualmente"
  },

  "djz": {
    "noData": "Atualmente não há dados de quadro congelado",
    "previousFrame": "Frame anterior",
    "nextFrame": "Próximo quadro"
  },

  "fwgl": {
    "ybp": "Painel",
    "UDS": "Serviço de Diagnóstico Unificado (Teste)",
    "UDS_des": "Fornece serviço de diagnóstico unificado do veículo, mais ECUs e mais funções",
    "DTC": "Monitoramento DTC",
    "DTC_des": "Fornecer soluções profissionais para códigos de falha do veículo",
    "xcfx": "Análise de viagem",
    "xcfx_des": "Analise os dados de cada viagem",
    "xncs": "Teste de desempenho do veículo",
    "xncs_des": "Fornecer relatório de análise de desempenho do veículo profissional",
    "sssjl": "fluxo de dados em tempo real",
    "sssjl_des": "Solicitar dados de diagnóstico do trem de força atual",
    "gzzsd": "Detecção de indicador de falha",
    "gzzsd_des": "Fornece informações de operação do veículo após a luz de falha acender ou apagar",

    "pid0141": "Status de diagnóstico pronto",
    "pid0141_des": "Fornece o status de monitoramento do veículo desde que o DTC foi apagado e o status operacional do monitor do ciclo de condução atual",
    "$05": "Resultados do monitoramento do sensor de oxigênio",
    "$05_des": "Leia os resultados do teste de monitoramento do sensor de oxigênio do veículo",
    "$06": "Resultados de monitoramento específicos",
    "$06_des": "permitir o acesso aos resultados dos testes de monitoramento On-Board Diagnostic para componentes/sistemas específicos.",
    "$09": "Informações do veículo",
    "$09_des": "Ler informações e informações específicas do veículo",

    "clnj": "",
    "clnj_des": "",

    "obdTest": "Teste de desempenho OBD",
    "obdTest_des": "Teste vários indicadores de desempenho do OBD por meio de ferramentas de teste automatizadas.",
    "djz": "Congelar quadro",
    "djz_des": "Quando um DTC aparece no sistema de escapamento, a ECU armazena os dados quando o DTC aparece",
    "yjjc": "Detecção completa de veículos com um clique",
    "yjjc_des": "Detecção abrangente de todos os dados do sensor do veículo, informações do veículo, códigos de problemas, quadros congelados e informações de monitoramento do veículo."
  },

  "yjjc": {
    "cljkxx": "informações de monitoramento do veículo",
    "xx_09": "Detectando informações do veículo",
    "xx_03": "Detectando informações de falha",
    "xx_01": "Detectando informações de monitoramento do veículo",
    "xx_02": "Detectando informações do quadro congelado",
    "xx_05": "Detectando informações do sensor de oxigênio",
    "xx_06": "Lendo informações específicas do resultado do monitoramento"
  },

  "ybpgl": {
    "dcdy": "Tensão da bateria",
    "xhyb": "Medidor de Cruzeiro",
    "yhyb": "Medidor de consumo de combustível",
    "zdyyb": "Medidor Personalizado",
    "xz": "Adicionar Painel",
    "bj": "Editar Painel",
    "sc": "Excluir Painel",
    "delete_tips": "Tem certeza que deseja excluir o painel?"
  },


  "status": {
    "1000": "Bluetooth não está ligado",
    "1001": "Bluetooth desligado",
    "1002": "Aguardando economia de combustível",
    "1003": "Procurando OBD",
    "1004": "Conectando OBD",
    "1005": "Bluetooth está conectado",
    "1006": "escrever dados com sucesso",
    "1007": "Falha ao gravar dados",
    "1008": "Habilitar notificação com sucesso",
    "1009": "Nenhum dispositivo encontrado"
  },


  "szgl": {
    "bt": "Configuração",
    "label1": "Idioma",
    "value1": "Siga o sistema",
    "label2": "Política de Privacidade",
    "label3": "Ajuda para conexão",
    "label4": "Sobre",
    "label5": "Shopping oficial",
    "value5": "Shopping 1688",
    "label6": "Versão",
    "cjwt": "Problema comum",
    "unittitle": "Unidade",
    "unitvalue1": "Sistema métrico",
    "unitvalue2": "Unidades imperiais",
    "unitinfo": "Confirme se deseja trocar de unidade?"
  },

  "yygl": {
    "label": "Seguir o sistema",
    "des": "Depois de ligado, será configurado automaticamente de acordo com o idioma do sistema",
    "en": "Inglês",
    "zh": "Chinês Simplificado",
    "zwft": "chinês tradicional",
    "es": "espanhol",
    "kr": "coreano",
    "ru": "Russo",
    "ja": "Japonês",
    "it": "italiano",
    "hi": "Hindi",
		"pt": "Português",
		"de": "alemão",
		"fr": "Francês",
		"nl": "holandês",
		"fi": "finlandês",
		"pl": "polonês",
		"bn": "Bengali",
		"hu": "Húngaro",
		"cs": "Tcheco",
		"th": "Tailandês",
		"tr": "turco",
		"ms": "Malaio",
		"ro": "romeno",
		"sv": "sueco",
		"da": "dinamarquês"
  },


  "obdManage": {
    "bt": "Gerenciamento OBD",
    "search_tip": "Pesquise novamente ou compre nossos produtos",
    "buy_tip": "Por favor, vá ao shopping para comprar",
    "searchAgain": "Pesquisar novamente",
    "nearBy": "Equipamento próximo",
    "ls": "Equipamento histórico",
    "bz": "Ver ajuda",
    "del": "Excluir",
    "delConfirm": "Tem certeza que deseja excluir este registro?",
    "switched": "O dispositivo está prestes a ser trocado, tem certeza?",
    "qrxx": "Confirme se o Bluetooth e o comutador de informações de localização do celular estão ativados.",
    "searchAgain_message": "Tem certeza que deseja pesquisar novamente os dispositivos próximos?"
  },


  "gzjc": {
    "bt": "Diagnóstico",
    "btn": "Iniciar teste",
    "des": "Inicie uma verificação completa do seu veículo",
    "FaultCodeQuery": "Consulta de código de falha",
    "zzjc": "Testando",
    "clearFaultCode": "Limpar código de falha",
    "kscz": "pesquisar",
    "fxgz": "Código de falha encontrado",
    "notFound": "nenhum problema encontrado",
    "cxjc": "Reverificar",
    "modalTitle": "Tem certeza que deseja limpar o código de falha?",
    "modalContent": "Antes que a falha seja resolvida, é recomendável não limpar o código de falha à vontade. A maioria das ECUs não permite excluir o código de falha quando o motor está funcionando. Se o código de falha pode ser apagado ou não é, em última análise, determinado pela ECU. Excluir códigos de problema não é realmente a solução para o problema.",
    "sdjc": "Relatório de inspeção de profundidade",
    "num": "Número de códigos de falha",
    "gzmxx": "Detalhes do código de falha",
    "label1": "categoria",
    "label2": "Explicação do código de falha",
    "definition_03": "Códigos de problemas de diagnóstico",
    "definition_07": "Códigos de problema de diagnóstico pendentes",
    "definition_0A": "Códigos de problemas de diagnóstico permanentes",
    "03_des": "Quando uma anormalidade é detectada pela ECU (Unidade de Controle do Veículo), um código de problema é armazenado na memória. Este código de problema refere-se a uma situação anormal encontrada durante o processo de condução recente. Esses códigos de problema são mantidos na memória por um período de tempo, quando o código de falha for encontrado novamente, atualize o período de retenção.",
    "07_des": "Esta é uma anomalia não reconhecida durante a condução. Se a anomalia for repetida e identificada, o código de problema temporário será classificado como um código de problema confirmado. Se não for salvo, será excluído quando o motor for desligado.",
    "0A_des": "Como mostra um histórico de DTCs anteriores, não representa o status atual do veículo. Pode não ser possível excluir programaticamente os DTCs correspondentes.",
    "sys_P": "Sistema de powertrain (definido pelo fabricante)",
    "sys_B": "Sistema da carroceria (definido pelo fabricante)",
    "sys_C": "Sistema de suspensão do chassi (definido pelo fabricante)",
    "sys_U": "Sistema de comunicação de rede (definido pelo fabricante)",
    "zzs": "Todos os fabricantes de automóveis"
  },

  "clgl": {
    "bt": "Meu carro",
    "info1": "Informações básicas do carro",
    "clpp": "Marcas de carros",
    "xh": "Modelo do carro",
    "nk": "Ano",
    "rylx": "Tipo de combustível",
    "info2": "Outras informações do veículo",
    "atdp": "Protocolo de comunicação",
    "ati": "Versão do Adaptador",
    "vin": "Número de identificação do veículo",
    "cid": "Identificações de calibração",
    "cvn": "Números de verificação de calibração",
    "ecu": "Unidade de controle eletrônico",
    "ESN": "Número de série do motor",
    "EROTAN": "Regulamento de escape ou número de homologação",
    "FEOCNTR": "Contador de ciclos de ignição de operação do motor alimentado",
    "obd": "OBDSUP"
  },

  "clbj": {
    "warn1": "Por favor, preencha a marca do veículo",
    "warn2": "o modelo do carro é necessário",
    "warn3": "o ano do carro é necessário",
    "warn4": "vin é necessário",
    "warn5": "Por favor, preencha o número de identificação do veículo correto",
    "warn6": "o nome do proprietário do carro é obrigatório",
    "warn7": "telefone é necessário",
    "warn8": "Por favor, digite o telefone correto",
    "warn9": "Por favor, digite o e-mail correto",
    "bt": "A conexão OBD foi bem-sucedida",
    "title_sub": "As informações a seguir são muito importantes para um diagnóstico preciso, a fim de melhorar sua experiência. Certifique-se de preencher com atenção.",
    "ts_vin": "A localização do código VIN: geralmente localizado no lado esquerdo do painel de instrumentos, no canto inferior esquerdo do pára-brisa dianteiro; há também uma coluna de dobradiça de porta, uma coluna de trava de porta ou uma das colunas conectadas a a coluna da fechadura da porta; ou a porta perto do banco do motorista no interior.",
    "vin": "vin",
    "czxm": "Nome",
    "lxdh": "Telefone",
    "lxyx": "E-mail"
  },
  "ota": {
    "bt": "Atualização OTA",
    "jcdxbb": "Nova versão de firmware detectada",
    "gxnr": "Atualizar conteúdo",
    "fxsm": "Instruções de atualização",
    "fxsm_des": "Atualização OTA (tecnologia over-the-air) significa que o terminal móvel baixa remotamente o pacote de atualização no servidor para atualizar o firmware OBD. A atualização não afetará seu veículo e segurança de direção, sinta-se à vontade para usar Se ele avisar que a atualização falhou, não saia da interface, reinsira o OBD e continue a atualização.",
    "zysx": "Aviso",
    "zysx_des": "Não atualize enquanto dirige e não remova ou desligue o OBD durante a atualização.",
    "mssj": "Atualizar agora",
    "kssj": "Iniciar a atualização",
    "sjcg": "Atualização OTA com sucesso",
    "kqqxty": "Abrir uma nova experiência",
    "xzgj": "Baixar firmware",
    "zzxr": "Escrevendo",
    "zzsj": "Atualizando",
    "zzjy": "Verificando a integridade",
    "sjsb": "Falha na atualização, tente novamente"
  },

  "xcfx": {
    "ksxc": "Iniciar a viagem",
    "jsxc": "Terminar a viagem",
    "lsjl": "Registro histórico",
    "zlc": "Quilometragem total",
    "hs": "Demorado",
    "kssj": "Hora de início",
    "zyh": "Total de litros"
  },

  "xncs": {
    "jsxn": "Acelerado",
    "scxn": "Frenagem",
    "jlxn": "Distância",
    "des1": "Faixa de teste de velocidade",
    "des2": "velocidade ao frear",
    "des3": "distância de teste",
    "aqtx": "preste atenção à segurança na condução!",
    "kscs": "Iniciar teste",
    "cxcs": "Re-testar",
    "tz": "Pare",
    "tip1": "Ajuste a velocidade do veículo para",
    "tip2": "Pise no acelerador para acelerar para",
    "tip2_end": "Acima",
    "tip3": "Pise no freio para reduzir a velocidade para ",
    "tip4": "Por favor, dirija",
    "tip5": "Viajou",
    "max_sd": "Velocidade máxima",
    "max_jsd": "Aceleração máxima",
    "max_zs": "Velocidade máxima",
    "tx1": "A velocidade inicial não pode ser maior que a velocidade final",
    "tx2": "Por favor, preencha a velocidade de frenagem maior que 0",
    "tx3": "Por favor, preencha a distância de teste maior que 0"
  },

  "bzxx": {
    "title1": "Passo 1: Ligue o veículo",
    "title2": "Etapa 2: Conecte o dispositivo",
    "title3": "Etapa 3: Ativar Bluetooth e localização",
    "title4": "Etapa 4: Abra o APP",
    "title5": "Etapa 5: Conecte o dispositivo",
    "text1": "Encontre a localização da interface OBD do veículo. A interface OBD é uma interface feminina de 16 pinos. A interface é trapezoidal. Alguns modelos têm uma tampa na interface OBD. As portas OBD comuns são pretas, brancas ou azuis. A localização é geralmente no painel de acabamento interno abaixo do volante, perto dos joelhos do motorista. A localização da interface OBD pode ser diferente para diferentes modelos e modelos. A figura a seguir mostra a possível localização da interface OBD:",
    "text2": "Depois de encontrar a interface OBD, conecte o dispositivo na interface OBD. Certifique-se de que esteja totalmente conectado (muitos carros estão conectados na metade e a energia está ligada, mas os pinos de sinal podem não estar conectado) e o indicador de alimentação ou tela vermelha estiver ligado.",
    "text3": "Ative o Bluetooth e os interruptores de localização em seu telefone. Método: deslize para baixo na parte superior da tela do telefone, abra o menu de atalho e clique em Bluetooth e informações de localização. Ative o Bluetooth em seu dispositivo iOS.",
    "text4": "Abra o aplicativo e permita que ele use as informações de localização.",
    "text5": "Depois de concluir as etapas acima, entre no APP, o APP irá verificar automaticamente o dispositivo OBD e perguntar se deseja conectar o dispositivo. O dispositivo iOS pergunta se deseja permitir o acesso ao endereço, clique em Permitir.",
    "text6": "Selecione o dispositivo a ser conectado e clique para conectar. Após a conexão bem-sucedida, a página inicial do APP exibirá o nome do dispositivo OBD, o endereço Bluetooth e uma leitura aparecerá no painel."
  },

  "06fw": {
    "MID": "Nome do monitor",
    "TID": "Nome do teste",
    "CID": "Número do componente",
    "O2Sensor": "Nome do sensor de O2",
    "MIN": "Limite Mínimo",
    "MAX": "Limite Máximo",
    "CURRENT": "Valor de teste"
  },

  "09fw": {
    "ipt": "Acompanhamento de desempenho em uso",
    "IPT_08_1": "Contagens de condições de monitoramento OBD encontradas",
    "IPT_08_2": "Contador de ciclos de ignição",
    "IPT_08_3": "Banco 1 de contagens de conclusão do Monitor Catalyst",
    "IPT_08_4": "Condições do monitor do catalisador encontradas contam o banco 1",
    "IPT_08_5": "Banco 2 de contagens de conclusão do Monitor Catalyst",
    "IPT_08_6": "Condições do monitor do catalisador encontradas contam com o banco 2",
    "IPT_08_7": "Banco 1 de contagens de conclusão do monitor do sensor de O2",
    "IPT_08_8": "Condições do monitor do sensor de O2 encontradas contam banco 1",
    "IPT_08_9": "Banco 2 de contagens de conclusão do monitor do sensor de O2",
    "IPT_08_10": "Condições do monitor do sensor de O2 encontradas contam banco 2",
    "IPT_08_11": "Contagens de condições de conclusão do monitor EGR e/ou VVT",
    "IPT_08_12": "Contagens encontradas de condições de monitor EGR e/ou VVT",
    "IPT_08_13": "Contagens de Condição de Conclusão do Monitor AIR (Ar Secundário)",
    "IPT_08_14": "Contagens encontradas das condições do monitor de ar (ar secundário)",
    "IPT_08_15": "Contagens de condição de conclusão do monitor EVAP",
    "IPT_08_16": "Contagens encontradas das condições do monitor EVAP",
    "IPT_08_17": "Banco de contagens de conclusão do monitor de sensor de O2 secundário 1",
    "IPT_08_18": "Condições de Monitoramento de Sensor de O2 Secundárias encontradas Contagem Banco 1",
    "IPT_08_19": "Banco de contagens de conclusão do monitor de sensor de O2 secundário 2",
    "IPT_08_20": "Condições de Monitoramento de Sensor de O2 Secundárias encontradas Contagem Banco 2",

    "IPT_08_des_1": "exibe o número de vezes que o veículo foi operado nas condições de monitoramento OBD especificadas (denominador geral).",
    "IPT_08_des_2": "exibe a contagem do número de vezes que o motor foi ligado.",
    "IPT_08_des_3": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do banco 1 do sistema de catalisadores foram encontradas (numerador).",
    "IPT_08_des_4": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do catalisador (denominador).",
    "IPT_08_des_5": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do banco 2 do sistema de catalisadores foram encontradas (numerador).",
    "IPT_08_des_6": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do catalisador (denominador).",
    "IPT_08_des_7": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do banco de sensores de oxigênio 1 foram encontradas (numerador).",
    "IPT_08_des_8": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sensor de oxigênio (denominador).",
    "IPT_08_des_9": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do banco de sensores de oxigênio 2 foram encontradas (numerador).",
    "IPT_08_des_10": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sensor de oxigênio (denominador).",
    "IPT_08_des_11": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema EGR/VVT foram encontradas (numerador).",
    "IPT_08_des_12": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sistema EGR/VVT (denominador).",
    "IPT_08_des_13": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema AIR foram encontradas (numerador).",
    "IPT_08_des_14": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sistema AIR (denominador).",
    "IPT_08_des_15": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do vazamento do sistema EVAP de 0,020“ (ou 0,040”) foram encontradas (numerador).",
    "IPT_08_des_16": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento de mau funcionamento de vazamento do sistema EVAP (denominador).",
    "IPT_08_des_17": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do banco de sensores de oxigênio secundário 1 foram encontradas (numerador).",
    "IPT_08_des_18": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sensor de oxigênio secundário (denominador).",
    "IPT_08_des_19": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do banco de sensores de oxigênio secundário 2 foram encontradas (numerador).",
    "IPT_08_des_20": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sensor de oxigênio secundário (denominador).",

    "IPT_0B_1": "Contagens de condições de monitoramento OBD encontradas",
    "IPT_0B_2": "Contador de ciclos de ignição",
    "IPT_0B_3": "Contagens de condição de conclusão do monitor catalisador NMHC",
    "IPT_0B_4": "Contagens encontradas das condições do monitor do catalisador NMHC",
    "IPT_0B_5": "Contagens de condição de conclusão do monitor de catalisador NOx/SCR",
    "IPT_0B_6": "Contagens encontradas das condições do monitor do catalisador NOx/SCR",
    "IPT_0B_7": "Contagens de condição de conclusão do monitor adsorvedor de NOx",
    "IPT_0B_8": "Contagens encontradas das condições do monitor adsorvedor de NOx",
    "IPT_0B_9": "Contagens de Condição de Conclusão do Monitor de Filtro PM",
    "IPT_0B_10": "Contagens encontradas das condições do monitor de filtro PM",
    "IPT_0B_11": "Contagens de condições de conclusão do monitor do sensor de gases de escape",
    "IPT_0B_12": "Contagens encontradas das condições do monitor do sensor de gases de escape",
    "IPT_0B_13": "Contagens de condições de conclusão do monitor EGR e/ou VVT",
    "IPT_0B_14": "Contagens encontradas de condições de monitor EGR e/ou VVT",
    "IPT_0B_15": "Contagens de condição de conclusão do monitor de pressão de reforço",
    "IPT_0B_16": "Contagens encontradas das condições do monitor de pressão de reforço",
    "IPT_0B_17": "Contagens de condição de conclusão do monitor de combustível",
    "IPT_0B_18": "Contagens encontradas das condições do monitor de combustível",

    "IPT_0B_des_1": "exibe o número de vezes que o veículo foi operado nas condições de monitoramento OBD especificadas (denominador geral).",
    "IPT_0B_des_2": "exibe a contagem do número de vezes que o motor foi ligado.",
    "IPT_0B_des_3": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema catalisador NMHC foram encontradas (numerador).",
    "IPT_0B_des_4": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do catalisador NMHC (denominador).",
    "IPT_0B_des_5": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema catalisador de NOx foram encontradas (numerador).",
    "IPT_0B_des_6": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do catalisador NOx (denominador).",
    "IPT_0B_des_7": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema adsorvedor de NOx foram encontradas (numerador).",
    "IPT_0B_des_8": "exibe o número de vezes que o veículo foi operado no denominador de condições de monitoramento do adsorvedor de NOx especificado).",
    "IPT_0B_des_9": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema de filtro PM foram encontradas (numerador).",
    "IPT_0B_des_10": "exibe o número de vezes que o veículo foi operado no denominador de condições de monitoramento do filtro PM especificado).",
    "IPT_0B_des_11": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sensor de gases de escape foram encontradas (numerador)",
    "IPT_0B_des_12": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sensor de gases de escape (denominador).",
    "IPT_0B_des_13": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema EGR/VVT foram encontradas (numerador).",
    "IPT_0B_des_14": "exibe o número de vezes que o veículo foi operado nas condições de monitoramento do sistema EGR/VVT especificadas (denominador).",
    "IPT_0B_des_15": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema de pressão de reforço foram encontradas (numerador).",
    "IPT_0B_des_16": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sistema de aumento de pressão (denominador).",
    "IPT_0B_des_17": "exibe o número de vezes que todas as condições necessárias para detectar um mau funcionamento do sistema de combustível foram encontradas (numerador).",
    "IPT_0B_des_18": "exibe o número de vezes que o veículo foi operado nas condições especificadas de monitoramento do sistema de combustível (denominador)."
  }
}