// 罗马尼亚语
var i18n = {
	"mt": "Ziua",
	"xs": "Ore",
	"fz": "Minute",
	"wxts": "Sfaturi",
	"zzjz": "se încarcă...",
	"noData": "NU DATE",
	"jchj": "Se verifică mediul de conectare",
	"ckfw": "Interval de referință",
	"bbgl": {
		"bbts": "Memento de actualizare a versiunii",
		"official": "Au fost lansate funcții noi, vă rugăm să accesați site-ul oficial pentru a descărca și actualiza cea mai recentă versiune.",
		"apple": "Au fost lansate noi funcții, accesați App Store pentru a descărca versiunea actualizată.",
		"google": "Au fost lansate funcții noi, accesați Google Play pentru a descărca versiunea actualizată."
	},
	"uds": {
		"uds0001": "Selectați modulul",
		"uds0002": "Selectați modulul de citit",
		"uds0003": "Lista conține toate modulele acceptate ale mărcii selectate, este recomandat să selectați doar modulele deja prezente pe mașină. Cu toate acestea, toate modulele pot fi selectate. Sistemul va detecta automat unitățile prezente efectiv pe mașină .",
		"uds0004": "Selectați tot",
		"uds0005": "Anulați selectați totul",
		"uds0006": "Începe diagnosticul",
		"uds0007": "Vânzător personalizat"
	},
	"yjdl": {
		"yxdl": "Autentificare prin e-mail",
		"dlts": "Introduceți mai întâi graficul Captcha, apoi primiți e-mailul Captcha",
		"sryx": "Vă rugăm să introduceți adresa de e-mail",
		"sryzm": "Vă rugăm să introduceți Captcha",
		"xyb": "Următorul",
		"xgyx": "Modificați căsuța poștală",
		"yxdz": "Adresa de e-mail",
		"fsyzm": "trimite codul de acces la e-mail",
		"yzm": "Cod de acces",
		"cxfs": "secunde pentru a retrimite",
		"dl": "Autentificare",
		"srtxyzm": "Introduceți Captcha grafic din stânga",
		"yxbzq": "E-mailul este incorect",
		"txyzmbzq": "Captcha grafică este incorectă",
		"fsdx": "Se trimite Captcha",
		"yxyzmfscg": "E-mail Captcha trimis cu succes",
		"yxbky": "Trimiterea e-mailului este anormală! Vă rugăm să verificați dacă adresa de e-mail este introdusă corect și dacă e-mailul poate fi primit în mod normal.",
		"zzyz": "Se verifică",
		"yzmcw": "E-mailul Captcha este incorect",
		"clxxgl": "Gestionarea informațiilor despre vehicule",
		"gxxx": "Actualizează informațiile",
		"dlcg": "Autentificare cu succes",
		"dlsb": "Conectarea a eșuat",
		"clxx": "Informații despre vehicul",
		"czxx": "Informații despre proprietarul mașinii",
		"wdl": "Nu sunt autentificat",
		"cl": "Vehicul"
	},

	"OBDxncs": {
		"bt": "Comparație de adaptoare",
		"fbt": "mai mare înseamnă mai rapid",
		"zjsd": "Viteza optima",
		"dqsd": "Viteza curentă",
		"xzmc": "Rata la care parametrii sunt citiți de la ECU pe secundă (unitate: parametri/secundă)",
		"sec_dt": "Testat cu Galaxy Note 8 și Pixel 2",
		"sec_dd1": "(1) Adaptoarele Wi-Fi nu sunt, în general, recomandate pentru Android, deoarece majoritatea telefoanelor își pierd conexiunea de date la internet în timpul utilizării.",
		"sec_dd2": "(2) Toate adaptoarele testate sunt Bluetooth standard, cu excepția cazului în care WiFi, USB sau BLE face parte din numele lor",
		"text2": "Comparație OBD"
	},

	"tsxx": {
		"qxz": "alege",
		"qsr": "Vă rugăm să introduceți",
		"qqr": "Confirmați",
		"qqx": "Anulați",
		"notConnected": "Vă rugăm mai întâi să vă conectați dispozitivul",
		"save": "Salvați formularul cu succes.",
		"dsyh": "Consumul de combustibil la ralanti se referă la consumul de combustibil în momentul curent când vehiculul este staționat, având ca unitate statistică timpul.",
		"xsyh": "Consumul de combustibil la condus se referă la consumul de combustibil în momentul curent în care vehiculul este în stare de conducere și ia distanța ca unitate statistică.",
		"pjyh": "Consumul mediu de combustibil se referă la consumul de combustibil la 100 de kilometri ai vehiculului în timpul acestui proces de conducere și este afișat numai după ce ați condus mai mult de 1 km.",
		"cqyh": "Consumul de combustibil pe termen lung se referă la consumul de combustibil consumat de vehicul pentru 100 de kilometri în timpul funcționării APP.",
		"yhsupport": "Această mașină nu acceptă afișarea consumului de combustibil",
		"cg": "succes",
		"noTrouble": "Felicitări, mașina dvs. este fără defecte, vă rugăm să continuați așa.",
		"noVin": "Vă rugăm să introduceți numărul cadrului din 17 cifre, astfel încât să vă putem oferi un serviciu mai bun.",
		"gzzsd": "MIL este abrevierea pentru lampa indicatoare de defecțiune. Când ledul MIL este aprins, înseamnă că sistemul motorului poate funcționa defectuos. Motivul pentru care ledul MIL aprins poate fi faptul că există prea mult depunere de carbon în interiorul supapa de accelerație sau motorul sau raportul amestecului este dezechilibrat după ce senzorul de oxigen se defectează sau lumina motorului este aprinsă din cauza calității slabe a combustibilului a benzinei și a arderii insuficiente a vehiculului.",
		"noDevelopment": "În curs de dezvoltare, rămâneți la curent. ",
		"zc": "Disponibil în prezent pentru testare",
		"noSupport": "În prezent nu este disponibil pentru testare",
		"noNetwork": "Rețeaua dvs. este indisponibilă momentan. Nicio rețea nu vă va afecta experiența.",
		"jy": "Dezactivat",
		"ywc": "Testul de stare a fost finalizat",
		"noCompelte": "Testul de stare nu a fost finalizat",
		"noSupportPid": "Vehiculul dvs. nu are acest test!",
		"useReminders": "Memento: după pauză, puteți mări sau vă deplasați glisând cu degetul pe glisor sau pe ecranul tactil.",
		"noCompelteDes": "Dacă starea de pregătire poate fi testată, dar nu este finalizată, pot fi luate următoarele măsuri punct cu articol: conduceți complet, întrețineți vehiculul, curățați ansamblul, modernizați ECU etc. Se speră ca procesul de conducere. va fi operat în conformitate cu specificațiile în viitor, iar întreținerea regulată va fi efectuată.",
		"fgf": "Această funcție este exclusivă pentru produsele oficiale, vă rugăm să o utilizați după cumpărare!",
		"b25": "Această funcție este exclusivă pentru B25, vă rugăm să o utilizați după cumpărare!"
	},

	"pid": {
		"dsyh": "Consum de combustibil la ralanti",
		"xsyh": "Consum de combustibil",
		"ssyh": "Consum mediu",
		"pjyh": "Consum instantaneu",
		"cqyh": "Consum de combustibil pe termen lung",
		"pjsd": "Viteza medie",
		"xslc": "Distanța parcursă",
		"DTC_legnth": "# de DTC-uri stocate în acest ECU",
		"MIL": "Stare lampa indicator de defecțiune",
		"mil_0": "lumină stinsă",
		"mil_1": "lumină aprinsă",
		"shxt": "Monitorizare rateuri",
		"ryxt": "Monitorizarea sistemului de combustibil",
		"zhzj": "Monitorizare completă a componentelor",

		"fdjlx": "Tipul motor",
		"ysfdj": "aprindere prin compresie",
		"dhfdj": "aprindere prin scânteie",
		"chj": "Monitorizarea catalizatorului",
		"jrchj": "Monitorizare catalizator încălzit",
		"zfxt": "Monitorizarea sistemului de evaporare",
		"eckqxt": "Monitorizarea sistemului de aer secundar",
		"ktxtzlj": "Monitorizarea agentului frigorific al sistemului A/C",
		"ycgqjrq": "Monitorizarea încălzitorului senzorului de oxigen",
		"ycgqjk": "Monitorizare senzor de oxigen",
		"erg": "Monitorizare sistem EGR/VVT",
		"NMHC": "Monitorizare catalizator NMHC",
		"NOx": "Monitorizare NOx/SCR",
		"yl": "Rezervat",
		"zyyl": "Monitorizarea presiunii de supraalimentare",
		"fqcgq": "Monitorizare senzor gaz de eșapament",
		"pmglq": "Monitorizare monitorizare filtru PM"
	},

	"sygl": {
		"xieyi": "Protocol",
		"tips1": "Conectează dispozitivul",
		"tips2": "Vă rugăm să activați Bluetooth! Vedeți ajutorul",
		"tips3": "Nu puteți găsi dispozitivul? Vedeți ajutor",
		"tips4": "Vă rugăm să activați serviciile de localizare",
		"tips5": "Universal",
		"tips6": "Versiune rentabilă",
		"sdlj": "Selectați manual o conexiune"
	},

	"djz": {
		"noData": "În prezent nu există date de înghețare a cadrelor",
		"previousFrame": "Cadru precedent",
		"nextFrame": "Următorul cadru"
	},

	"fwgl": {
		"ybp": "Tabloul de bord",
		"UDS": "Serviciul de diagnosticare unificat (test)",
		"UDS_des": "Oferiți serviciul de diagnosticare unificată a vehiculului, mai multe ECU și mai multe funcții",
		"DTC": "Monitorizare DTC",
		"DTC_des": "Oferiți soluții profesionale pentru codurile de eroare ale vehiculului",
		"xcfx": "Analiza călătoriei",
		"xcfx_des": "Analizați datele fiecărei călătorii",
		"xncs": "Testarea performanței vehiculului",
		"xncs_des": "Oferiți un raport profesional de analiză a performanței vehiculului",
		"sssjl": "flux de date în timp real",
		"sssjl_des": "Solicitați date de diagnosticare curente ale grupului de propulsie",
		"gzzsd": "Detecție indicator de eroare",
		"gzzsd_des": "Oferă informații despre funcționarea vehiculului după ce lumina de eroare este aprinsă sau stinsă",

		"pid0141": "Stare gata de diagnosticare",
		"pid0141_des": "Oferă starea de monitorizare a vehiculului de când DTC a fost șters și starea curentă de funcționare a monitorului ciclului de conducere",
		"$05": "Rezultatele monitorizării senzorului de oxigen",
		"$05_des": "Citiți rezultatele testării monitorizării senzorului de oxigen al vehiculului",
		"$06": "Rezultatele monitorizării specifice",
		"$06_des": "permite accesul la rezultatele testelor de monitorizare de diagnosticare la bord pentru anumite componente/sisteme.",
		"$09": "Informații despre vehicul",
		"$09_des": "Citiți informațiile și informațiile specifice vehiculului",

		"clnj": "",
		"clnj_des": "",

		"obdTest": "Test de performanță OBD",
		"obdTest_des": "Testează diverși indicatori de performanță ai OBD prin instrumente automate de testare.",
		"djz": "Înghețați cadru",
		"djz_des": "Când apare un DTC în sistemul de evacuare, ECU stochează datele când apare DTC",
		"yjjc": "Detecție completă a vehiculului cu un singur clic",
		"yjjc_des": "Detecția completă a tuturor datelor senzorilor vehiculului, informații despre vehicul, coduri de eroare, cadre înghețate și informații despre monitorizarea vehiculului."
	},

	"yjjc": {
		"cljkxx": "informații de monitorizare a vehiculului",
		"xx_09": "Se detectează informații despre vehicul",
		"xx_03": "Se detectează informații despre eroare",
		"xx_01": "Detectarea informațiilor de monitorizare a vehiculului",
		"xx_02": "Se detectează informații despre cadru înghețat",
		"xx_05": "Se detectează informații despre senzorul de oxigen",
		"xx_06": "Citirea informațiilor specifice rezultatelor monitorizării"
	},

	"ybpgl": {
		"dcdy": "Tensiunea bateriei",
		"xhyb": "Contor de croazieră",
		"yhyb": "Contor de consum de combustibil",
		"zdyyb": "Contor personalizat",
		"xz": "Adăugați tabloul de bord",
		"bj": "Editați tabloul de bord",
		"sc": "Ștergeți tabloul de bord",
		"delete_tips": "Sunteți sigur că veți șterge tabloul de bord?"
	},


	"status": {
		"1000": "Bluetooth nu este pornit",
		"1001": "Bluetooth este dezactivat",
		"1002": "Se așteaptă economisirea combustibilului",
		"1003": "Se caută OBD",
		"1004": "Se conectează OBD",
		"1005": "Bluetooth-ul este conectat",
		"1006": "s-a scris cu succes datele",
		"1007": "Nu s-a putut scrie datele",
		"1008": "Activați notificarea cu succes",
		"1009": "Nu a fost găsit niciun dispozitiv"
	},


	"szgl": {
		"bt": "Setare",
		"label1": "Limba",
		"value1": "Urmăriți sistemul",
		"label2": "Politica de confidențialitate",
		"label3": "Ajutor pentru conectare",
		"label4": "Despre",
		"label5": "Mall oficial",
		"value5": "1688 Mall",
		"label6": "Versiune",
		"cjwt": "Problemă comună",
		"unittitle": "Unitate",
		"unitvalue1": "Sistem metric",
		"unitvalue2": "Unități imperiale",
		"unitinfo": "Confirmați dacă schimbați unitățile?"
	},

	"yygl": {
		"label": "Urmăriți sistemul",
		"des": "După ce este pornit, va fi setat automat în funcție de limba sistemului",
		"en": "Engleză",
		"zh": "Chineză simplificată",
		"zwft": "Chineză tradițională",
		"es": "spaniolă",
		"kr": "coreeană",
		"ru": "rusă",
		"ja": "Japoneză",
		"it": "italiană",
		"hi": "Hindi",
		"pt": "portugheză",
		"de": "germană",
		"fr": "franceză",
		"nl": "olandeză",
		"fi": "finlandeză",
		"pl": "poloneză",
		"bn": "bengali",
		"hu": "maghiară",
		"cs": "cehă",
		"th": "Thailandez",
		"tr": "Turc",
		"ms": "Malaez",
		"ro": "român",
		"sv": "suedez",
		"da": "daneză"
	},


	"obdManage": {
		"bt": "Gestionare OBD",
		"search_tip": "Vă rugăm să căutați din nou sau să cumpărați produsele noastre",
		"buy_tip": "Vă rugăm să mergeți la mall pentru a cumpăra",
		"searchAgain": "Căutați din nou",
		"nearBy": "Echipament din apropiere",
		"ls": "Echipament istoric",
		"bz": "Vedeți ajutorul",
		"del": "Șterge",
		"delConfirm": "Sunteți sigur că veți șterge această înregistrare?",
		"switched": "Dispozitivul este pe cale să fie comutat, ești sigur?",
		"qrxx": "Vă rugăm să confirmați că comutatorul Bluetooth și informații despre locație al telefonului mobil este activat.",
		"searchAgain_message": "Sigur veți căuta din nou dispozitivele din apropiere?"
	},


	"gzjc": {
		"bt": "Diagnostic",
		"btn": "Începe testarea",
		"des": "Începeți o scanare completă a vehiculului dvs.",
		"FaultCodeQuery": "Interogare cod eroare",
		"zzjc": "Testare",
		"clearFaultCode": "Ștergeți codul de eroare",
		"kscz": "căutați",
		"fxgz": "Cod de eroare găsit",
		"notFound": "nu au fost găsite probleme",
		"cxjc": "Reverificați",
		"modalTitle": "Sunteți sigur că doriți să ștergeți codul de eroare?",
		"modalContent": "Înainte de a se rezolva defecțiunea, se recomandă să nu ștergeți codul de eroare după bunul plac. Majoritatea ECU-urilor nu permit ștergerea codului de eroare atunci când motorul funcționează. Dacă codul de eroare poate fi șters sau nu, este în cele din urmă determinat de ECU. Ștergerea codurilor de eroare nu este cu adevărat soluția la problemă.",
		"sdjc": "Raport de inspecție în profunzime",
		"num": "Număr de coduri de eroare",
		"gzmxx": "Detalii cod de eroare",
		"label1": "categorie",
		"label2": "Explicația codului de eroare",
		"definition_03": "Coduri de diagnosticare a erorilor",
		"definition_07": "Coduri de diagnosticare în așteptare",
		"definition_0A": "Coduri de diagnosticare permanente",
		"03_des": "Când o anomalie este detectată de ECU (Unitatea de control al vehiculului), un cod de eroare este stocat în memorie. Acest cod de eroare se referă la o situație anormală găsită în timpul procesului recent de conducere. Aceste coduri de eroare sunt păstrate în memorie. pentru o perioadă de timp, când codul de eroare este găsit din nou, actualizați perioada de păstrare.",
		"07_des": "Aceasta este o anomalie nerecunoscută în timpul conducerii. Dacă anomalia este repetată și identificată, codul de eroare temporară va fi clasificat ca cod de eroare confirmat. Dacă nu este salvat, acesta va fi șters când motorul este oprit.",
		"0A_des": "Deoarece arată un istoric al DTC-urilor anterioare, nu reprezintă starea actuală a vehiculului. Este posibil să nu fie posibilă ștergerea programatică a DTC-urilor corespunzătoare.",
		"sys_P": "Sistem propulsor (definit de producător)",
		"sys_B": "Sistem caroserie (definit de producător)",
		"sys_C": "Sistem de suspensie a șasiului (definit de producător)",
		"sys_U": "Sistem de comunicare în rețea (definit de producător)",
		"zzs": "Toți producătorii de mașini"
	},

	"clgl": {
		"bt": "Mașina mea",
		"info1": "Informații de bază despre mașină",
		"clpp": "Marci de masini",
		"xh": "Model de mașină",
		"nk": "Anul",
		"rylx": "Tipul de combustibil",
		"info2": "Alte informații despre vehicul",
		"atdp": "Protocol de comunicare",
		"ati": "Versiune adaptor",
		"vin": "Numărul de identificare a vehiculului",
		"cid": "Identificări de calibrare",
		"cvn": "Numere de verificare a calibrării",
		"ecu": "Unitate de control electronic",
		"ESN": "Număr de serie al motorului",
		"EROTAN": "Număr de omologare de tip pentru reglarea eșapamentului",
		"FEOCNTR": "Contor ciclului de aprindere pentru funcționarea motorului alimentat",
		"obd": "OBDSUP"
	},

	"clbj": {
		"warn1": "Vă rugăm să completați marca vehiculului",
		"warn2": "este necesar modelul de mașină",
		"warn3": "Anul mașinii este necesar",
		"warn4": "vin este necesar",
		"warn5": "Vă rugăm să completați numărul corect de identificare a vehiculului",
		"warn6": "numele proprietarului mașinii este necesar",
		"warn7": "telefonul este necesar",
		"warn8": "Vă rugăm să introduceți telefonul corect",
		"warn9": "Vă rugăm să introduceți adresa de e-mail corectă",
		"bt": "Conexiunea OBD a avut succes",
		"title_sub": "Următoarele informații sunt foarte importante pentru un diagnostic precis, pentru a vă îmbunătăți experiența. Asigurați-vă că completați cu atenție.",
		"ts_vin": "Locația codului VIN: situată în general în partea stângă a panoului de bord, în partea stângă jos a parbrizului față; există și o coloană cu balamale pentru ușă, o coloană pentru încuietoarea ușii sau una dintre coloanele conectate la coloana de blocare a ușii; sau ușa de lângă scaunul șoferului în interior.",
		"vin": "Vin",
		"czxm": "Nume",
		"lxdh": "Telefon",
		"lxyx": "E-mail"
	},
	"ota": {
		"bt": "Actualizare OTA",
		"jcdxbb": "S-a detectat o nouă versiune de firmware",
		"gxnr": "Actualizează conținutul",
		"fxsm": "Instrucțiuni de actualizare",
		"fxsm_des": "Actualizarea OTA (tehnologie over-the-air) înseamnă că terminalul mobil descarcă de la distanță pachetul de upgrade de pe server pentru a actualiza firmware-ul OBD. Actualizarea nu va afecta vehiculul și siguranța la conducere, vă rugăm să nu ezitați să utilizați Dacă vă solicită că actualizarea a eșuat, vă rugăm să nu părăsiți interfața, reintroduceți OBD-ul și continuați actualizarea.",
		"zysx": "Avertisment",
		"zysx_des": "Nu faceți upgrade în timpul conducerii și nu scoateți sau opriți OBD-ul în timpul upgrade-ului.",
		"mssj": "Faceți upgrade acum",
		"kssj": "Începeți actualizarea",
		"sjcg": "Actualizare OTA cu succes",
		"kqqxty": "Deschide o nouă experiență",
		"xzgj": "Descărcați firmware",
		"zzxr": "Scriu",
		"zzsj": "În curs de actualizare",
		"zzjy": "Se verifică integritatea",
		"sjsb": "Actualizarea a eșuat, încercați din nou"
	},

	"xcfx": {
		"ksxc": "Începe călătoria",
		"jsxc": "Încheie călătoria",
		"lsjl": "Înregistrare istorică",
		"zlc": "Kilometraj total",
		"hs": "Consumator de timp",
		"kssj": "Ora de începere",
		"zyh": "Total litri"
	},

	"xncs": {
		"jsxn": "Accelerat",
		"scxn": "Frânare",
		"jlxn": "Distanța",
		"des1": "Interval de testare a vitezei",
		"des2": "viteza la franare",
		"des3": "distanța de testare",
		"aqtx": "vă rugăm să acordați atenție siguranței la volan!",
		"kscs": "Începe testarea",
		"cxcs": "Re-test",
		"tz": "Opriți",
		"tip1": "Vă rugăm să reglați viteza vehiculului la",
		"tip2": "Vă rugăm să pășiți pe accelerație pentru a accelera până la",
		"tip2_end": "Deasupra",
		"tip3": "Vă rugăm să pășiți pe frâne pentru a reduce viteza la",
		"tip4": "Vă rugăm să conduceți",
		"tip5": "A călătorit",
		"max_sd": "Viteza maxima",
		"max_jsd": "Accelerație maximă",
		"max_zs": "Viteza maxima",
		"tx1": "Viteza de pornire nu poate fi mai mare decât viteza finală",
		"tx2": "Vă rugăm să completați viteza de frânare mai mare de 0",
		"tx3": "Vă rugăm să completați distanța de testare mai mare decât 0"
	},

	"bzxx": {
		"title1": "Pasul 1: Porniți vehiculul",
		"title2": "Pasul 2: Conectați dispozitivul",
		"title3": "Pasul 3: Activați Bluetooth și locație",
		"title4": "Pasul 4: Deschideți aplicația",
		"title5": "Pasul 5: Conectați dispozitivul",
		"text1": "Găsiți locația interfeței OBD a vehiculului. Interfața OBD este o interfață feminină cu 16 pini. Interfața este trapezoidală. Unele modele au un capac pe interfața OBD. Porturile OBD obișnuite sunt negre, albe sau albastre. Locația este, în general, în panoul ornamental interior de sub volan, lângă genunchii șoferului. Locația interfeței OBD poate fi diferită pentru diferite modele și modele. Următoarea figură arată locația posibilă a interfeței OBD:",
		"text2": "După ce ați găsit interfața OBD, conectați dispozitivul la interfața OBD. Asigurați-vă că este conectat până la capăt (multe mașini sunt conectate la jumătate și alimentarea este pornită, dar pinii semnalului este posibil să nu fie conectat), iar indicatorul roșu de alimentare sau ecranul este aprins.",
		"text3": "Porniți Bluetooth și comutatoarele de locație pe telefon. Metodă: Glisați în jos în partea de sus a ecranului telefonului, deschideți meniul de comenzi rapide și faceți clic pe Bluetooth și informații despre locație. Activați Bluetooth pe dispozitivul iOS.",
		"text4": "Deschideți aplicația și permiteți aplicației să folosească informații despre locație.",
		"text5": "După finalizarea pașilor de mai sus, introduceți aplicația, aplicația va scana automat dispozitivul OBD și vă va întreba dacă conectați dispozitivul. Dispozitivul iOS vă întreabă dacă permiteți accesul la adresă, faceți clic pe Permite.",
		"text6": "Selectați dispozitivul de conectat și faceți clic pentru a vă conecta. După ce conexiunea a reușit, pagina de pornire a aplicației va afișa numele dispozitivului OBD, adresa Bluetooth și va apărea o citire pe tabloul de bord."
	},

	"06fw": {
		"MID": "Numele monitorului",
		"TID": "Numele testului",
		"CID": "Numărul componentei",
		"O2Sensor": "Numele senzorului O2",
		"MIN": "Limita minimă",
		"MAX": "Limita maximă",
		"CURRENT": "Valoare de testare"
	},

	"09fw": {
		"ipt": "Urmărirea performanței în utilizare",
		"IPT_08_1": "Condiții de monitorizare OBD întâlnite",
		"IPT_08_2": "Contor ciclu de aprindere",
		"IPT_08_3": "Terminarea monitorizării catalizatorului contează Banca 1",
		"IPT_08_4": "Condițiile de monitorizare a catalizatorului întâlnite contorizează Banca 1",
		"IPT_08_5": "Terminarea monitorizării catalizatorului contează Banca 2",
		"IPT_08_6": "Condițiile de monitorizare a catalizatorului întâlnite contorizează Banca 2",
		"IPT_08_7": "Terminarea monitorizării senzorului O2 contorizează Banca 1",
		"IPT_08_8": "Condițiile de monitorizare a senzorului O2 întâlnite contorizează Banca 1",
		"IPT_08_9": "Terminarea monitorizării senzorului O2 contorizează Banca 2",
		"IPT_08_10": "Condițiile de monitorizare a senzorului O2 întâlnite contorizează Banca 2",
		"IPT_08_11": "Numărări de condiții de finalizare a monitorizării EGR și/sau VVT",
		"IPT_08_12": "Numărări întâlnite pentru monitorizarea EGR și/sau VVT",
		"IPT_08_13": "Număr de condiții de finalizare a monitorizării AIR (aer secundar)",
		"IPT_08_14": "Condiții de monitorizare a aerului înregistrate (aer secundar)",
		"IPT_08_15": "Numărările condiției de finalizare a monitorului EVAP",
		"IPT_08_16": "Numărări întâlnite pentru monitorizarea EVAP",
		"IPT_08_17": "Încheierea monitorizării senzorului de O2 secundar contorizează Banca 1",
		"IPT_08_18": "Condițiile de monitorizare ale senzorului de O2 secundar întâmpinate contorizează Banca 1",
		"IPT_08_19": "Încheierea monitorizării senzorului de O2 secundar contorizează Banca 2",
		"IPT_08_20": "Condițiile de monitorizare ale senzorului de O2 secundar întâmpinate contorizează Banca 2",

		"IPT_08_des_1": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare OBD specificate (numitorul general).",
		"IPT_08_des_2": "afișează numărul de ori când motorul a fost pornit.",
		"IPT_08_des_3": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului de catalizator din banca 1 (numărător).",
		"IPT_08_des_4": "afișează numărul de ori când vehiculul a fost operat în condițiile specificate de monitorizare a catalizatorului (denominator).",
		"IPT_08_des_5": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului catalizatorului banca 2 (numerator).",
		"IPT_08_des_6": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a catalizatorului (numitorul).",
		"IPT_08_des_7": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a senzorului de oxigen din banca 1 (numărător).",
		"IPT_08_des_8": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare ale senzorului de oxigen specificate (denominator).",
		"IPT_08_des_9": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a senzorului de oxigen din banca 2 (numărător).",
		"IPT_08_des_10": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare ale senzorului de oxigen specificate (denominator).",
		"IPT_08_des_11": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului EGR/VVT (numărător).",
		"IPT_08_des_12": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a sistemului EGR/VVT (denominator).",
		"IPT_08_des_13": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului AIR (numărător).",
		"IPT_08_des_14": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a sistemului AIR (denominator).",
		"IPT_08_des_15": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului EVAP de 0,020” (sau 0,040”) (numărător).",
		"IPT_08_des_16": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a defecțiunilor sistemului EVAP (denominator).",
		"IPT_08_des_17": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune secundară a senzorului de oxigen din banca 1 (numerator).",
		"IPT_08_des_18": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare a senzorului de oxigen secundar specificate (denominator).",
		"IPT_08_des_19": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta defecțiunile unui senzor de oxigen secundar din banca 2 (numărător).",
		"IPT_08_des_20": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare ale senzorului de oxigen secundar specificate (denominator).",

		"IPT_0B_1": "Condițiile de monitorizare OBD întâlnite",
		"IPT_0B_2": "Contor ciclu de aprindere",
		"IPT_0B_3": "Numărările condiției de finalizare a monitorizării catalizatorului NMHC",
		"IPT_0B_4": "Numărări întâlnite în condițiile monitorizării catalizatorului NMHC",
		"IPT_0B_5": "Numărările condițiilor de finalizare a monitorizării catalizatorului NOx/SCR",
		"IPT_0B_6": "Numărări întâlnite pentru monitorizarea catalizatorului NOx/SCR",
		"IPT_0B_7": "Numărările condițiilor de finalizare a monitorizării absorbantului de NOx",
		"IPT_0B_8": "Numărări de condiții întâlnite pentru monitorizarea absorbantului de NOx",
		"IPT_0B_9": "Numărările condițiilor de finalizare a monitorizării filtrului PM",
		"IPT_0B_10": "Contări întâlnite în condițiile monitorizării filtrului PM",
		"IPT_0B_11": "Numărătoarea condițiilor de finalizare a monitorizării senzorului de gaze de eșapament",
		"IPT_0B_12": "Contări întâlnite de monitorizare a senzorului de gaze de eșapament",
		"IPT_0B_13": "Numărări de condiții de finalizare a monitorizării EGR și/sau VVT",
		"IPT_0B_14": "Numărări întâlnite pentru monitorizarea EGR și/sau VVT",
		"IPT_0B_15": "Numărări de condiții de finalizare a monitorului de presiune de supraalimentare",
		"IPT_0B_16": "Contări întâmpinate pentru monitorizarea presiunii de supraalimentare",
		"IPT_0B_17": "Contează condițiile de finalizare a monitorului de combustibil",
		"IPT_0B_18": "Condiții de monitorizare a combustibilului întâlnite",

		"IPT_0B_des_1": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare OBD specificate (numitorul general).",
		"IPT_0B_des_2": "afișează numărul de ori când motorul a fost pornit.",
		"IPT_0B_des_3": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului de catalizator NMHC (numerator).",
		"IPT_0B_des_4": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a catalizatorului NMHC (denominator).",
		"IPT_0B_des_5": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului catalizatorului de NOx (numerator).",
		"IPT_0B_des_6": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a catalizatorului de NOx (numitor).",
		"IPT_0B_des_7": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului de absorbție de NOx (numărător).",
		"IPT_0B_des_8": "afișează numărul de ori când vehiculul a fost operat în numitorul specificat de condiții de monitorizare a absorbantului de NOx).",
		"IPT_0B_des_9": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului de filtrare PM (numărător).",
		"IPT_0B_des_10": "afișează numărul de ori când vehiculul a fost operat în numitorul de condiții de monitorizare a filtrului PM specificat).",
		"IPT_0B_des_11": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a senzorului de gaze de eșapament (numărător)",
		"IPT_0B_des_12": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare specificate a senzorului de gaze de eșapament (denominator).",
		"IPT_0B_des_13": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului EGR/VVT (numărător).",
		"IPT_0B_des_14": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a sistemului EGR/VVT (denominator).",
		"IPT_0B_des_15": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului de presiune de supraalimentare (numerator).",
		"IPT_0B_des_16": "afișează de câte ori vehiculul a fost operat în condițiile de monitorizare specificate a sistemului de presiune de supraalimentare (denominator).",
		"IPT_0B_des_17": "afișează de câte ori au fost întâlnite toate condițiile necesare pentru a detecta o defecțiune a sistemului de alimentare cu combustibil (numărător).",
		"IPT_0B_des_18": "afișează de câte ori vehiculul a fost operat în condițiile specificate de monitorizare a sistemului de combustibil (denominator)."
	}
}
